import type { LocaleCode } from "./i18n";

export type AccountCopy = {
  account: string;
  signIn: string;
  signOut: string;
  selected: string;
  noCharge: string;
  privacy: string;
};

export type AccountIntroCopy = {
  title: string;
  description: string;
  accessCta: string;
};

const accountCopy = {
  en: { account: "Account", signIn: "Continue securely", signOut: "Sign out", selected: "Selected plan", noCharge: "Billing is not enabled. No charge today.", privacy: "No immigration documents or payment details are requested." },
  ja: { account: "アカウント", signIn: "安全に続ける", signOut: "ログアウト", selected: "選択したプラン", noCharge: "請求はまだ有効ではありません。本日の請求はありません。", privacy: "移民関連書類や支払い情報は求めません。" },
  ko: { account: "계정", signIn: "안전하게 계속", signOut: "로그아웃", selected: "선택한 요금제", noCharge: "결제가 아직 활성화되지 않았습니다. 오늘 청구되지 않습니다.", privacy: "이민 서류나 결제 정보를 요청하지 않습니다." },
  "zh-CN": { account: "账户", signIn: "安全继续", signOut: "退出登录", selected: "已选方案", noCharge: "付款尚未启用，今天不会收费。", privacy: "我们不会索取移民文件或付款资料。" },
  "zh-TW": { account: "帳號", signIn: "安全地繼續", signOut: "登出", selected: "已選方案", noCharge: "付款尚未啟用，今天不會收費。", privacy: "我們不會要求移民文件或付款資料。" },
  es: { account: "Cuenta", signIn: "Continuar de forma segura", signOut: "Cerrar sesión", selected: "Plan seleccionado", noCharge: "La facturación no está habilitada. Hoy no se realizará ningún cargo.", privacy: "No solicitamos documentos migratorios ni datos de pago." },
  fr: { account: "Compte", signIn: "Continuer en toute sécurité", signOut: "Se déconnecter", selected: "Forfait sélectionné", noCharge: "La facturation n’est pas activée. Aucun débit aujourd’hui.", privacy: "Aucun document d’immigration ni moyen de paiement n’est demandé." },
  de: { account: "Konto", signIn: "Sicher fortfahren", signOut: "Abmelden", selected: "Gewählter Tarif", noCharge: "Die Abrechnung ist nicht aktiviert. Heute erfolgt keine Belastung.", privacy: "Wir fragen weder Einwanderungsunterlagen noch Zahlungsdaten ab." },
  "pt-BR": { account: "Conta", signIn: "Continuar com segurança", signOut: "Sair", selected: "Plano selecionado", noCharge: "A cobrança não está ativada. Nenhum valor será cobrado hoje.", privacy: "Não solicitamos documentos de imigração nem dados de pagamento." },
  it: { account: "Account", signIn: "Continua in sicurezza", signOut: "Esci", selected: "Piano selezionato", noCharge: "La fatturazione non è attiva. Oggi non verrà effettuato alcun addebito.", privacy: "Non richiediamo documenti d’immigrazione né dati di pagamento." },
  nl: { account: "Account", signIn: "Veilig doorgaan", signOut: "Uitloggen", selected: "Gekozen abonnement", noCharge: "Facturering is niet ingeschakeld. Vandaag worden geen kosten berekend.", privacy: "We vragen niet om immigratiedocumenten of betaalgegevens." },
  pl: { account: "Konto", signIn: "Kontynuuj bezpiecznie", signOut: "Wyloguj się", selected: "Wybrany plan", noCharge: "Płatności nie są włączone. Dziś nie zostanie pobrana opłata.", privacy: "Nie prosimy o dokumenty imigracyjne ani dane płatnicze." },
  tr: { account: "Hesap", signIn: "Güvenle devam et", signOut: "Çıkış yap", selected: "Seçilen plan", noCharge: "Faturalandırma etkin değil. Bugün ücret alınmayacak.", privacy: "Göçmenlik belgesi veya ödeme bilgisi istemiyoruz." },
  ru: { account: "Аккаунт", signIn: "Продолжить безопасно", signOut: "Выйти", selected: "Выбранный план", noCharge: "Оплата пока не включена. Сегодня списаний не будет.", privacy: "Мы не запрашиваем иммиграционные документы или платёжные данные." },
  uk: { account: "Обліковий запис", signIn: "Продовжити безпечно", signOut: "Вийти", selected: "Вибраний план", noCharge: "Оплату ще не ввімкнено. Сьогодні списань не буде.", privacy: "Ми не запитуємо імміграційні документи чи платіжні дані." },
  ar: { account: "الحساب", signIn: "المتابعة بأمان", signOut: "تسجيل الخروج", selected: "الخطة المختارة", noCharge: "الفوترة غير مفعّلة. لن يتم تحصيل أي رسوم اليوم.", privacy: "لا نطلب مستندات الهجرة أو بيانات الدفع." },
  he: { account: "חשבון", signIn: "המשך באופן מאובטח", signOut: "יציאה", selected: "התוכנית שנבחרה", noCharge: "החיוב אינו פעיל. לא יתבצע חיוב היום.", privacy: "איננו מבקשים מסמכי הגירה או פרטי תשלום." },
  hi: { account: "खाता", signIn: "सुरक्षित रूप से जारी रखें", signOut: "साइन आउट", selected: "चुनी गई योजना", noCharge: "बिलिंग चालू नहीं है। आज कोई शुल्क नहीं लगेगा।", privacy: "हम आव्रजन दस्तावेज़ या भुगतान विवरण नहीं मांगते।" },
  bn: { account: "অ্যাকাউন্ট", signIn: "নিরাপদে চালিয়ে যান", signOut: "সাইন আউট", selected: "নির্বাচিত পরিকল্পনা", noCharge: "বিলিং চালু নেই। আজ কোনো চার্জ হবে না।", privacy: "আমরা অভিবাসন নথি বা পেমেন্টের তথ্য চাই না।" },
  ur: { account: "اکاؤنٹ", signIn: "محفوظ طریقے سے جاری رکھیں", signOut: "سائن آؤট", selected: "منتخب منصوبہ", noCharge: "بلنگ فعال نہیں ہے۔ آج کوئی رقم وصول نہیں کی جائے گی۔", privacy: "ہم امیگریشن دستاویزات یا ادائیگی کی تفصیلات نہیں مانگتے۔" },
  id: { account: "Akun", signIn: "Lanjutkan dengan aman", signOut: "Keluar", selected: "Paket yang dipilih", noCharge: "Penagihan belum diaktifkan. Tidak ada biaya hari ini.", privacy: "Kami tidak meminta dokumen imigrasi atau detail pembayaran." },
  ms: { account: "Akaun", signIn: "Teruskan dengan selamat", signOut: "Log keluar", selected: "Pelan dipilih", noCharge: "Pengebilan belum diaktifkan. Tiada caj hari ini.", privacy: "Kami tidak meminta dokumen imigresen atau butiran pembayaran." },
  th: { account: "บัญชี", signIn: "ดำเนินการต่ออย่างปลอดภัย", signOut: "ออกจากระบบ", selected: "แผนที่เลือก", noCharge: "ยังไม่เปิดใช้การเรียกเก็บเงิน วันนี้ไม่มีค่าใช้จ่าย", privacy: "เราไม่ขอเอกสารตรวจคนเข้าเมืองหรือข้อมูลการชำระเงิน" },
  vi: { account: "Tài khoản", signIn: "Tiếp tục an toàn", signOut: "Đăng xuất", selected: "Gói đã chọn", noCharge: "Thanh toán chưa được bật. Hôm nay không phát sinh phí.", privacy: "Chúng tôi không yêu cầu giấy tờ nhập cư hoặc thông tin thanh toán." },
  fil: { account: "Account", signIn: "Magpatuloy nang ligtas", signOut: "Mag-sign out", selected: "Napiling plano", noCharge: "Hindi pa naka-enable ang billing. Walang sisingilin ngayon.", privacy: "Hindi kami humihingi ng dokumento sa imigrasyon o detalye ng bayad." },
  sv: { account: "Konto", signIn: "Fortsätt säkert", signOut: "Logga ut", selected: "Vald plan", noCharge: "Fakturering är inte aktiverad. Ingen avgift tas ut i dag.", privacy: "Vi begär inga immigrationshandlingar eller betalningsuppgifter." },
  no: { account: "Konto", signIn: "Fortsett sikkert", signOut: "Logg ut", selected: "Valgt abonnement", noCharge: "Fakturering er ikke aktivert. Du belastes ikke i dag.", privacy: "Vi ber ikke om immigrasjonsdokumenter eller betalingsopplysninger." },
  da: { account: "Konto", signIn: "Fortsæt sikkert", signOut: "Log ud", selected: "Valgt abonnement", noCharge: "Fakturering er ikke aktiveret. Du bliver ikke opkrævet i dag.", privacy: "Vi beder ikke om immigrationsdokumenter eller betalingsoplysninger." },
  fi: { account: "Tili", signIn: "Jatka turvallisesti", signOut: "Kirjaudu ulos", selected: "Valittu tilaus", noCharge: "Laskutus ei ole käytössä. Tänään ei veloiteta.", privacy: "Emme pyydä maahanmuuttoasiakirjoja tai maksutietoja." },
  cs: { account: "Účet", signIn: "Pokračovat bezpečně", signOut: "Odhlásit se", selected: "Vybraný tarif", noCharge: "Fakturace není zapnutá. Dnes nebude nic účtováno.", privacy: "Nevyžadujeme imigrační dokumenty ani platební údaje." },
  sk: { account: "Účet", signIn: "Pokračovať bezpečne", signOut: "Odhlásiť sa", selected: "Vybraný plán", noCharge: "Fakturácia nie je zapnutá. Dnes sa nič neúčtuje.", privacy: "Nevyžadujeme imigračné dokumenty ani platobné údaje." },
  hu: { account: "Fiók", signIn: "Folytatás biztonságosan", signOut: "Kijelentkezés", selected: "Kiválasztott csomag", noCharge: "A számlázás nincs bekapcsolva. Ma nem terheljük meg.", privacy: "Nem kérünk bevándorlási dokumentumokat vagy fizetési adatokat." },
  ro: { account: "Cont", signIn: "Continuă în siguranță", signOut: "Deconectare", selected: "Plan selectat", noCharge: "Facturarea nu este activată. Astăzi nu se percepe nicio taxă.", privacy: "Nu solicităm documente de imigrare sau date de plată." },
  el: { account: "Λογαριασμός", signIn: "Συνέχεια με ασφάλεια", signOut: "Αποσύνδεση", selected: "Επιλεγμένο πρόγραμμα", noCharge: "Η χρέωση δεν είναι ενεργή. Δεν θα υπάρξει χρέωση σήμερα.", privacy: "Δεν ζητάμε έγγραφα μετανάστευσης ή στοιχεία πληρωμής." },
  bg: { account: "Профил", signIn: "Продължете сигурно", signOut: "Изход", selected: "Избран план", noCharge: "Таксуването не е активирано. Днес няма да бъдете таксувани.", privacy: "Не изискваме имиграционни документи или данни за плащане." },
  hr: { account: "Račun", signIn: "Nastavi sigurno", signOut: "Odjava", selected: "Odabrani plan", noCharge: "Naplata nije omogućena. Danas nema terećenja.", privacy: "Ne tražimo imigracijske dokumente ni podatke za plaćanje." },
  sr: { account: "Налог", signIn: "Настави безбедно", signOut: "Одјава", selected: "Изабрани план", noCharge: "Наплата није омогућена. Данас нема задужења.", privacy: "Не тражимо имиграциона документа нити податке за плаћање." },
  sl: { account: "Račun", signIn: "Nadaljuj varno", signOut: "Odjava", selected: "Izbrani paket", noCharge: "Obračunavanje ni omogočeno. Danes ne bo bremenitve.", privacy: "Ne zahtevamo priseljenskih dokumentov ali podatkov za plačilo." },
  sw: { account: "Akaunti", signIn: "Endelea kwa usalama", signOut: "Ondoka", selected: "Mpango uliochaguliwa", noCharge: "Malipo hayajawashwa. Hakuna ada leo.", privacy: "Hatuombi hati za uhamiaji au maelezo ya malipo." },
  fa: { account: "حساب", signIn: "ادامه امن", signOut: "خروج", selected: "طرح انتخاب‌شده", noCharge: "صورتحساب فعال نیست. امروز هزینه‌ای دریافت نمی‌شود.", privacy: "ما مدارک مهاجرت یا اطلاعات پرداخت درخواست نمی‌کنیم." },
} satisfies Record<LocaleCode, AccountCopy>;

const accountIntroTitle = {
  en: "Keep your interview preparation in one place.",
  ja: "面接準備をひとつの場所にまとめましょう。",
  ko: "면접 준비를 한곳에서 관리하세요.",
  "zh-CN": "把面试准备集中在一个地方。",
  "zh-TW": "將面試準備集中在同一個地方。",
  es: "Mantén tu preparación para entrevistas en un solo lugar.",
  fr: "Regroupez votre préparation aux entretiens au même endroit.",
  de: "Halte deine Interviewvorbereitung an einem Ort zusammen.",
  "pt-BR": "Mantenha sua preparação para entrevistas em um só lugar.",
  it: "Tieni la preparazione ai colloqui in un unico posto.",
  nl: "Houd je sollicitatievoorbereiding op één plek.",
  pl: "Przygotowanie do rozmowy w jednym miejscu.",
  tr: "Mülakat hazırlığını tek yerde tut.",
  ru: "Храните всю подготовку к собеседованию в одном месте.",
  uk: "Зберігайте всю підготовку до співбесіди в одному місці.",
  ar: "اجمع تحضيرك للمقابلة في مكان واحد.",
  he: "שמרו את ההכנה לראיון במקום אחד.",
  hi: "अपनी इंटरव्यू तैयारी एक ही जगह रखें।",
  bn: "আপনার সাক্ষাৎকারের প্রস্তুতি এক জায়গায় রাখুন।",
  ur: "اپنی انٹرویو تیاری ایک جگہ رکھیں۔",
  id: "Simpan persiapan wawancara di satu tempat.",
  ms: "Simpan persediaan temu duga anda di satu tempat.",
  th: "เก็บการเตรียมสัมภาษณ์ไว้ในที่เดียว",
  vi: "Giữ mọi nội dung chuẩn bị phỏng vấn ở một nơi.",
  fil: "Panatilihin sa iisang lugar ang paghahanda mo sa interview.",
  sv: "Samla dina intervjuförberedelser på ett ställe.",
  no: "Samle intervjuforberedelsene på ett sted.",
  da: "Saml din interviewforberedelse ét sted.",
  fi: "Pidä haastatteluun valmistautuminen yhdessä paikassa.",
  cs: "Mějte přípravu na pohovor na jednom místě.",
  sk: "Majte prípravu na pohovor na jednom mieste.",
  hu: "Tartsd egy helyen az interjúfelkészülésedet.",
  ro: "Păstrează pregătirea pentru interviu într-un singur loc.",
  el: "Κρατήστε την προετοιμασία για τη συνέντευξη σε ένα μέρος.",
  bg: "Поддържайте подготовката си за интервю на едно място.",
  hr: "Držite pripremu za razgovor na jednom mjestu.",
  sr: "Држите припрему за интервју на једном месту.",
  sl: "Pripravo na razgovor imejte na enem mestu.",
  sw: "Weka maandalizi yako ya usaili mahali pamoja.",
  fa: "آمادگی مصاحبه را در یک جا نگه دارید.",
} satisfies Record<LocaleCode, string>;

const requiredLoginNotice = {
  en: "Sign in is required to use personal tools and save your evidence map, interview stories, practice progress, tracker, and feedback.",
  ja: "個人向け機能を利用し、証拠マップ、面接ストーリー、練習の進捗、トラッカー、フィードバックを保存するには、サインインが必要です。",
  ko: "개인 기능을 사용하고 증거 맵, 면접 스토리, 연습 진행 상황, 트래커, 피드백을 저장하려면 로그인이 필요합니다.",
  "zh-CN": "使用个人功能以及保存证据地图、面试故事、练习进度、追踪记录和反馈前，必须先登录。",
  "zh-TW": "使用個人功能，以及保存證據地圖、面試故事、練習進度、追蹤紀錄與意見回饋前，必須先登入。",
  es: "Debes iniciar sesión para usar las herramientas personales y guardar tu mapa de evidencias, historias, progreso, seguimiento y comentarios.",
  fr: "La connexion est obligatoire pour utiliser les outils personnels et enregistrer votre carte de preuves, vos récits, vos progrès, votre suivi et vos avis.",
  de: "Du musst dich anmelden, um persönliche Werkzeuge zu nutzen und Evidenzkarte, Interviewgeschichten, Übungsfortschritt, Tracker und Feedback zu speichern.",
  "pt-BR": "É necessário entrar para usar as ferramentas pessoais e salvar seu mapa de evidências, histórias, progresso, rastreador e feedback.",
  it: "Devi accedere per usare gli strumenti personali e salvare la mappa delle prove, le storie, i progressi, il tracker e il feedback.",
  nl: "Je moet inloggen om persoonlijke hulpmiddelen te gebruiken en je bewijskaart, verhalen, oefenvoortgang, tracker en feedback op te slaan.",
  pl: "Logowanie jest wymagane, aby korzystać z narzędzi osobistych i zapisywać mapę dowodów, historie, postępy, tracker oraz opinie.",
  tr: "Kişisel araçları kullanmak ve kanıt haritanı, hikâyelerini, ilerlemeni, takip kayıtlarını ve geri bildirimini kaydetmek için giriş yapmalısın.",
  ru: "Вход обязателен для личных инструментов и сохранения карты доказательств, историй, прогресса, трекера и отзывов.",
  uk: "Вхід обов’язковий для особистих інструментів і збереження карти доказів, історій, прогресу, трекера та відгуків.",
  ar: "يلزم تسجيل الدخول لاستخدام الأدوات الشخصية وحفظ خريطة الأدلة وقصص المقابلة وتقدم التدريب والمتابعة والملاحظات.",
  he: "יש להתחבר כדי להשתמש בכלים האישיים ולשמור את מפת הראיות, סיפורי הראיון, ההתקדמות, המעקב והמשוב.",
  hi: "व्यक्तिगत टूल इस्तेमाल करने और अपना एविडेंस मैप, इंटरव्यू कहानियाँ, अभ्यास प्रगति, ट्रैकर और प्रतिक्रिया सेव करने के लिए साइन इन करना आवश्यक है।",
  bn: "ব্যক্তিগত টুল ব্যবহার এবং প্রমাণের মানচিত্র, সাক্ষাৎকারের গল্প, অনুশীলনের অগ্রগতি, ট্র্যাকার ও মতামত সংরক্ষণ করতে সাইন ইন করা আবশ্যক।",
  ur: "ذاتی ٹولز استعمال کرنے اور ثبوتی نقشہ، انٹرویو کہانیاں، مشق کی پیش رفت، ٹریکر اور رائے محفوظ کرنے کے لیے سائن ان ضروری ہے۔",
  id: "Anda harus masuk untuk menggunakan alat pribadi dan menyimpan peta bukti, cerita wawancara, progres latihan, pelacak, serta umpan balik.",
  ms: "Anda mesti log masuk untuk menggunakan alat peribadi dan menyimpan peta bukti, cerita temu duga, kemajuan latihan, penjejak serta maklum balas.",
  th: "ต้องลงชื่อเข้าใช้เพื่อใช้เครื่องมือส่วนบุคคลและบันทึกแผนที่หลักฐาน เรื่องราวสัมภาษณ์ ความคืบหน้า ตัวติดตาม และข้อเสนอแนะ",
  vi: "Bạn phải đăng nhập để dùng các công cụ cá nhân và lưu bản đồ bằng chứng, câu chuyện phỏng vấn, tiến độ luyện tập, theo dõi và phản hồi.",
  fil: "Kailangang mag-sign in para magamit ang mga personal na tool at ma-save ang evidence map, mga kuwento, progreso, tracker, at feedback.",
  sv: "Du måste logga in för att använda personliga verktyg och spara din beviskarta, dina berättelser, framsteg, spårning och feedback.",
  no: "Du må logge inn for å bruke personlige verktøy og lagre beviskartet, historiene, fremdriften, sporingen og tilbakemeldingene.",
  da: "Du skal logge ind for at bruge personlige værktøjer og gemme dit evidenskort, historier, fremskridt, tracker og feedback.",
  fi: "Sinun on kirjauduttava käyttääksesi henkilökohtaisia työkaluja ja tallentaaksesi näyttökartan, tarinat, edistymisen, seurannan ja palautteen.",
  cs: "Pro používání osobních nástrojů a ukládání mapy důkazů, příběhů, pokroku, sledování a zpětné vazby je nutné se přihlásit.",
  sk: "Na používanie osobných nástrojov a uloženie mapy dôkazov, príbehov, pokroku, sledovania a spätnej väzby sa musíte prihlásiť.",
  hu: "A személyes eszközök használatához, valamint a bizonyítéktérkép, történetek, haladás, követés és visszajelzés mentéséhez be kell jelentkezned.",
  ro: "Trebuie să te conectezi pentru a folosi instrumentele personale și a salva harta dovezilor, poveștile, progresul, urmărirea și feedbackul.",
  el: "Απαιτείται σύνδεση για τη χρήση προσωπικών εργαλείων και την αποθήκευση του χάρτη τεκμηρίων, των ιστοριών, της προόδου, της παρακολούθησης και των σχολίων.",
  bg: "Трябва да влезете, за да използвате личните инструменти и да запазвате картата на доказателствата, историите, напредъка, проследяването и обратната връзка.",
  hr: "Morate se prijaviti za korištenje osobnih alata i spremanje karte dokaza, priča, napretka, praćenja i povratnih informacija.",
  sr: "Морате се пријавити да бисте користили личне алате и сачували мапу доказа, приче, напредак, праћење и повратне информације.",
  sl: "Za uporabo osebnih orodij ter shranjevanje zemljevida dokazov, zgodb, napredka, sledenja in povratnih informacij se morate prijaviti.",
  sw: "Lazima uingie ili kutumia zana binafsi na kuhifadhi ramani ya ushahidi, hadithi, maendeleo, ufuatiliaji na maoni.",
  fa: "برای استفاده از ابزارهای شخصی و ذخیره نقشه شواهد، داستان‌ها، پیشرفت تمرین، پیگیری و بازخورد باید وارد شوید.",
} satisfies Record<LocaleCode, string>;

const privateActivityNotice = {
  en: "Only you can see your saved activity. We do not collect anonymous resumes, job descriptions, interview transcripts, or voice recordings.",
  ja: "保存した履歴を閲覧できるのは本人だけです。匿名の履歴書、求人票、面接の文字起こし、音声録音は収集しません。",
  ko: "저장된 활동은 본인만 볼 수 있습니다. 익명 사용자의 이력서, 채용 공고, 면접 기록 또는 음성 녹음은 수집하지 않습니다.",
  "zh-CN": "只有你可以查看已保存的活动。我们不会收集匿名访客的履历、职位描述、面试逐字稿或语音录音。",
  "zh-TW": "只有你可以查看已保存的活動。我們不會收集匿名訪客的履歷、職缺描述、面試逐字稿或語音錄音。",
  es: "Solo tú puedes ver tu actividad guardada. No recopilamos currículums, ofertas, transcripciones ni grabaciones de voz de visitantes anónimos.",
  fr: "Vous seul pouvez voir votre activité enregistrée. Nous ne collectons pas les CV, offres, transcriptions ou enregistrements vocaux des visiteurs anonymes.",
  de: "Nur du kannst deine gespeicherten Aktivitäten sehen. Wir erfassen keine anonymen Lebensläufe, Stellenanzeigen, Interviewtranskripte oder Sprachaufnahmen.",
  "pt-BR": "Só você pode ver sua atividade salva. Não coletamos currículos, vagas, transcrições ou gravações de voz de visitantes anônimos.",
  it: "Solo tu puoi vedere le attività salvate. Non raccogliamo CV, annunci, trascrizioni o registrazioni vocali di visitatori anonimi.",
  nl: "Alleen jij kunt je opgeslagen activiteit zien. We verzamelen geen anonieme cv’s, vacatures, interviewtranscripten of spraakopnamen.",
  pl: "Tylko Ty widzisz zapisaną aktywność. Nie zbieramy anonimowych CV, ofert pracy, transkrypcji rozmów ani nagrań głosu.",
  tr: "Kaydedilen etkinliğini yalnızca sen görebilirsin. Anonim ziyaretçilerin özgeçmişlerini, ilanlarını, görüşme dökümlerini veya ses kayıtlarını toplamayız.",
  ru: "Сохранённые действия видите только вы. Мы не собираем анонимные резюме, вакансии, расшифровки интервью или голосовые записи.",
  uk: "Збережені дії бачите лише ви. Ми не збираємо анонімні резюме, вакансії, розшифровки співбесід або голосові записи.",
  ar: "لا يرى نشاطك المحفوظ سواك. لا نجمع سيراً ذاتية أو أوصاف وظائف أو نصوص مقابلات أو تسجيلات صوتية من الزوار المجهولين.",
  he: "רק אתם יכולים לראות את הפעילות השמורה. איננו אוספים קורות חיים, תיאורי משרה, תמלילי ראיונות או הקלטות קול של מבקרים אנונימיים.",
  hi: "आपकी सेव की गई गतिविधि केवल आपको दिखती है। हम गुमनाम विज़िटर के रिज़्यूमे, जॉब विवरण, इंटरव्यू ट्रांसक्रिप्ट या वॉइस रिकॉर्डिंग एकत्र नहीं करते।",
  bn: "শুধু আপনিই সংরক্ষিত কার্যকলাপ দেখতে পারবেন। আমরা বেনামী দর্শকের জীবনবৃত্তান্ত, চাকরির বিবরণ, সাক্ষাৎকারের প্রতিলিপি বা কণ্ঠ রেকর্ডিং সংগ্রহ করি না।",
  ur: "آپ کی محفوظ سرگرمی صرف آپ دیکھ سکتے ہیں۔ ہم گمنام افراد کے ریزیومے، ملازمت کی تفصیل، انٹرویو متن یا آواز کی ریکارڈنگ جمع نہیں کرتے۔",
  id: "Hanya Anda yang dapat melihat aktivitas tersimpan. Kami tidak mengumpulkan CV, lowongan, transkrip wawancara, atau rekaman suara pengunjung anonim.",
  ms: "Hanya anda boleh melihat aktiviti tersimpan. Kami tidak mengumpul resume, iklan kerja, transkrip temu duga atau rakaman suara pelawat tanpa nama.",
  th: "มีเพียงคุณที่ดูประวัติกิจกรรมที่บันทึกไว้ได้ เราไม่เก็บเรซูเม่ รายละเอียดงาน บทถอดเสียงสัมภาษณ์ หรือเสียงบันทึกของผู้เยี่ยมชมที่ไม่ระบุตัวตน",
  vi: "Chỉ bạn mới xem được hoạt động đã lưu. Chúng tôi không thu thập hồ sơ, tin tuyển dụng, bản ghi phỏng vấn hay bản thu âm của khách ẩn danh.",
  fil: "Ikaw lang ang makakakita ng naka-save na aktibidad. Hindi kami nangongolekta ng resume, job post, transcript, o voice recording ng anonymous na bisita.",
  sv: "Bara du kan se din sparade aktivitet. Vi samlar inte in anonyma cv:n, platsannonser, intervjutranskript eller röstinspelningar.",
  no: "Bare du kan se den lagrede aktiviteten. Vi samler ikke inn anonyme CV-er, stillingsannonser, intervjuutskrifter eller taleopptak.",
  da: "Kun du kan se din gemte aktivitet. Vi indsamler ikke anonyme CV’er, jobopslag, interviewudskrifter eller stemmeoptagelser.",
  fi: "Vain sinä näet tallennetun toimintasi. Emme kerää anonyymejä ansioluetteloita, työpaikkailmoituksia, haastattelulitterointeja tai äänitallenteita.",
  cs: "Uloženou aktivitu vidíte pouze vy. Neshromažďujeme anonymní životopisy, nabídky práce, přepisy pohovorů ani hlasové nahrávky.",
  sk: "Uloženú aktivitu vidíte iba vy. Nezhromažďujeme anonymné životopisy, pracovné ponuky, prepisy pohovorov ani hlasové nahrávky.",
  hu: "A mentett tevékenységet csak te láthatod. Nem gyűjtünk névtelen önéletrajzokat, álláshirdetéseket, interjúleiratokat vagy hangfelvételeket.",
  ro: "Doar tu poți vedea activitatea salvată. Nu colectăm CV-uri, anunțuri, transcrieri sau înregistrări vocale ale vizitatorilor anonimi.",
  el: "Μόνο εσείς βλέπετε την αποθηκευμένη δραστηριότητά σας. Δεν συλλέγουμε ανώνυμα βιογραφικά, αγγελίες, απομαγνητοφωνήσεις ή ηχογραφήσεις.",
  bg: "Само вие виждате запазената си активност. Не събираме анонимни автобиографии, обяви, транскрипции или гласови записи.",
  hr: "Samo vi možete vidjeti spremljenu aktivnost. Ne prikupljamo anonimne životopise, oglase, prijepise razgovora ni glasovne snimke.",
  sr: "Само ви можете видети сачувану активност. Не прикупљамо анонимне биографије, огласе, транскрипте интервјуа или гласовне снимке.",
  sl: "Shranjeno dejavnost lahko vidite samo vi. Ne zbiramo anonimnih življenjepisov, oglasov, prepisov razgovorov ali glasovnih posnetkov.",
  sw: "Ni wewe pekee unayeweza kuona shughuli uliyohifadhi. Hatukusanyi wasifu, maelezo ya kazi, nakala za usaili au rekodi za sauti za wageni wasiojulikana.",
  fa: "فقط شما می‌توانید فعالیت ذخیره‌شده خود را ببینید. ما رزومه، شرح شغل، متن مصاحبه یا ضبط صدای بازدیدکنندگان ناشناس را جمع‌آوری نمی‌کنیم.",
} satisfies Record<LocaleCode, string>;

const freeAccessNotice = {
  en: "All features are free and open source.",
  ja: "すべての機能は無料でオープンソースです。",
  ko: "모든 기능은 무료이며 오픈 소스입니다.",
  "zh-CN": "所有功能均免费开源。",
  "zh-TW": "所有功能皆免費開源。",
  es: "Todas las funciones son gratuitas y de código abierto.",
  fr: "Toutes les fonctionnalités sont gratuites et open source.",
  de: "Alle Funktionen sind kostenlos und Open Source.",
  "pt-BR": "Todos os recursos são gratuitos e de código aberto.",
  it: "Tutte le funzionalità sono gratuite e open source.",
  nl: "Alle functies zijn gratis en open source.",
  pl: "Wszystkie funkcje są bezpłatne i open source.",
  tr: "Tüm özellikler ücretsiz ve açık kaynaklıdır.",
  ru: "Все функции бесплатны и имеют открытый исходный код.",
  uk: "Усі функції безкоштовні та мають відкритий код.",
  ar: "جميع الميزات مجانية ومفتوحة المصدر.",
  he: "כל התכונות חינמיות ובקוד פתוח.",
  hi: "सभी सुविधाएँ निःशुल्क और ओपन सोर्स हैं।",
  bn: "সব ফিচার বিনামূল্যে ও ওপেন সোর্স।",
  ur: "تمام خصوصیات مفت اور اوپن سورس ہیں۔",
  id: "Semua fitur gratis dan bersumber terbuka.",
  ms: "Semua ciri adalah percuma dan sumber terbuka.",
  th: "ทุกฟีเจอร์ใช้งานฟรีและเป็นโอเพนซอร์ส",
  vi: "Mọi tính năng đều miễn phí và mã nguồn mở.",
  fil: "Lahat ng feature ay libre at open source.",
  sv: "Alla funktioner är gratis och har öppen källkod.",
  no: "Alle funksjoner er gratis og har åpen kildekode.",
  da: "Alle funktioner er gratis og open source.",
  fi: "Kaikki ominaisuudet ovat ilmaisia ja avointa lähdekoodia.",
  cs: "Všechny funkce jsou zdarma a s otevřeným zdrojovým kódem.",
  sk: "Všetky funkcie sú bezplatné a s otvoreným zdrojovým kódom.",
  hu: "Minden funkció ingyenes és nyílt forráskódú.",
  ro: "Toate funcțiile sunt gratuite și open source.",
  el: "Όλες οι λειτουργίες είναι δωρεάν και ανοικτού κώδικα.",
  bg: "Всички функции са безплатни и с отворен код.",
  hr: "Sve su značajke besplatne i otvorenog koda.",
  sr: "Све функције су бесплатне и отвореног кода.",
  sl: "Vse funkcije so brezplačne in odprtokodne.",
  sw: "Vipengele vyote ni vya bure na vya chanzo huria.",
  fa: "همه قابلیت‌ها رایگان و متن‌باز هستند.",
} satisfies Record<LocaleCode, string>;

const openSourceLabel = {
  en: "Open source", ja: "オープンソース", ko: "오픈 소스",
  "zh-CN": "开源", "zh-TW": "開源", es: "Código abierto",
  fr: "Open source", de: "Open Source", "pt-BR": "Código aberto",
  it: "Open source", nl: "Open source", pl: "Open source",
  tr: "Açık kaynak", ru: "Открытый код", uk: "Відкритий код",
  ar: "مفتوح المصدر", he: "קוד פתוח", hi: "ओपन सोर्स",
  bn: "ওপেন সোর্স", ur: "اوپن سورس", id: "Sumber terbuka",
  ms: "Sumber terbuka", th: "โอเพนซอร์ส", vi: "Mã nguồn mở",
  fil: "Open source", sv: "Öppen källkod", no: "Åpen kildekode",
  da: "Open source", fi: "Avoin lähdekoodi", cs: "Otevřený zdrojový kód",
  sk: "Otvorený zdrojový kód", hu: "Nyílt forráskód", ro: "Open source",
  el: "Ανοικτός κώδικας", bg: "Отворен код", hr: "Otvoreni kod",
  sr: "Отворени код", sl: "Odprta koda", sw: "Chanzo huria", fa: "متن‌باز",
} satisfies Record<LocaleCode, string>;

export function accountCopyFor(locale: LocaleCode): AccountCopy {
  return {
    ...accountCopy[locale],
    noCharge: freeAccessNotice[locale],
    privacy: privateActivityNotice[locale],
  };
}

export function accountIntroCopyFor(locale: LocaleCode): AccountIntroCopy {
  return {
    title: accountIntroTitle[locale],
    description: requiredLoginNotice[locale],
    accessCta: accountCopy[locale].signIn,
  };
}

export function openSourceLabelFor(locale: LocaleCode) {
  return openSourceLabel[locale];
}
