import type { LocaleCode } from "./i18n";

type AuthCopy = {
  identityNotice: string;
  evidenceNotice: string;
  setupNeeded: string;
  signInFailed: string;
};

const identityNotice = {
  en: "Sign-in shares only your name, email address, and profile image.",
  ja: "ログインで共有されるのは、氏名、メールアドレス、プロフィール画像のみです。",
  ko: "로그인 시 이름, 이메일 주소, 프로필 이미지만 공유됩니다.",
  "zh-CN": "登录只会共享你的姓名、电子邮箱和头像。",
  "zh-TW": "登入只會分享你的姓名、電子郵件與個人頭像。",
  es: "Al iniciar sesión solo se comparten tu nombre, correo y foto de perfil.",
  fr: "La connexion ne partage que votre nom, votre e-mail et votre photo de profil.",
  de: "Bei der Anmeldung werden nur Name, E-Mail-Adresse und Profilbild geteilt.",
  "pt-BR": "O login compartilha apenas seu nome, e-mail e foto de perfil.",
  it: "L’accesso condivide solo nome, e-mail e immagine del profilo.",
  nl: "Bij het inloggen worden alleen je naam, e-mailadres en profielfoto gedeeld.",
  pl: "Logowanie udostępnia tylko imię i nazwisko, e-mail oraz zdjęcie profilowe.",
  tr: "Oturum açma yalnızca adınızı, e-posta adresinizi ve profil resminizi paylaşır.",
  ru: "При входе передаются только имя, адрес электронной почты и фото профиля.",
  uk: "Під час входу передаються лише ім’я, електронна адреса та фото профілю.",
  ar: "لا يشارك تسجيل الدخول سوى اسمك وبريدك الإلكتروني وصورة ملفك الشخصي.",
  he: "הכניסה משתפת רק את השם, כתובת האימייל ותמונת הפרופיל שלך.",
  hi: "साइन-इन केवल आपका नाम, ईमेल पता और प्रोफ़ाइल चित्र साझा करता है।",
  bn: "সাইন-ইন শুধু আপনার নাম, ইমেইল ঠিকানা ও প্রোফাইল ছবি শেয়ার করে।",
  ur: "سائن اِن صرف آپ کا نام، ای میل پتہ اور پروفائل تصویر شیئر کرتا ہے۔",
  id: "Masuk hanya membagikan nama, alamat email, dan foto profil Anda.",
  ms: "Log masuk hanya berkongsi nama, alamat e-mel dan imej profil anda.",
  th: "การเข้าสู่ระบบจะแชร์เฉพาะชื่อ อีเมล และรูปโปรไฟล์ของคุณ",
  vi: "Đăng nhập chỉ chia sẻ tên, địa chỉ email và ảnh hồ sơ của bạn.",
  fil: "Pangalan, email address, at profile image mo lang ang ibinabahagi sa pag-sign in.",
  sv: "Inloggningen delar endast ditt namn, din e-postadress och profilbild.",
  no: "Innlogging deler bare navn, e-postadresse og profilbilde.",
  da: "Login deler kun dit navn, din e-mailadresse og dit profilbillede.",
  fi: "Kirjautuminen jakaa vain nimesi, sähköpostiosoitteesi ja profiilikuvasi.",
  cs: "Přihlášení sdílí pouze vaše jméno, e-mail a profilový obrázek.",
  sk: "Prihlásenie zdieľa iba vaše meno, e-mail a profilový obrázok.",
  hu: "A bejelentkezés csak a nevedet, e-mail-címedet és profilképedet osztja meg.",
  ro: "Autentificarea transmite doar numele, adresa de e-mail și fotografia de profil.",
  el: "Η σύνδεση κοινοποιεί μόνο το όνομα, το email και την εικόνα προφίλ σας.",
  bg: "Входът споделя само името, имейла и профилната ви снимка.",
  hr: "Prijava dijeli samo vaše ime, adresu e-pošte i sliku profila.",
  sr: "Пријава дели само ваше име, адресу е-поште и слику профила.",
  sl: "Prijava deli samo vaše ime, e-poštni naslov in profilno sliko.",
  sw: "Kuingia kunashiriki jina, barua pepe na picha ya wasifu pekee.",
  fa: "ورود فقط نام، نشانی ایمیل و تصویر نمایه شما را به اشتراک می‌گذارد.",
} satisfies Record<LocaleCode, string>;

const evidenceNotice = {
  en: "Career data is never imported automatically. You choose which LinkedIn, GitHub, portfolio, or resume sources become interview evidence.",
  ja: "職歴データが自動で取り込まれることはありません。LinkedIn、GitHub、ポートフォリオ、履歴書のどれを面接の根拠に使うかは自分で選べます。",
  ko: "경력 데이터는 자동으로 가져오지 않습니다. LinkedIn, GitHub, 포트폴리오 또는 이력서 중 면접 근거로 사용할 자료를 직접 선택합니다.",
  "zh-CN": "职业资料不会自动导入。你可以自行选择哪些 LinkedIn、GitHub、作品集或履历内容作为面试依据。",
  "zh-TW": "職涯資料不會自動匯入。你可以自行選擇哪些 LinkedIn、GitHub、作品集或履歷內容作為面試依據。",
  es: "Los datos profesionales nunca se importan automáticamente. Tú eliges qué fuentes de LinkedIn, GitHub, portafolio o CV usar como evidencia.",
  fr: "Les données professionnelles ne sont jamais importées automatiquement. Vous choisissez les sources LinkedIn, GitHub, portfolio ou CV utilisées comme preuves.",
  de: "Karrieredaten werden nie automatisch importiert. Du entscheidest, welche LinkedIn-, GitHub-, Portfolio- oder Lebenslaufquellen als Nachweise dienen.",
  "pt-BR": "Dados profissionais nunca são importados automaticamente. Você escolhe quais fontes do LinkedIn, GitHub, portfólio ou currículo viram evidências.",
  it: "I dati professionali non vengono mai importati automaticamente. Scegli tu quali fonti LinkedIn, GitHub, portfolio o CV usare come prove.",
  nl: "Loopbaangegevens worden nooit automatisch geïmporteerd. Jij kiest welke LinkedIn-, GitHub-, portfolio- of cv-bronnen als bewijs dienen.",
  pl: "Dane zawodowe nigdy nie są importowane automatycznie. To Ty wybierasz źródła LinkedIn, GitHub, portfolio lub CV używane jako dowody.",
  tr: "Kariyer verileri otomatik olarak içe aktarılmaz. Hangi LinkedIn, GitHub, portföy veya özgeçmiş kaynaklarının kanıt olacağını siz seçersiniz.",
  ru: "Карьерные данные не импортируются автоматически. Вы сами выбираете, какие материалы LinkedIn, GitHub, портфолио или резюме использовать как доказательства.",
  uk: "Кар’єрні дані не імпортуються автоматично. Ви самі обираєте матеріали LinkedIn, GitHub, портфоліо чи резюме для доказів.",
  ar: "لا تُستورد بياناتك المهنية تلقائياً. أنت تختار مصادر LinkedIn أو GitHub أو ملف الأعمال أو السيرة الذاتية التي تصبح أدلة للمقابلة.",
  he: "נתוני קריירה לעולם אינם מיובאים אוטומטית. אתם בוחרים אילו מקורות LinkedIn, GitHub, תיק עבודות או קורות חיים ישמשו כראיות.",
  hi: "करियर डेटा कभी अपने-आप आयात नहीं होता। आप चुनते हैं कि कौन से LinkedIn, GitHub, पोर्टफोलियो या रिज़्यूमे स्रोत इंटरव्यू प्रमाण बनें।",
  bn: "ক্যারিয়ার তথ্য কখনও স্বয়ংক্রিয়ভাবে আমদানি হয় না। কোন LinkedIn, GitHub, পোর্টফোলিও বা জীবনবৃত্তান্ত সাক্ষাৎকারের প্রমাণ হবে তা আপনি বেছে নেন।",
  ur: "کیریئر ڈیٹا خودکار طور پر درآمد نہیں ہوتا۔ آپ منتخب کرتے ہیں کہ کون سے LinkedIn، GitHub، پورٹ فولیو یا ریزیومے ذرائع انٹرویو ثبوت بنیں۔",
  id: "Data karier tidak pernah diimpor otomatis. Anda memilih sumber LinkedIn, GitHub, portofolio, atau CV yang menjadi bukti wawancara.",
  ms: "Data kerjaya tidak pernah diimport secara automatik. Anda memilih sumber LinkedIn, GitHub, portfolio atau resume yang menjadi bukti temu duga.",
  th: "ระบบจะไม่นำเข้าข้อมูลอาชีพโดยอัตโนมัติ คุณเลือกเองว่าจะใช้ LinkedIn, GitHub, พอร์ตโฟลิโอ หรือเรซูเม่ใดเป็นหลักฐานการสัมภาษณ์",
  vi: "Dữ liệu nghề nghiệp không bao giờ được tự động nhập. Bạn chọn nguồn LinkedIn, GitHub, hồ sơ năng lực hoặc CV dùng làm bằng chứng phỏng vấn.",
  fil: "Hindi awtomatikong ini-import ang career data. Ikaw ang pipili kung aling LinkedIn, GitHub, portfolio, o resume source ang gagamiting ebidensya.",
  sv: "Karriärdata importeras aldrig automatiskt. Du väljer vilka LinkedIn-, GitHub-, portfölj- eller cv-källor som blir intervjubevis.",
  no: "Karrieredata importeres aldri automatisk. Du velger hvilke LinkedIn-, GitHub-, portefølje- eller CV-kilder som blir intervjubevis.",
  da: "Karrieredata importeres aldrig automatisk. Du vælger, hvilke LinkedIn-, GitHub-, portfolio- eller CV-kilder der bruges som dokumentation.",
  fi: "Uratietoja ei koskaan tuoda automaattisesti. Valitset itse, mitkä LinkedIn-, GitHub-, portfolio- tai ansioluettelolähteet toimivat näyttönä.",
  cs: "Kariérní data se nikdy neimportují automaticky. Sami vybíráte zdroje LinkedIn, GitHub, portfolio nebo CV použité jako důkazy.",
  sk: "Kariérne údaje sa nikdy neimportujú automaticky. Sami si vyberáte zdroje LinkedIn, GitHub, portfólio alebo CV použité ako dôkazy.",
  hu: "A karrieradatokat soha nem importáljuk automatikusan. Te választod ki, mely LinkedIn-, GitHub-, portfólió- vagy önéletrajzforrás legyen bizonyíték.",
  ro: "Datele profesionale nu sunt importate automat. Tu alegi sursele LinkedIn, GitHub, portofoliu sau CV folosite ca dovezi.",
  el: "Τα επαγγελματικά δεδομένα δεν εισάγονται ποτέ αυτόματα. Εσείς επιλέγετε ποιες πηγές LinkedIn, GitHub, portfolio ή βιογραφικού γίνονται αποδεικτικά.",
  bg: "Кариерните данни никога не се импортират автоматично. Вие избирате кои източници от LinkedIn, GitHub, портфолио или автобиография да служат като доказателства.",
  hr: "Podaci o karijeri nikad se ne uvoze automatski. Vi birate izvore LinkedIn, GitHub, portfelja ili životopisa koji služe kao dokaz.",
  sr: "Подаци о каријери се никада не увозе аутоматски. Ви бирате LinkedIn, GitHub, портфолио или биографију који служе као доказ.",
  sl: "Karierni podatki se nikoli ne uvozijo samodejno. Sami izberete vire LinkedIn, GitHub, portfelj ali življenjepis, ki bodo dokazila.",
  sw: "Data ya kazi haiingizwi kiotomatiki. Unachagua vyanzo vya LinkedIn, GitHub, jalada au wasifu vitakavyotumika kama ushahidi.",
  fa: "داده‌های شغلی هرگز خودکار وارد نمی‌شوند. شما انتخاب می‌کنید کدام منابع LinkedIn،‏ GitHub، نمونه‌کار یا رزومه به‌عنوان مدرک مصاحبه استفاده شوند.",
} satisfies Record<LocaleCode, string>;

const setupNeeded = {
  en: "This sign-in provider needs one-time administrator setup before it can be used.",
  ja: "このログイン方法を使うには、管理者による初回設定が必要です。",
  ko: "이 로그인 방법을 사용하려면 관리자의 최초 설정이 필요합니다.",
  "zh-CN": "此登录方式需要管理员先完成一次性设置。",
  "zh-TW": "此登入方式需要管理員先完成一次性設定。",
  es: "Este proveedor de acceso necesita una configuración inicial del administrador.",
  fr: "Ce fournisseur de connexion nécessite une configuration initiale par l’administrateur.",
  de: "Dieser Anmeldeanbieter muss einmalig durch die Administration eingerichtet werden.",
  "pt-BR": "Este provedor de login precisa de uma configuração inicial do administrador.",
  it: "Questo provider di accesso richiede una configurazione iniziale dell’amministratore.",
  nl: "Deze aanmeldprovider moet eenmalig door de beheerder worden ingesteld.",
  pl: "Ten dostawca logowania wymaga jednorazowej konfiguracji przez administratora.",
  tr: "Bu oturum açma sağlayıcısı için yöneticinin bir defalık kurulum yapması gerekir.",
  ru: "Для этого способа входа администратору нужно выполнить первоначальную настройку.",
  uk: "Для цього способу входу адміністратор має виконати початкове налаштування.",
  ar: "يحتاج موفر تسجيل الدخول هذا إلى إعداد أولي من المسؤول.",
  he: "ספק הכניסה הזה דורש הגדרה חד־פעמית של מנהל המערכת.",
  hi: "इस साइन-इन प्रदाता को उपयोग से पहले एडमिन की एक बार की सेटअप की आवश्यकता है।",
  bn: "এই সাইন-ইন প্রদানকারী ব্যবহার করতে প্রশাসকের একবারের সেটআপ দরকার।",
  ur: "اس سائن اِن فراہم کنندہ کو استعمال سے پہلے منتظم کی ایک بار کی ترتیب درکار ہے۔",
  id: "Penyedia masuk ini memerlukan penyiapan satu kali oleh administrator.",
  ms: "Penyedia log masuk ini memerlukan persediaan sekali oleh pentadbir.",
  th: "ผู้ดูแลระบบต้องตั้งค่าผู้ให้บริการเข้าสู่ระบบนี้หนึ่งครั้งก่อนใช้งาน",
  vi: "Nhà cung cấp đăng nhập này cần quản trị viên thiết lập một lần trước khi sử dụng.",
  fil: "Kailangan muna ng isang beses na administrator setup ang sign-in provider na ito.",
  sv: "Den här inloggningsleverantören måste först konfigureras av en administratör.",
  no: "Denne innloggingsleverandøren må først konfigureres av en administrator.",
  da: "Denne loginudbyder skal først konfigureres én gang af en administrator.",
  fi: "Järjestelmänvalvojan on määritettävä tämä kirjautumispalvelu kerran ennen käyttöä.",
  cs: "Tento poskytovatel přihlášení vyžaduje jednorázové nastavení správcem.",
  sk: "Tento poskytovateľ prihlásenia vyžaduje jednorazové nastavenie správcom.",
  hu: "Ezt a bejelentkezési szolgáltatót a rendszergazdának egyszer be kell állítania.",
  ro: "Acest furnizor de autentificare necesită o configurare inițială de către administrator.",
  el: "Αυτός ο πάροχος σύνδεσης χρειάζεται μία αρχική ρύθμιση από διαχειριστή.",
  bg: "Този доставчик за вход изисква еднократна настройка от администратор.",
  hr: "Ovaj pružatelj prijave zahtijeva jednokratno postavljanje administratora.",
  sr: "Овај добављач пријаве захтева једнократно подешавање администратора.",
  sl: "Ta ponudnik prijave zahteva enkratno nastavitev skrbnika.",
  sw: "Mtoa huduma huyu wa kuingia anahitaji usanidi wa mara moja na msimamizi.",
  fa: "این ارائه‌دهنده ورود پیش از استفاده به تنظیم یک‌باره مدیر نیاز دارد.",
} satisfies Record<LocaleCode, string>;

const signInFailed = {
  en: "Sign-in could not be completed. Please try again.",
  ja: "ログインを完了できませんでした。もう一度お試しください。",
  ko: "로그인을 완료하지 못했습니다. 다시 시도해 주세요.",
  "zh-CN": "无法完成登录，请再试一次。",
  "zh-TW": "無法完成登入，請再試一次。",
  es: "No se pudo completar el acceso. Inténtalo de nuevo.",
  fr: "La connexion n’a pas pu être effectuée. Veuillez réessayer.",
  de: "Die Anmeldung konnte nicht abgeschlossen werden. Bitte versuche es erneut.",
  "pt-BR": "Não foi possível concluir o login. Tente novamente.",
  it: "Non è stato possibile completare l’accesso. Riprova.",
  nl: "Het inloggen kon niet worden voltooid. Probeer het opnieuw.",
  pl: "Nie udało się dokończyć logowania. Spróbuj ponownie.",
  tr: "Oturum açma tamamlanamadı. Lütfen tekrar deneyin.",
  ru: "Не удалось завершить вход. Попробуйте ещё раз.",
  uk: "Не вдалося завершити вхід. Спробуйте ще раз.",
  ar: "تعذر إكمال تسجيل الدخول. يُرجى المحاولة مجدداً.",
  he: "לא ניתן היה להשלים את הכניסה. נסו שוב.",
  hi: "साइन-इन पूरा नहीं हो सका। कृपया फिर कोशिश करें।",
  bn: "সাইন-ইন সম্পন্ন করা যায়নি। আবার চেষ্টা করুন।",
  ur: "سائن اِن مکمل نہیں ہو سکا۔ براہ کرم دوبارہ کوشش کریں۔",
  id: "Proses masuk tidak dapat diselesaikan. Silakan coba lagi.",
  ms: "Log masuk tidak dapat diselesaikan. Sila cuba lagi.",
  th: "ไม่สามารถเข้าสู่ระบบให้เสร็จสมบูรณ์ได้ โปรดลองอีกครั้ง",
  vi: "Không thể hoàn tất đăng nhập. Vui lòng thử lại.",
  fil: "Hindi makumpleto ang pag-sign in. Pakisubukan muli.",
  sv: "Inloggningen kunde inte slutföras. Försök igen.",
  no: "Innloggingen kunne ikke fullføres. Prøv igjen.",
  da: "Login kunne ikke gennemføres. Prøv igen.",
  fi: "Kirjautumista ei voitu suorittaa. Yritä uudelleen.",
  cs: "Přihlášení se nepodařilo dokončit. Zkuste to znovu.",
  sk: "Prihlásenie sa nepodarilo dokončiť. Skúste to znova.",
  hu: "A bejelentkezést nem sikerült befejezni. Próbáld újra.",
  ro: "Autentificarea nu a putut fi finalizată. Încearcă din nou.",
  el: "Η σύνδεση δεν ολοκληρώθηκε. Δοκιμάστε ξανά.",
  bg: "Входът не можа да бъде завършен. Опитайте отново.",
  hr: "Prijava nije dovršena. Pokušajte ponovno.",
  sr: "Пријава није завршена. Покушајте поново.",
  sl: "Prijave ni bilo mogoče dokončati. Poskusite znova.",
  sw: "Kuingia hakukukamilika. Tafadhali jaribu tena.",
  fa: "ورود کامل نشد. لطفاً دوباره تلاش کنید.",
} satisfies Record<LocaleCode, string>;

export function authCopyFor(locale: LocaleCode): AuthCopy {
  return {
    identityNotice: identityNotice[locale],
    evidenceNotice: evidenceNotice[locale],
    setupNeeded: setupNeeded[locale],
    signInFailed: signInFailed[locale],
  };
}
