import type { LocaleCode } from "./i18n";

export type FaqItem = {
  question: string;
  answer: string;
};

export type FaqCopy = {
  eyebrow: string;
  title: string;
  intro: string;
  items: FaqItem[];
};

const faqCopy = {
  en: {
    eyebrow: "Frequently asked questions",
    title: "Clear answers before you build your proof pack.",
    intro: "What CareerStoryMap does today, what stays under your control, and where the current limits are.",
    items: [
      { question: "Will CareerStoryMap invent achievements for me?", answer: "No. Every suggestion must trace back to evidence you provide. Missing proof stays visible as a real gap." },
      { question: "What do I need to get started?", answer: "One real resume and one real job description are enough. Adding your interview date or application stage makes the preparation plan more useful." },
      { question: "Is the match result an ATS score?", answer: "No. It maps each important requirement to strong, partial, or missing evidence instead of claiming one universal ATS score." },
      { question: "Do I need an account?", answer: "No. You can use the core workspace without signing in. Sign-in remains optional in the current open-source version." },
      { question: "Which documents can I import, and are they private?", answer: "Common PDF, DOCX, PPTX, XLSX, text, and OpenDocument files are parsed in your browser by default. Scans or legacy files may need OCR or conversion first." },
      { question: "Does CareerStoryMap apply to jobs automatically?", answer: "No. The public open-source version never submits an application for you. You review and control every action." },
      { question: "Can I use it worldwide and in my language?", answer: "The interface supports 40 languages and worldwide filters. Live job and market coverage depends on approved sources available for each region." },
    ],
  },
  ja: {
    eyebrow: "よくある質問",
    title: "プルーフパックを作る前に、疑問を解消しましょう。",
    intro: "CareerStoryMap が現在できること、利用者が管理できること、現在の制限を明確に説明します。",
    items: [
      { question: "CareerStoryMap は実績を作り上げますか？", answer: "いいえ。すべての提案は、あなたが提供した根拠に結び付きます。根拠がない部分は実際のギャップとして表示されます。" },
      { question: "始めるには何が必要ですか？", answer: "実際の履歴書と求人票が1つずつあれば始められます。面接日や応募段階を加えると、準備計画がさらに役立ちます。" },
      { question: "マッチ結果は ATS スコアですか？", answer: "いいえ。単一の万能スコアではなく、重要な要件ごとに根拠が強い、一部ある、ないを示します。" },
      { question: "アカウントは必要ですか？", answer: "いいえ。サインインせずに主要ワークスペースを利用できます。現在のオープンソース版ではサインインは任意です。" },
      { question: "どの書類を読み込めますか？プライバシーは守られますか？", answer: "一般的な PDF、DOCX、PPTX、XLSX、テキスト、OpenDocument は通常ブラウザ内で解析されます。スキャンや古い形式は OCR または変換が必要な場合があります。" },
      { question: "求人へ自動応募しますか？", answer: "いいえ。公開オープンソース版が代理で応募を送信することはありません。すべての操作をあなたが確認して管理します。" },
      { question: "世界中で自分の言語を使えますか？", answer: "画面は40言語と世界各地の絞り込みに対応しています。求人と市場データの範囲は、地域ごとに利用可能な承認済みデータ源によります。" },
    ],
  },
  ko: {
    eyebrow: "자주 묻는 질문",
    title: "증거 팩을 만들기 전에 궁금증을 해결하세요.",
    intro: "CareerStoryMap이 현재 제공하는 기능, 사용자가 통제하는 부분, 현재의 한계를 명확히 설명합니다.",
    items: [
      { question: "CareerStoryMap이 제 성과를 지어내나요?", answer: "아니요. 모든 제안은 사용자가 제공한 근거로 이어져야 합니다. 근거가 없으면 실제 공백으로 표시됩니다." },
      { question: "시작하려면 무엇이 필요한가요?", answer: "실제 이력서 한 부와 실제 JD 한 개면 충분합니다. 면접일이나 지원 단계를 추가하면 준비 계획이 더 유용해집니다." },
      { question: "매칭 결과가 ATS 점수인가요?", answer: "아니요. 하나의 보편적 점수를 주장하지 않고, 중요 요건별로 근거가 강함·부분적·없음을 보여 줍니다." },
      { question: "계정이 필요한가요?", answer: "아니요. 로그인하지 않고 핵심 워크스페이스를 사용할 수 있습니다. 현재 오픈 소스 버전에서 로그인은 선택 사항입니다." },
      { question: "어떤 문서를 가져올 수 있고 비공개인가요?", answer: "일반적인 PDF, DOCX, PPTX, XLSX, 텍스트, OpenDocument 파일은 기본적으로 브라우저에서 처리됩니다. 스캔본이나 구형 파일은 OCR 또는 변환이 필요할 수 있습니다." },
      { question: "채용 공고에 자동 지원하나요?", answer: "아니요. 공개 오픈 소스 버전은 지원서를 대신 제출하지 않습니다. 모든 작업은 사용자가 검토하고 통제합니다." },
      { question: "전 세계에서 제 언어로 사용할 수 있나요?", answer: "인터페이스는 40개 언어와 전 세계 필터를 지원합니다. 실시간 채용 및 시장 범위는 지역별 승인 데이터 소스에 따라 달라집니다." },
    ],
  },
  "zh-CN": {
    eyebrow: "常见问题",
    title: "建立面试证据包之前，先把问题弄清楚。",
    intro: "说明 CareerStoryMap 目前能做什么、哪些操作由你控制，以及现阶段的限制。",
    items: [
      { question: "CareerStoryMap 会替我编造成就吗？", answer: "不会。每项建议都必须能追溯到你提供的证据；缺少证据的部分会保留为真实缺口。" },
      { question: "开始使用需要准备什么？", answer: "一份真实简历和一份真实 JD 就够了。加入面试日期或申请阶段，会让准备计划更有帮助。" },
      { question: "匹配结果就是 ATS 分数吗？", answer: "不是。它不会声称存在通用 ATS 分数，而是逐项显示重要要求的证据是充分、部分还是缺失。" },
      { question: "一定要注册账户吗？", answer: "不需要。不登录也能使用核心工作区；在目前的开源版本中，登录是可选的。" },
      { question: "可以导入哪些文件？资料是否私密？", answer: "常见 PDF、DOCX、PPTX、XLSX、文本和 OpenDocument 文件默认在浏览器中解析。扫描件或旧格式可能需要先做 OCR 或转换。" },
      { question: "CareerStoryMap 会自动投递职位吗？", answer: "不会。公开开源版本不会替你提交申请；每一步都由你审核和控制。" },
      { question: "可以在全球使用并切换语言吗？", answer: "界面支持40种语言和全球地区筛选。实时职位与市场覆盖取决于各地区可用的核准数据源。" },
    ],
  },
  "zh-TW": {
    eyebrow: "常見問題",
    title: "建立面試證據包之前，先把疑問說清楚。",
    intro: "說明 CareerStoryMap 現在能做什麼、哪些操作由你掌控，以及目前的限制。",
    items: [
      { question: "CareerStoryMap 會替我捏造經歷或成就嗎？", answer: "不會。每一項建議都必須能追溯到你提供的證據；缺少證據的部分會保留為真實缺口。" },
      { question: "開始使用需要準備什麼？", answer: "一份真實履歷與一份真實 JD 就足夠。加入面試日期或申請階段，會讓準備計畫更實用。" },
      { question: "匹配結果就是 ATS 分數嗎？", answer: "不是。它不會宣稱存在通用 ATS 分數，而是逐項顯示重要要求的證據是充分、部分或缺少。" },
      { question: "一定要註冊帳號嗎？", answer: "不用。不登入也能使用核心工作區；在目前的開源版本中，登入是選擇性的。" },
      { question: "可以匯入哪些檔案？資料是否私密？", answer: "常見 PDF、DOCX、PPTX、XLSX、文字與 OpenDocument 檔案預設在瀏覽器內解析。掃描檔或舊格式可能要先做 OCR 或轉換。" },
      { question: "CareerStoryMap 會自動投遞職缺嗎？", answer: "不會。公開開源版本不會替你送出申請；每一步都由你審核與控制。" },
      { question: "可以在全球使用並切換語言嗎？", answer: "介面支援40種語言與全球地區篩選。即時職缺及市場涵蓋範圍取決於各地可用的核准資料源。" },
    ],
  },
  es: {
    eyebrow: "Preguntas frecuentes",
    title: "Respuestas claras antes de crear tu paquete de evidencias.",
    intro: "Qué hace CareerStoryMap hoy, qué controlas tú y cuáles son los límites actuales.",
    items: [
      { question: "¿CareerStoryMap inventará logros por mí?", answer: "No. Cada sugerencia debe vincularse con pruebas que tú aportes. Lo que no tenga respaldo seguirá visible como una brecha real." },
      { question: "¿Qué necesito para empezar?", answer: "Basta con un currículum real y una oferta real. Añadir la fecha de entrevista o la etapa de candidatura mejora el plan de preparación." },
      { question: "¿El resultado es una puntuación ATS?", answer: "No. En lugar de prometer una puntuación ATS universal, muestra si cada requisito importante tiene pruebas sólidas, parciales o inexistentes." },
      { question: "¿Necesito una cuenta?", answer: "No. Puedes usar el espacio principal sin iniciar sesión. El acceso con cuenta es opcional en la versión abierta actual." },
      { question: "¿Qué documentos puedo importar y son privados?", answer: "Los archivos PDF, DOCX, PPTX, XLSX, texto y OpenDocument habituales se procesan por defecto en tu navegador. Los escaneos o formatos antiguos pueden necesitar OCR o conversión." },
      { question: "¿CareerStoryMap solicita empleos automáticamente?", answer: "No. La versión pública y abierta nunca envía una candidatura por ti. Tú revisas y controlas cada acción." },
      { question: "¿Puedo usarlo en todo el mundo y en mi idioma?", answer: "La interfaz admite 40 idiomas y filtros globales. La cobertura de empleos y mercado depende de las fuentes aprobadas disponibles en cada región." },
    ],
  },
  fr: {
    eyebrow: "Questions fréquentes",
    title: "Des réponses claires avant de créer votre dossier de preuves.",
    intro: "Ce que CareerStoryMap fait aujourd’hui, ce que vous contrôlez et les limites actuelles.",
    items: [
      { question: "CareerStoryMap invente-t-il des réalisations ?", answer: "Non. Chaque suggestion doit renvoyer aux preuves que vous fournissez. Une preuve absente reste visible comme une véritable lacune." },
      { question: "De quoi ai-je besoin pour commencer ?", answer: "Un vrai CV et une vraie offre suffisent. La date d’entretien ou l’étape de candidature rend le plan de préparation plus utile." },
      { question: "Le résultat correspond-il à un score ATS ?", answer: "Non. Il indique, exigence par exigence, si la preuve est forte, partielle ou absente au lieu de prétendre fournir un score ATS universel." },
      { question: "Ai-je besoin d’un compte ?", answer: "Non. L’espace principal fonctionne sans connexion. La connexion reste facultative dans la version open source actuelle." },
      { question: "Quels documents puis-je importer et sont-ils privés ?", answer: "Les fichiers PDF, DOCX, PPTX, XLSX, texte et OpenDocument courants sont traités par défaut dans votre navigateur. Les scans ou anciens formats peuvent nécessiter un OCR ou une conversion." },
      { question: "CareerStoryMap postule-t-il automatiquement ?", answer: "Non. La version publique open source n’envoie jamais de candidature à votre place. Vous contrôlez chaque action." },
      { question: "Puis-je l’utiliser partout et dans ma langue ?", answer: "L’interface prend en charge 40 langues et des filtres mondiaux. La couverture en direct dépend des sources approuvées disponibles dans chaque région." },
    ],
  },
  de: {
    eyebrow: "Häufige Fragen",
    title: "Klare Antworten, bevor du dein Nachweispaket erstellst.",
    intro: "Was CareerStoryMap heute kann, was du kontrollierst und wo die aktuellen Grenzen liegen.",
    items: [
      { question: "Erfindet CareerStoryMap Erfolge für mich?", answer: "Nein. Jeder Vorschlag muss auf deinen Nachweisen beruhen. Fehlende Belege bleiben als echte Lücke sichtbar." },
      { question: "Was brauche ich zum Start?", answer: "Ein echter Lebenslauf und eine echte Stellenbeschreibung reichen aus. Interviewdatum oder Bewerbungsphase verbessern den Vorbereitungsplan." },
      { question: "Ist das Ergebnis ein ATS-Score?", answer: "Nein. Statt eines angeblich universellen ATS-Scores zeigt es pro wichtiger Anforderung starke, teilweise oder fehlende Nachweise." },
      { question: "Brauche ich ein Konto?", answer: "Nein. Der Kernarbeitsbereich funktioniert ohne Anmeldung. Die Anmeldung ist in der aktuellen Open-Source-Version optional." },
      { question: "Welche Dokumente kann ich importieren und sind sie privat?", answer: "Übliche PDF-, DOCX-, PPTX-, XLSX-, Text- und OpenDocument-Dateien werden standardmäßig im Browser verarbeitet. Scans oder alte Formate benötigen eventuell OCR oder Konvertierung." },
      { question: "Bewirbt sich CareerStoryMap automatisch?", answer: "Nein. Die öffentliche Open-Source-Version sendet niemals Bewerbungen für dich ab. Du prüfst und steuerst jede Aktion." },
      { question: "Kann ich es weltweit und in meiner Sprache nutzen?", answer: "Die Oberfläche unterstützt 40 Sprachen und weltweite Filter. Live-Stellen und Marktabdeckung hängen von regional verfügbaren, genehmigten Quellen ab." },
    ],
  },
  "pt-BR": {
    eyebrow: "Perguntas frequentes",
    title: "Respostas claras antes de criar seu pacote de evidências.",
    intro: "O que o CareerStoryMap faz hoje, o que fica sob seu controle e quais são os limites atuais.",
    items: [
      { question: "O CareerStoryMap inventa conquistas para mim?", answer: "Não. Toda sugestão precisa apontar para evidências fornecidas por você. O que não tiver comprovação continua visível como lacuna real." },
      { question: "Do que preciso para começar?", answer: "Um currículo real e uma descrição de vaga real são suficientes. A data da entrevista ou a etapa da candidatura melhora o plano de preparação." },
      { question: "O resultado é uma pontuação de ATS?", answer: "Não. Em vez de prometer uma pontuação universal, ele mostra evidência forte, parcial ou ausente para cada requisito importante." },
      { question: "Preciso de uma conta?", answer: "Não. O espaço principal funciona sem login. Entrar continua opcional na versão de código aberto atual." },
      { question: "Quais documentos posso importar e eles são privados?", answer: "PDF, DOCX, PPTX, XLSX, texto e OpenDocument comuns são processados no navegador por padrão. Digitalizações ou formatos antigos podem exigir OCR ou conversão." },
      { question: "O CareerStoryMap se candidata automaticamente?", answer: "Não. A versão pública de código aberto nunca envia uma candidatura por você. Você revisa e controla cada ação." },
      { question: "Posso usar no mundo todo e no meu idioma?", answer: "A interface oferece 40 idiomas e filtros globais. A cobertura ao vivo depende das fontes aprovadas disponíveis em cada região." },
    ],
  },
  it: {
    eyebrow: "Domande frequenti",
    title: "Risposte chiare prima di creare il tuo pacchetto di prove.",
    intro: "Cosa fa oggi CareerStoryMap, cosa controlli tu e quali sono i limiti attuali.",
    items: [
      { question: "CareerStoryMap inventa risultati per me?", answer: "No. Ogni suggerimento deve risalire alle prove che fornisci. Ciò che non è dimostrato resta visibile come una lacuna reale." },
      { question: "Di cosa ho bisogno per iniziare?", answer: "Bastano un curriculum reale e una descrizione di lavoro reale. Data del colloquio o fase della candidatura migliorano il piano." },
      { question: "Il risultato è un punteggio ATS?", answer: "No. Mostra prove forti, parziali o mancanti per ogni requisito importante, senza promettere un punteggio ATS universale." },
      { question: "Serve un account?", answer: "No. Puoi usare lo spazio principale senza accedere. L’accesso è facoltativo nell’attuale versione open source." },
      { question: "Quali documenti posso importare e sono privati?", answer: "I comuni PDF, DOCX, PPTX, XLSX, file di testo e OpenDocument vengono elaborati nel browser. Scansioni o vecchi formati possono richiedere OCR o conversione." },
      { question: "CareerStoryMap invia candidature automaticamente?", answer: "No. La versione pubblica open source non invia mai candidature al posto tuo. Ogni azione resta sotto il tuo controllo." },
      { question: "Posso usarlo ovunque e nella mia lingua?", answer: "L’interfaccia supporta 40 lingue e filtri globali. La copertura in tempo reale dipende dalle fonti approvate disponibili per regione." },
    ],
  },
  nl: {
    eyebrow: "Veelgestelde vragen",
    title: "Duidelijke antwoorden voordat je je bewijspakket maakt.",
    intro: "Wat CareerStoryMap nu doet, wat jij beheert en waar de huidige grenzen liggen.",
    items: [
      { question: "Verzint CareerStoryMap prestaties voor mij?", answer: "Nee. Elke suggestie moet teruggaan op bewijs dat jij aanlevert. Ontbrekend bewijs blijft zichtbaar als een echte leemte." },
      { question: "Wat heb ik nodig om te beginnen?", answer: "Eén echt cv en één echte vacaturetekst zijn genoeg. Een interviewdatum of sollicitatiefase maakt het plan nuttiger." },
      { question: "Is het resultaat een ATS-score?", answer: "Nee. Het toont per belangrijke eis sterk, gedeeltelijk of ontbrekend bewijs, in plaats van één universele ATS-score te beloven." },
      { question: "Heb ik een account nodig?", answer: "Nee. De kernwerkruimte werkt zonder inloggen. Inloggen is optioneel in de huidige open-sourceversie." },
      { question: "Welke documenten kan ik importeren en zijn ze privé?", answer: "Gangbare PDF-, DOCX-, PPTX-, XLSX-, tekst- en OpenDocument-bestanden worden standaard in je browser verwerkt. Scans of oude formaten kunnen OCR of conversie vereisen." },
      { question: "Solliciteert CareerStoryMap automatisch?", answer: "Nee. De openbare open-sourceversie verstuurt nooit een sollicitatie voor je. Jij controleert elke actie." },
      { question: "Kan ik het wereldwijd en in mijn taal gebruiken?", answer: "De interface ondersteunt 40 talen en wereldwijde filters. Live dekking hangt af van goedgekeurde bronnen per regio." },
    ],
  },
  pl: {
    eyebrow: "Najczęstsze pytania",
    title: "Jasne odpowiedzi przed utworzeniem pakietu dowodów.",
    intro: "Co CareerStoryMap robi dziś, co pozostaje pod Twoją kontrolą i jakie są obecne ograniczenia.",
    items: [
      { question: "Czy CareerStoryMap wymyśla moje osiągnięcia?", answer: "Nie. Każda sugestia musi prowadzić do dostarczonych przez Ciebie dowodów. Brak dowodu pozostaje widoczny jako prawdziwa luka." },
      { question: "Czego potrzebuję na początek?", answer: "Wystarczy prawdziwe CV i prawdziwy opis stanowiska. Data rozmowy lub etap rekrutacji ulepsza plan przygotowań." },
      { question: "Czy wynik dopasowania to wynik ATS?", answer: "Nie. Pokazuje mocne, częściowe lub brakujące dowody dla każdego wymagania zamiast obiecywać jeden uniwersalny wynik ATS." },
      { question: "Czy potrzebuję konta?", answer: "Nie. Z głównej przestrzeni można korzystać bez logowania. Logowanie jest opcjonalne w obecnej wersji open source." },
      { question: "Jakie dokumenty mogę importować i czy są prywatne?", answer: "Typowe pliki PDF, DOCX, PPTX, XLSX, tekstowe i OpenDocument są domyślnie przetwarzane w przeglądarce. Skany lub stare formaty mogą wymagać OCR albo konwersji." },
      { question: "Czy CareerStoryMap automatycznie wysyła aplikacje?", answer: "Nie. Publiczna wersja open source nigdy nie wysyła aplikacji za Ciebie. Każde działanie kontrolujesz samodzielnie." },
      { question: "Czy mogę używać go globalnie i w swoim języku?", answer: "Interfejs obsługuje 40 języków i filtry światowe. Dostępność danych na żywo zależy od zatwierdzonych źródeł w regionie." },
    ],
  },
  tr: {
    eyebrow: "Sık sorulan sorular",
    title: "Kanıt paketini oluşturmadan önce net yanıtlar.",
    intro: "CareerStoryMap’in bugün yaptıkları, sizin kontrolünüzde kalanlar ve mevcut sınırlar.",
    items: [
      { question: "CareerStoryMap benim için başarı uydurur mu?", answer: "Hayır. Her öneri sağladığınız kanıta dayanmalıdır. Desteklenmeyen noktalar gerçek boşluk olarak görünür kalır." },
      { question: "Başlamak için neye ihtiyacım var?", answer: "Gerçek bir özgeçmiş ve gerçek bir iş ilanı yeterlidir. Mülakat tarihi veya başvuru aşaması hazırlık planını geliştirir." },
      { question: "Eşleşme sonucu bir ATS puanı mı?", answer: "Hayır. Evrensel bir ATS puanı iddia etmek yerine her önemli gereklilik için güçlü, kısmi veya eksik kanıtı gösterir." },
      { question: "Hesap gerekli mi?", answer: "Hayır. Ana çalışma alanını giriş yapmadan kullanabilirsiniz. Mevcut açık kaynak sürümünde giriş isteğe bağlıdır." },
      { question: "Hangi belgeleri içe aktarabilirim ve bunlar gizli mi?", answer: "Yaygın PDF, DOCX, PPTX, XLSX, metin ve OpenDocument dosyaları varsayılan olarak tarayıcıda işlenir. Taramalar veya eski biçimler OCR ya da dönüşüm gerektirebilir." },
      { question: "CareerStoryMap otomatik başvuru yapar mı?", answer: "Hayır. Herkese açık sürüm sizin yerinize başvuru göndermez. Her işlemi siz inceler ve kontrol edersiniz." },
      { question: "Dünya çapında ve kendi dilimde kullanabilir miyim?", answer: "Arayüz 40 dili ve küresel filtreleri destekler. Canlı kapsam, her bölgedeki onaylı kaynaklara bağlıdır." },
    ],
  },
  ru: {
    eyebrow: "Частые вопросы",
    title: "Чёткие ответы до создания пакета доказательств.",
    intro: "Что CareerStoryMap умеет сейчас, что контролируете вы и каковы текущие ограничения.",
    items: [
      { question: "CareerStoryMap будет придумывать мои достижения?", answer: "Нет. Каждое предложение должно опираться на предоставленные вами доказательства. Неподтверждённое остаётся видимым как реальный пробел." },
      { question: "Что нужно для начала?", answer: "Достаточно настоящего резюме и описания вакансии. Дата интервью или этап заявки сделают план полезнее." },
      { question: "Результат соответствия — это балл ATS?", answer: "Нет. Вместо универсального балла система показывает сильные, частичные или отсутствующие доказательства по каждому важному требованию." },
      { question: "Нужна ли учётная запись?", answer: "Нет. Основное рабочее пространство доступно без входа. В текущей открытой версии вход необязателен." },
      { question: "Какие документы можно импортировать и приватны ли они?", answer: "Обычные PDF, DOCX, PPTX, XLSX, текстовые и OpenDocument-файлы по умолчанию обрабатываются в браузере. Для сканов и старых форматов может понадобиться OCR или конвертация." },
      { question: "CareerStoryMap подаёт заявки автоматически?", answer: "Нет. Публичная открытая версия никогда не отправляет заявку за вас. Каждое действие проверяете и контролируете вы." },
      { question: "Можно использовать сервис по всему миру и на моём языке?", answer: "Интерфейс поддерживает 40 языков и глобальные фильтры. Покрытие зависит от одобренных источников в каждом регионе." },
    ],
  },
  uk: {
    eyebrow: "Поширені запитання",
    title: "Чіткі відповіді перед створенням пакета доказів.",
    intro: "Що CareerStoryMap уміє зараз, що контролюєте ви та які є обмеження.",
    items: [
      { question: "CareerStoryMap вигадуватиме мої досягнення?", answer: "Ні. Кожна порада має спиратися на надані вами докази. Непідтверджене залишається видимим як справжня прогалина." },
      { question: "Що потрібно для початку?", answer: "Достатньо справжнього резюме й опису вакансії. Дата співбесіди або етап заявки покращать план підготовки." },
      { question: "Результат відповідності — це бал ATS?", answer: "Ні. Замість універсального бала система показує сильні, часткові або відсутні докази для кожної важливої вимоги." },
      { question: "Чи потрібен обліковий запис?", answer: "Ні. Основний робочий простір доступний без входу. У поточній відкритій версії вхід необов’язковий." },
      { question: "Які документи можна імпортувати та чи вони приватні?", answer: "Звичайні PDF, DOCX, PPTX, XLSX, текстові й OpenDocument-файли типово обробляються у браузері. Сканам або старим форматам може знадобитися OCR чи конвертація." },
      { question: "CareerStoryMap подає заявки автоматично?", answer: "Ні. Публічна відкрита версія ніколи не надсилає заявку замість вас. Ви контролюєте кожну дію." },
      { question: "Можна користуватися в усьому світі й моєю мовою?", answer: "Інтерфейс підтримує 40 мов і глобальні фільтри. Покриття залежить від схвалених джерел у кожному регіоні." },
    ],
  },
  ar: {
    eyebrow: "الأسئلة الشائعة",
    title: "إجابات واضحة قبل بناء حزمة الأدلة.",
    intro: "ما الذي يقدمه CareerStoryMap اليوم، وما الذي يبقى تحت سيطرتك، وما حدوده الحالية.",
    items: [
      { question: "هل يختلق CareerStoryMap إنجازات لي؟", answer: "لا. يجب أن يرتبط كل اقتراح بدليل تقدمه أنت. ويظل ما لا تدعمه الأدلة ظاهرًا كفجوة حقيقية." },
      { question: "ماذا أحتاج للبدء؟", answer: "تكفي سيرة ذاتية حقيقية ووصف وظيفي حقيقي. وتزيد فائدة الخطة عند إضافة موعد المقابلة أو مرحلة التقديم." },
      { question: "هل نتيجة المطابقة هي درجة ATS؟", answer: "لا. بدل الادعاء بوجود درجة عالمية، تعرض قوة الدليل أو جزئيته أو غيابه لكل متطلب مهم." },
      { question: "هل أحتاج إلى حساب؟", answer: "لا. يمكنك استخدام مساحة العمل الأساسية دون تسجيل الدخول. تسجيل الدخول اختياري في النسخة المفتوحة الحالية." },
      { question: "ما الملفات التي يمكن استيرادها وهل تبقى خاصة؟", answer: "تُعالج ملفات PDF وDOCX وPPTX وXLSX والنص وOpenDocument الشائعة في متصفحك افتراضيًا. وقد تحتاج الملفات الممسوحة أو القديمة إلى OCR أو تحويل." },
      { question: "هل يقدّم CareerStoryMap للوظائف تلقائيًا؟", answer: "لا. النسخة العامة المفتوحة لا ترسل أي طلب نيابة عنك. أنت تراجع وتتحكم في كل خطوة." },
      { question: "هل يمكن استخدامه عالميًا وبلغتي؟", answer: "تدعم الواجهة 40 لغة ومرشحات عالمية. وتعتمد التغطية الحية على المصادر المعتمدة المتاحة لكل منطقة." },
    ],
  },
  he: {
    eyebrow: "שאלות נפוצות",
    title: "תשובות ברורות לפני בניית חבילת ההוכחות.",
    intro: "מה CareerStoryMap עושה היום, מה נשאר בשליטתכם ומהן המגבלות הנוכחיות.",
    items: [
      { question: "האם CareerStoryMap ממציא הישגים?", answer: "לא. כל הצעה חייבת להישען על ראיות שסיפקתם. מה שאינו נתמך נשאר מוצג כפער אמיתי." },
      { question: "מה צריך כדי להתחיל?", answer: "מספיקים קורות חיים אמיתיים ותיאור משרה אמיתי. תאריך ראיון או שלב הגשה משפרים את תוכנית ההכנה." },
      { question: "האם תוצאת ההתאמה היא ציון ATS?", answer: "לא. במקום להבטיח ציון אוניברסלי, היא מציגה ראיות חזקות, חלקיות או חסרות לכל דרישה חשובה." },
      { question: "האם צריך חשבון?", answer: "לא. אפשר להשתמש בסביבת העבודה המרכזית ללא התחברות. ההתחברות היא אופציונלית בגרסת הקוד הפתוח הנוכחית." },
      { question: "אילו מסמכים אפשר לייבא והאם הם פרטיים?", answer: "קובצי PDF, DOCX, PPTX, XLSX, טקסט ו-OpenDocument נפוצים מעובדים כברירת מחדל בדפדפן. סריקות או פורמטים ישנים עשויים לדרוש OCR או המרה." },
      { question: "האם CareerStoryMap מגיש מועמדות אוטומטית?", answer: "לא. הגרסה הציבורית לעולם אינה שולחת מועמדות במקומכם. אתם בודקים ושולטים בכל פעולה." },
      { question: "אפשר להשתמש בו בעולם ובשפה שלי?", answer: "הממשק תומך ב-40 שפות ובמסננים עולמיים. הכיסוי החי תלוי במקורות מאושרים הזמינים בכל אזור." },
    ],
  },
  hi: {
    eyebrow: "अक्सर पूछे जाने वाले प्रश्न",
    title: "अपना एविडेंस पैक बनाने से पहले स्पष्ट उत्तर।",
    intro: "CareerStoryMap आज क्या करता है, क्या आपके नियंत्रण में रहता है और इसकी मौजूदा सीमाएँ क्या हैं।",
    items: [
      { question: "क्या CareerStoryMap मेरी उपलब्धियाँ गढ़ेगा?", answer: "नहीं। हर सुझाव आपके दिए प्रमाण से जुड़ा होना चाहिए। बिना प्रमाण वाली बात वास्तविक कमी के रूप में दिखाई देती है।" },
      { question: "शुरू करने के लिए क्या चाहिए?", answer: "एक वास्तविक रिज़्यूमे और एक वास्तविक JD पर्याप्त हैं। इंटरव्यू की तारीख या आवेदन चरण जोड़ने से तैयारी योजना बेहतर होती है।" },
      { question: "क्या मैच परिणाम ATS स्कोर है?", answer: "नहीं। यह एक सार्वभौमिक स्कोर का दावा नहीं करता, बल्कि हर महत्वपूर्ण आवश्यकता के लिए मजबूत, आंशिक या गायब प्रमाण दिखाता है।" },
      { question: "क्या मुझे खाता चाहिए?", answer: "नहीं। मुख्य वर्कस्पेस बिना साइन इन किए उपयोग किया जा सकता है। मौजूदा ओपन-सोर्स संस्करण में साइन इन वैकल्पिक है।" },
      { question: "कौन से दस्तावेज़ आयात कर सकता हूँ और क्या वे निजी हैं?", answer: "सामान्य PDF, DOCX, PPTX, XLSX, टेक्स्ट और OpenDocument फ़ाइलें डिफ़ॉल्ट रूप से ब्राउज़र में संसाधित होती हैं। स्कैन या पुराने प्रारूप को OCR या रूपांतरण चाहिए हो सकता है।" },
      { question: "क्या CareerStoryMap अपने आप आवेदन करता है?", answer: "नहीं। सार्वजनिक ओपन-सोर्स संस्करण आपकी ओर से आवेदन नहीं भेजता। हर कार्रवाई पर आपका नियंत्रण रहता है।" },
      { question: "क्या इसे दुनिया भर में अपनी भाषा में उपयोग कर सकता हूँ?", answer: "इंटरफ़ेस 40 भाषाओं और वैश्विक फ़िल्टर का समर्थन करता है। लाइव कवरेज हर क्षेत्र के स्वीकृत स्रोतों पर निर्भर है।" },
    ],
  },
  bn: {
    eyebrow: "সাধারণ প্রশ্ন",
    title: "প্রমাণের প্যাক তৈরির আগে পরিষ্কার উত্তর।",
    intro: "CareerStoryMap এখন কী করে, কী আপনার নিয়ন্ত্রণে থাকে এবং বর্তমান সীমা কোথায়।",
    items: [
      { question: "CareerStoryMap কি আমার অর্জন বানিয়ে দেবে?", answer: "না। প্রতিটি পরামর্শ আপনার দেওয়া প্রমাণের সঙ্গে যুক্ত থাকতে হবে। প্রমাণ না থাকলে সেটি প্রকৃত ঘাটতি হিসেবেই দেখা যাবে।" },
      { question: "শুরু করতে কী লাগবে?", answer: "একটি বাস্তব জীবনবৃত্তান্ত ও একটি বাস্তব চাকরির বিবরণ যথেষ্ট। সাক্ষাৎকারের তারিখ বা আবেদনের ধাপ যোগ করলে পরিকল্পনা আরও কার্যকর হয়।" },
      { question: "ম্যাচ ফল কি ATS স্কোর?", answer: "না। একক সার্বজনীন স্কোরের বদলে প্রতিটি গুরুত্বপূর্ণ চাহিদার জন্য শক্তিশালী, আংশিক বা অনুপস্থিত প্রমাণ দেখায়।" },
      { question: "অ্যাকাউন্ট কি দরকার?", answer: "না। সাইন ইন ছাড়াই মূল ওয়ার্কস্পেস ব্যবহার করা যায়। বর্তমান ওপেন-সোর্স সংস্করণে সাইন ইন ঐচ্ছিক।" },
      { question: "কোন নথি আনা যায় এবং সেগুলো কি ব্যক্তিগত?", answer: "সাধারণ PDF, DOCX, PPTX, XLSX, টেক্সট ও OpenDocument ফাইল ডিফল্টভাবে ব্রাউজারে প্রক্রিয়াকৃত হয়। স্ক্যান বা পুরোনো ফাইলে OCR বা রূপান্তর লাগতে পারে।" },
      { question: "CareerStoryMap কি নিজে আবেদন করে?", answer: "না। প্রকাশ্য ওপেন-সোর্স সংস্করণ আপনার হয়ে আবেদন পাঠায় না। প্রতিটি পদক্ষেপ আপনি নিয়ন্ত্রণ করেন।" },
      { question: "বিশ্বজুড়ে নিজের ভাষায় ব্যবহার করা যায়?", answer: "ইন্টারফেস ৪০টি ভাষা ও বৈশ্বিক ফিল্টার সমর্থন করে। লাইভ কভারেজ অঞ্চলভিত্তিক অনুমোদিত উৎসের ওপর নির্ভর করে।" },
    ],
  },
  ur: {
    eyebrow: "اکثر پوچھے گئے سوالات",
    title: "ثبوتی پیک بنانے سے پہلے واضح جوابات۔",
    intro: "CareerStoryMap آج کیا کرتا ہے، کیا آپ کے اختیار میں رہتا ہے اور موجودہ حدود کیا ہیں۔",
    items: [
      { question: "کیا CareerStoryMap میری کامیابیاں گھڑے گا؟", answer: "نہیں۔ ہر تجویز آپ کے فراہم کردہ ثبوت سے جڑی ہونی چاہیے۔ بغیر ثبوت کی بات حقیقی خلا کے طور پر دکھائی جاتی ہے۔" },
      { question: "شروع کرنے کے لیے کیا چاہیے؟", answer: "ایک حقیقی ریزیومے اور ایک حقیقی JD کافی ہیں۔ انٹرویو کی تاریخ یا درخواست کا مرحلہ شامل کرنے سے تیاری بہتر ہوتی ہے۔" },
      { question: "کیا میچ نتیجہ ATS اسکور ہے؟", answer: "نہیں۔ ایک عالمی اسکور کے بجائے یہ ہر اہم ضرورت کے لیے مضبوط، جزوی یا غائب ثبوت دکھاتا ہے۔" },
      { question: "کیا اکاؤنٹ ضروری ہے؟", answer: "نہیں۔ مرکزی ورک اسپیس بغیر سائن ان استعمال ہو سکتی ہے۔ موجودہ اوپن سورس ورژن میں سائن ان اختیاری ہے۔" },
      { question: "کون سی دستاویزات درآمد ہو سکتی ہیں اور کیا وہ نجی ہیں؟", answer: "عام PDF، DOCX، PPTX، XLSX، متن اور OpenDocument فائلیں عموماً براؤزر میں پراسیس ہوتی ہیں۔ اسکین یا پرانے فارمیٹ کو OCR یا تبدیلی درکار ہو سکتی ہے۔" },
      { question: "کیا CareerStoryMap خودکار درخواست بھیجتا ہے؟", answer: "نہیں۔ عوامی اوپن سورس ورژن آپ کی طرف سے درخواست جمع نہیں کرتا۔ ہر قدم آپ کے اختیار میں ہے۔" },
      { question: "کیا اسے دنیا بھر میں اپنی زبان میں استعمال کر سکتا ہوں؟", answer: "انٹرفیس 40 زبانوں اور عالمی فلٹرز کی حمایت کرتا ہے۔ لائیو کوریج ہر خطے کے منظور شدہ ذرائع پر منحصر ہے۔" },
    ],
  },
  id: {
    eyebrow: "Pertanyaan umum",
    title: "Jawaban jelas sebelum membuat paket bukti Anda.",
    intro: "Apa yang dilakukan CareerStoryMap saat ini, apa yang Anda kendalikan, dan batasannya.",
    items: [
      { question: "Apakah CareerStoryMap mengarang pencapaian saya?", answer: "Tidak. Setiap saran harus terhubung ke bukti yang Anda berikan. Bukti yang tidak ada tetap terlihat sebagai kesenjangan nyata." },
      { question: "Apa yang saya perlukan untuk mulai?", answer: "Satu resume nyata dan satu deskripsi pekerjaan nyata sudah cukup. Tanggal wawancara atau tahap lamaran membuat rencana lebih berguna." },
      { question: "Apakah hasil kecocokan merupakan skor ATS?", answer: "Tidak. Hasil ini menunjukkan bukti kuat, sebagian, atau tidak ada untuk setiap persyaratan penting, bukan mengklaim satu skor ATS universal." },
      { question: "Apakah saya perlu akun?", answer: "Tidak. Ruang kerja inti dapat digunakan tanpa masuk. Masuk bersifat opsional pada versi sumber terbuka saat ini." },
      { question: "Dokumen apa yang dapat diimpor dan apakah tetap privat?", answer: "PDF, DOCX, PPTX, XLSX, teks, dan OpenDocument umum diproses di browser secara default. Hasil pindai atau format lama mungkin memerlukan OCR atau konversi." },
      { question: "Apakah CareerStoryMap melamar otomatis?", answer: "Tidak. Versi publik tidak pernah mengirim lamaran untuk Anda. Anda meninjau dan mengendalikan setiap tindakan." },
      { question: "Dapatkah saya menggunakannya di seluruh dunia dan dalam bahasa saya?", answer: "Antarmuka mendukung 40 bahasa dan filter global. Cakupan langsung bergantung pada sumber yang disetujui di tiap wilayah." },
    ],
  },
  ms: {
    eyebrow: "Soalan lazim",
    title: "Jawapan jelas sebelum membina pek bukti anda.",
    intro: "Apa yang dilakukan CareerStoryMap hari ini, perkara yang anda kawal dan batas semasa.",
    items: [
      { question: "Adakah CareerStoryMap mereka-reka pencapaian saya?", answer: "Tidak. Setiap cadangan mesti berpaut pada bukti yang anda berikan. Bukti yang tiada kekal sebagai jurang sebenar." },
      { question: "Apakah yang diperlukan untuk bermula?", answer: "Satu resume sebenar dan satu huraian kerja sebenar sudah mencukupi. Tarikh temu duga atau peringkat permohonan menambah baik pelan." },
      { question: "Adakah hasil padanan ialah skor ATS?", answer: "Tidak. Ia menunjukkan bukti kuat, separa atau tiada bagi setiap keperluan penting, bukan mendakwa satu skor ATS sejagat." },
      { question: "Adakah saya perlukan akaun?", answer: "Tidak. Ruang kerja teras boleh digunakan tanpa log masuk. Log masuk adalah pilihan dalam versi sumber terbuka semasa." },
      { question: "Dokumen apa boleh diimport dan adakah ia peribadi?", answer: "PDF, DOCX, PPTX, XLSX, teks dan OpenDocument lazim diproses dalam pelayar secara lalai. Imbasan atau format lama mungkin memerlukan OCR atau penukaran." },
      { question: "Adakah CareerStoryMap memohon secara automatik?", answer: "Tidak. Versi awam tidak pernah menghantar permohonan bagi pihak anda. Anda menyemak dan mengawal setiap tindakan." },
      { question: "Boleh digunakan di seluruh dunia dan dalam bahasa saya?", answer: "Antara muka menyokong 40 bahasa dan penapis global. Liputan langsung bergantung pada sumber diluluskan mengikut wilayah." },
    ],
  },
  th: {
    eyebrow: "คำถามที่พบบ่อย",
    title: "คำตอบที่ชัดเจนก่อนสร้างชุดหลักฐานของคุณ",
    intro: "CareerStoryMap ทำอะไรได้ในวันนี้ สิ่งใดอยู่ในการควบคุมของคุณ และข้อจำกัดปัจจุบัน",
    items: [
      { question: "CareerStoryMap จะสร้างผลงานที่ไม่จริงให้ฉันหรือไม่", answer: "ไม่ ทุกคำแนะนำต้องเชื่อมกลับไปยังหลักฐานที่คุณให้ ส่วนที่ไม่มีหลักฐานจะยังแสดงเป็นช่องว่างจริง" },
      { question: "ต้องใช้อะไรในการเริ่มต้น", answer: "เรซูเม่จริงหนึ่งฉบับและ JD จริงหนึ่งรายการก็เพียงพอ การเพิ่มวันสัมภาษณ์หรือขั้นตอนสมัครจะช่วยให้แผนมีประโยชน์ขึ้น" },
      { question: "ผลการจับคู่คือคะแนน ATS หรือไม่", answer: "ไม่ ระบบจะแสดงหลักฐานที่แข็งแรง บางส่วน หรือขาดหายสำหรับแต่ละข้อกำหนด แทนการอ้างคะแนน ATS แบบเดียว" },
      { question: "จำเป็นต้องมีบัญชีหรือไม่", answer: "ไม่ คุณใช้พื้นที่ทำงานหลักได้โดยไม่ต้องลงชื่อเข้าใช้ การลงชื่อเข้าใช้เป็นทางเลือกในเวอร์ชันโอเพนซอร์สปัจจุบัน" },
      { question: "นำเข้าไฟล์อะไรได้บ้างและข้อมูลเป็นส่วนตัวหรือไม่", answer: "ไฟล์ PDF, DOCX, PPTX, XLSX, ข้อความ และ OpenDocument ทั่วไปจะประมวลผลในเบราว์เซอร์โดยค่าเริ่มต้น ไฟล์สแกนหรือเก่าอาจต้อง OCR หรือแปลงก่อน" },
      { question: "CareerStoryMap สมัครงานให้อัตโนมัติหรือไม่", answer: "ไม่ เวอร์ชันสาธารณะจะไม่ส่งใบสมัครแทนคุณ คุณตรวจสอบและควบคุมทุกการทำงาน" },
      { question: "ใช้ได้ทั่วโลกและในภาษาของฉันหรือไม่", answer: "อินเทอร์เฟซรองรับ 40 ภาษาและตัวกรองทั่วโลก ความครอบคลุมแบบสดขึ้นอยู่กับแหล่งข้อมูลที่ได้รับอนุมัติในแต่ละภูมิภาค" },
    ],
  },
  vi: {
    eyebrow: "Câu hỏi thường gặp",
    title: "Câu trả lời rõ ràng trước khi tạo bộ bằng chứng.",
    intro: "CareerStoryMap hiện làm được gì, điều gì do bạn kiểm soát và các giới hạn hiện tại.",
    items: [
      { question: "CareerStoryMap có bịa thành tích cho tôi không?", answer: "Không. Mọi gợi ý phải liên kết với bằng chứng bạn cung cấp. Phần không có bằng chứng vẫn được hiển thị là khoảng trống thật." },
      { question: "Tôi cần gì để bắt đầu?", answer: "Một CV thật và một JD thật là đủ. Ngày phỏng vấn hoặc giai đoạn ứng tuyển giúp kế hoạch chuẩn bị hữu ích hơn." },
      { question: "Kết quả đối chiếu có phải điểm ATS không?", answer: "Không. Hệ thống hiển thị bằng chứng mạnh, một phần hoặc thiếu cho từng yêu cầu quan trọng thay vì tuyên bố một điểm ATS chung." },
      { question: "Tôi có cần tài khoản không?", answer: "Không. Bạn có thể dùng không gian chính mà không đăng nhập. Đăng nhập là tùy chọn trong phiên bản nguồn mở hiện tại." },
      { question: "Có thể nhập tài liệu nào và chúng có riêng tư không?", answer: "PDF, DOCX, PPTX, XLSX, văn bản và OpenDocument thông dụng được xử lý trong trình duyệt theo mặc định. Bản quét hoặc định dạng cũ có thể cần OCR hoặc chuyển đổi." },
      { question: "CareerStoryMap có tự động ứng tuyển không?", answer: "Không. Phiên bản công khai không bao giờ gửi đơn thay bạn. Bạn xem xét và kiểm soát mọi hành động." },
      { question: "Có thể dùng trên toàn cầu và bằng ngôn ngữ của tôi không?", answer: "Giao diện hỗ trợ 40 ngôn ngữ và bộ lọc toàn cầu. Phạm vi trực tiếp phụ thuộc vào nguồn được phê duyệt ở từng khu vực." },
    ],
  },
  fil: {
    eyebrow: "Mga madalas itanong",
    title: "Malinaw na sagot bago buuin ang iyong evidence pack.",
    intro: "Ano ang ginagawa ng CareerStoryMap ngayon, ano ang kontrolado mo, at ang kasalukuyang limitasyon.",
    items: [
      { question: "Gagawa ba ang CareerStoryMap ng pekeng achievement?", answer: "Hindi. Dapat nakaugnay ang bawat mungkahi sa ebidensiyang ibinigay mo. Ang walang suporta ay mananatiling tunay na gap." },
      { question: "Ano ang kailangan para magsimula?", answer: "Sapat na ang isang totoong resume at isang totoong JD. Mas magiging kapaki-pakinabang ang plano kapag idinagdag ang petsa ng interview o yugto ng application." },
      { question: "ATS score ba ang match result?", answer: "Hindi. Ipinapakita nito ang malakas, bahagya, o nawawalang ebidensiya sa bawat mahalagang requirement sa halip na mangakong may iisang ATS score." },
      { question: "Kailangan ko ba ng account?", answer: "Hindi. Magagamit ang pangunahing workspace nang hindi nag-sign in. Opsyonal ang sign-in sa kasalukuyang open-source na bersyon." },
      { question: "Anong dokumento ang mai-import at pribado ba ang mga ito?", answer: "Ang karaniwang PDF, DOCX, PPTX, XLSX, text, at OpenDocument ay pinoproseso sa browser bilang default. Maaaring kailangan ng OCR o conversion ang scan at lumang format." },
      { question: "Awtomatikong nag-a-apply ba ang CareerStoryMap?", answer: "Hindi. Hindi nagsusumite ng application para sa iyo ang pampublikong bersyon. Ikaw ang sumusuri at kumokontrol sa bawat aksyon." },
      { question: "Magagamit ba ito sa buong mundo at sa wika ko?", answer: "Sinusuportahan ng interface ang 40 wika at global na filter. Nakadepende ang live coverage sa aprubadong source sa bawat rehiyon." },
    ],
  },
  sv: {
    eyebrow: "Vanliga frågor",
    title: "Tydliga svar innan du bygger ditt bevispaket.",
    intro: "Vad CareerStoryMap gör i dag, vad du styr och vilka begränsningar som finns.",
    items: [
      { question: "Hittar CareerStoryMap på prestationer åt mig?", answer: "Nej. Varje förslag måste kunna kopplas till bevis du lämnar. Det som saknar stöd visas som en verklig lucka." },
      { question: "Vad behöver jag för att börja?", answer: "Ett riktigt cv och en riktig jobbannons räcker. Intervjudatum eller ansökningssteg gör planen mer användbar." },
      { question: "Är matchningsresultatet ett ATS-värde?", answer: "Nej. Det visar starka, delvisa eller saknade bevis för varje viktigt krav i stället för att lova ett universellt ATS-värde." },
      { question: "Behöver jag ett konto?", answer: "Nej. Kärnarbetsytan fungerar utan inloggning. Inloggning är valfri i den nuvarande öppna versionen." },
      { question: "Vilka dokument kan jag importera och är de privata?", answer: "Vanliga PDF-, DOCX-, PPTX-, XLSX-, text- och OpenDocument-filer bearbetas normalt i webbläsaren. Skanningar eller äldre format kan kräva OCR eller konvertering." },
      { question: "Söker CareerStoryMap jobb automatiskt?", answer: "Nej. Den offentliga versionen skickar aldrig en ansökan åt dig. Du granskar och styr varje åtgärd." },
      { question: "Kan jag använda det globalt och på mitt språk?", answer: "Gränssnittet stöder 40 språk och globala filter. Livetäckning beror på godkända källor i varje region." },
    ],
  },
  no: {
    eyebrow: "Vanlige spørsmål",
    title: "Klare svar før du bygger bevispakken din.",
    intro: "Hva CareerStoryMap gjør i dag, hva du styrer og hvilke begrensninger som finnes.",
    items: [
      { question: "Finner CareerStoryMap på prestasjoner for meg?", answer: "Nei. Hvert forslag må knyttes til bevis du gir. Det som mangler støtte, vises som et reelt gap." },
      { question: "Hva trenger jeg for å starte?", answer: "En ekte CV og en ekte stillingsbeskrivelse er nok. Intervjudato eller søknadsfase gjør planen mer nyttig." },
      { question: "Er resultatet en ATS-poengsum?", answer: "Nei. Det viser sterke, delvise eller manglende bevis for hvert viktig krav i stedet for å love én universell ATS-poengsum." },
      { question: "Trenger jeg en konto?", answer: "Nei. Kjernearbeidsområdet kan brukes uten innlogging. Innlogging er valgfritt i dagens åpne versjon." },
      { question: "Hvilke dokumenter kan jeg importere, og er de private?", answer: "Vanlige PDF-, DOCX-, PPTX-, XLSX-, tekst- og OpenDocument-filer behandles som standard i nettleseren. Skanninger eller eldre formater kan kreve OCR eller konvertering." },
      { question: "Søker CareerStoryMap automatisk på jobber?", answer: "Nei. Den offentlige versjonen sender aldri en søknad for deg. Du gjennomgår og styrer hver handling." },
      { question: "Kan jeg bruke det globalt og på språket mitt?", answer: "Grensesnittet støtter 40 språk og globale filtre. Livedekning avhenger av godkjente kilder i hver region." },
    ],
  },
  da: {
    eyebrow: "Ofte stillede spørgsmål",
    title: "Klare svar, før du bygger din evidenspakke.",
    intro: "Hvad CareerStoryMap gør i dag, hvad du styrer, og hvor de nuværende grænser går.",
    items: [
      { question: "Opfinder CareerStoryMap resultater for mig?", answer: "Nej. Hvert forslag skal kunne føres tilbage til den evidens, du giver. Det, der mangler støtte, vises som et reelt hul." },
      { question: "Hvad skal jeg bruge for at begynde?", answer: "Et rigtigt CV og en rigtig jobbeskrivelse er nok. Interviewdato eller ansøgningsfase gør planen mere nyttig." },
      { question: "Er matchresultatet en ATS-score?", answer: "Nej. Det viser stærk, delvis eller manglende evidens for hvert vigtigt krav i stedet for at love én universel ATS-score." },
      { question: "Skal jeg have en konto?", answer: "Nej. Kernearbejdsområdet kan bruges uden login. Login er valgfrit i den nuværende open source-version." },
      { question: "Hvilke dokumenter kan jeg importere, og er de private?", answer: "Almindelige PDF-, DOCX-, PPTX-, XLSX-, tekst- og OpenDocument-filer behandles som standard i browseren. Scanninger eller ældre formater kan kræve OCR eller konvertering." },
      { question: "Søger CareerStoryMap automatisk job?", answer: "Nej. Den offentlige version sender aldrig en ansøgning for dig. Du gennemgår og styrer alle handlinger." },
      { question: "Kan jeg bruge det globalt og på mit sprog?", answer: "Brugerfladen understøtter 40 sprog og globale filtre. Livedækning afhænger af godkendte kilder i hver region." },
    ],
  },
  fi: {
    eyebrow: "Usein kysytyt kysymykset",
    title: "Selkeät vastaukset ennen näyttöpaketin rakentamista.",
    intro: "Mitä CareerStoryMap tekee nyt, mitä sinä hallitset ja mitkä ovat nykyiset rajat.",
    items: [
      { question: "Keksiikö CareerStoryMap saavutuksia puolestani?", answer: "Ei. Jokaisen ehdotuksen täytyy perustua antamaasi näyttöön. Ilman tukea jäävä asia näkyy aitona puutteena." },
      { question: "Mitä tarvitsen aloittamiseen?", answer: "Yksi todellinen CV ja yksi todellinen työpaikkailmoitus riittävät. Haastattelupäivä tai hakuvaihe parantaa suunnitelmaa." },
      { question: "Onko vastaavuustulos ATS-pistemäärä?", answer: "Ei. Se näyttää vahvan, osittaisen tai puuttuvan näytön jokaiselle tärkeälle vaatimukselle eikä lupaa yhtä yleistä ATS-pistemäärää." },
      { question: "Tarvitsenko tilin?", answer: "Et. Ydintyötilaa voi käyttää kirjautumatta. Kirjautuminen on vapaaehtoista nykyisessä avoimen lähdekoodin versiossa." },
      { question: "Mitä asiakirjoja voin tuoda ja ovatko ne yksityisiä?", answer: "Tavalliset PDF-, DOCX-, PPTX-, XLSX-, teksti- ja OpenDocument-tiedostot käsitellään oletuksena selaimessa. Skannaukset tai vanhat muodot voivat vaatia OCR:n tai muunnoksen." },
      { question: "Hakeeko CareerStoryMap töitä automaattisesti?", answer: "Ei. Julkinen versio ei koskaan lähetä hakemusta puolestasi. Tarkistat ja hallitset jokaisen toiminnon." },
      { question: "Voinko käyttää sitä maailmanlaajuisesti omalla kielelläni?", answer: "Käyttöliittymä tukee 40 kieltä ja maailmanlaajuisia suodattimia. Reaaliaikainen kattavuus riippuu alueen hyväksytyistä lähteistä." },
    ],
  },
  cs: {
    eyebrow: "Časté dotazy",
    title: "Jasné odpovědi před vytvořením balíčku důkazů.",
    intro: "Co CareerStoryMap umí dnes, co ovládáte vy a kde jsou současné limity.",
    items: [
      { question: "Vymyslí CareerStoryMap moje úspěchy?", answer: "Ne. Každý návrh musí vycházet z důkazů, které poskytnete. Nepodložené části zůstanou viditelné jako skutečná mezera." },
      { question: "Co potřebuji na začátek?", answer: "Stačí skutečný životopis a skutečný popis práce. Datum pohovoru nebo fáze žádosti plán zpřesní." },
      { question: "Je výsledek shody skóre ATS?", answer: "Ne. Ukazuje silné, částečné nebo chybějící důkazy pro každý důležitý požadavek místo slibu univerzálního skóre ATS." },
      { question: "Potřebuji účet?", answer: "Ne. Hlavní pracovní prostor lze používat bez přihlášení. Přihlášení je v současné open-source verzi volitelné." },
      { question: "Jaké dokumenty lze importovat a jsou soukromé?", answer: "Běžné PDF, DOCX, PPTX, XLSX, textové a OpenDocument soubory se zpracují v prohlížeči. Skeny nebo staré formáty mohou vyžadovat OCR či převod." },
      { question: "Podává CareerStoryMap žádosti automaticky?", answer: "Ne. Veřejná verze nikdy neodešle žádost za vás. Každou akci kontrolujete vy." },
      { question: "Lze jej používat celosvětově a v mém jazyce?", answer: "Rozhraní podporuje 40 jazyků a globální filtry. Živé pokrytí závisí na schválených zdrojích v regionu." },
    ],
  },
  sk: {
    eyebrow: "Časté otázky",
    title: "Jasné odpovede pred vytvorením balíka dôkazov.",
    intro: "Čo CareerStoryMap dokáže dnes, čo ovládate vy a aké sú súčasné limity.",
    items: [
      { question: "Vymyslí CareerStoryMap moje úspechy?", answer: "Nie. Každý návrh musí vychádzať z dôkazov, ktoré poskytnete. Nepodložené časti zostanú viditeľné ako skutočná medzera." },
      { question: "Čo potrebujem na začiatok?", answer: "Stačí skutočný životopis a skutočný opis práce. Dátum pohovoru alebo fáza žiadosti plán spresnia." },
      { question: "Je výsledok zhody skóre ATS?", answer: "Nie. Zobrazuje silné, čiastočné alebo chýbajúce dôkazy ku každej požiadavke namiesto sľubu jedného univerzálneho skóre ATS." },
      { question: "Potrebujem účet?", answer: "Nie. Hlavný pracovný priestor sa dá používať bez prihlásenia. Prihlásenie je v súčasnej open-source verzii voliteľné." },
      { question: "Aké dokumenty môžem importovať a sú súkromné?", answer: "Bežné PDF, DOCX, PPTX, XLSX, textové a OpenDocument súbory sa spracujú v prehliadači. Skeny alebo staré formáty môžu vyžadovať OCR či konverziu." },
      { question: "Podáva CareerStoryMap žiadosti automaticky?", answer: "Nie. Verejná verzia nikdy neodošle žiadosť za vás. Každý krok kontrolujete vy." },
      { question: "Dá sa používať celosvetovo a v mojom jazyku?", answer: "Rozhranie podporuje 40 jazykov a globálne filtre. Živé pokrytie závisí od schválených zdrojov v regióne." },
    ],
  },
  hu: {
    eyebrow: "Gyakori kérdések",
    title: "Egyértelmű válaszok a bizonyítékcsomag elkészítése előtt.",
    intro: "Mit tesz ma a CareerStoryMap, mi marad az Ön kezében, és mik a jelenlegi korlátok.",
    items: [
      { question: "Kitalál eredményeket helyettem a CareerStoryMap?", answer: "Nem. Minden javaslatnak az Ön által megadott bizonyítékra kell támaszkodnia. A nem igazolt rész valódi hiányként látható marad." },
      { question: "Mire van szükségem a kezdéshez?", answer: "Egy valódi önéletrajz és egy valódi állásleírás elég. Az interjú dátuma vagy a jelentkezési szakasz javítja a tervet." },
      { question: "A találati eredmény ATS-pontszám?", answer: "Nem. Minden fontos követelménynél erős, részleges vagy hiányzó bizonyítékot mutat, nem pedig egyetlen univerzális ATS-pontot ígér." },
      { question: "Szükségem van fiókra?", answer: "Nem. Az alap munkaterület bejelentkezés nélkül használható. A bejelentkezés a jelenlegi nyílt verzióban választható." },
      { question: "Milyen dokumentumokat importálhatok, és privátak maradnak?", answer: "A szokásos PDF, DOCX, PPTX, XLSX, szöveg és OpenDocument fájlok alapból a böngészőben kerülnek feldolgozásra. A szkennelt vagy régi formátumok OCR-t vagy átalakítást igényelhetnek." },
      { question: "A CareerStoryMap automatikusan pályáz?", answer: "Nem. A nyilvános verzió soha nem küld jelentkezést Ön helyett. Minden lépést Ön ellenőriz." },
      { question: "Világszerte és a saját nyelvemen is használhatom?", answer: "A felület 40 nyelvet és globális szűrőket támogat. Az élő lefedettség a régiónként jóváhagyott forrásoktól függ." },
    ],
  },
  ro: {
    eyebrow: "Întrebări frecvente",
    title: "Răspunsuri clare înainte de a crea pachetul de dovezi.",
    intro: "Ce face CareerStoryMap astăzi, ce controlați dvs. și care sunt limitele actuale.",
    items: [
      { question: "CareerStoryMap inventează realizări pentru mine?", answer: "Nu. Fiecare sugestie trebuie să se lege de dovezile oferite de dvs. Ce nu are suport rămâne vizibil ca o lacună reală." },
      { question: "De ce am nevoie pentru a începe?", answer: "Un CV real și o descriere reală a postului sunt suficiente. Data interviului sau etapa candidaturii îmbunătățesc planul." },
      { question: "Rezultatul potrivirii este un scor ATS?", answer: "Nu. Arată dovezi puternice, parțiale sau lipsă pentru fiecare cerință importantă, fără a promite un scor ATS universal." },
      { question: "Am nevoie de un cont?", answer: "Nu. Spațiul principal poate fi folosit fără autentificare. Autentificarea este opțională în versiunea open source actuală." },
      { question: "Ce documente pot importa și rămân private?", answer: "Fișierele PDF, DOCX, PPTX, XLSX, text și OpenDocument obișnuite sunt procesate implicit în browser. Scanările sau formatele vechi pot necesita OCR ori conversie." },
      { question: "CareerStoryMap aplică automat la joburi?", answer: "Nu. Versiunea publică nu trimite niciodată o candidatură în locul dvs. Dvs. controlați fiecare acțiune." },
      { question: "Îl pot folosi oriunde și în limba mea?", answer: "Interfața acceptă 40 de limbi și filtre globale. Acoperirea live depinde de sursele aprobate din fiecare regiune." },
    ],
  },
  el: {
    eyebrow: "Συχνές ερωτήσεις",
    title: "Καθαρές απαντήσεις πριν δημιουργήσετε το πακέτο τεκμηρίων.",
    intro: "Τι κάνει σήμερα το CareerStoryMap, τι ελέγχετε εσείς και ποια είναι τα τρέχοντα όρια.",
    items: [
      { question: "Το CareerStoryMap επινοεί επιτεύγματα για μένα;", answer: "Όχι. Κάθε πρόταση πρέπει να συνδέεται με στοιχεία που παρέχετε. Ό,τι δεν τεκμηριώνεται παραμένει ορατό ως πραγματικό κενό." },
      { question: "Τι χρειάζομαι για να ξεκινήσω;", answer: "Αρκούν ένα πραγματικό βιογραφικό και μια πραγματική περιγραφή θέσης. Η ημερομηνία συνέντευξης ή το στάδιο αίτησης βελτιώνει το πλάνο." },
      { question: "Το αποτέλεσμα αντιστοίχισης είναι βαθμός ATS;", answer: "Όχι. Δείχνει ισχυρά, μερικά ή ελλιπή στοιχεία για κάθε σημαντική απαίτηση αντί να υπόσχεται έναν καθολικό βαθμό ATS." },
      { question: "Χρειάζομαι λογαριασμό;", answer: "Όχι. Ο βασικός χώρος λειτουργεί χωρίς σύνδεση. Η σύνδεση είναι προαιρετική στην τρέχουσα έκδοση ανοικτού κώδικα." },
      { question: "Ποια έγγραφα εισάγονται και παραμένουν ιδιωτικά;", answer: "Συνήθη PDF, DOCX, PPTX, XLSX, κείμενα και OpenDocument επεξεργάζονται στον φυλλομετρητή. Σαρώσεις ή παλιές μορφές μπορεί να χρειάζονται OCR ή μετατροπή." },
      { question: "Το CareerStoryMap κάνει αυτόματες αιτήσεις;", answer: "Όχι. Η δημόσια έκδοση δεν υποβάλλει ποτέ αίτηση για εσάς. Εσείς ελέγχετε κάθε ενέργεια." },
      { question: "Μπορώ να το χρησιμοποιώ παγκοσμίως και στη γλώσσα μου;", answer: "Η διεπαφή υποστηρίζει 40 γλώσσες και παγκόσμια φίλτρα. Η ζωντανή κάλυψη εξαρτάται από εγκεκριμένες πηγές ανά περιοχή." },
    ],
  },
  bg: {
    eyebrow: "Често задавани въпроси",
    title: "Ясни отговори преди създаването на пакет с доказателства.",
    intro: "Какво прави CareerStoryMap днес, какво контролирате вие и какви са текущите ограничения.",
    items: [
      { question: "CareerStoryMap измисля ли постижения вместо мен?", answer: "Не. Всяко предложение трябва да води до предоставено от вас доказателство. Неподкрепеното остава видимо като реална липса." },
      { question: "Какво ми трябва за начало?", answer: "Достатъчни са реално CV и реална обява. Датата на интервюто или етапът на кандидатурата подобряват плана." },
      { question: "Резултатът от съвпадението ATS оценка ли е?", answer: "Не. Той показва силни, частични или липсващи доказателства за всяко важно изискване, а не обещава универсална ATS оценка." },
      { question: "Нужен ли ми е профил?", answer: "Не. Основното работно пространство работи без вход. Входът е по избор в текущата версия с отворен код." },
      { question: "Какви документи мога да импортирам и лични ли са?", answer: "Обичайни PDF, DOCX, PPTX, XLSX, текст и OpenDocument файлове се обработват в браузъра. Сканирани или стари формати може да изискват OCR или конвертиране." },
      { question: "CareerStoryMap кандидатства ли автоматично?", answer: "Не. Публичната версия никога не изпраща кандидатура вместо вас. Вие контролирате всяко действие." },
      { question: "Мога ли да го използвам по света и на моя език?", answer: "Интерфейсът поддържа 40 езика и глобални филтри. Покритието на живо зависи от одобрени източници във всеки регион." },
    ],
  },
  hr: {
    eyebrow: "Česta pitanja",
    title: "Jasni odgovori prije izrade paketa dokaza.",
    intro: "Što CareerStoryMap radi danas, što vi kontrolirate i koja su trenutačna ograničenja.",
    items: [
      { question: "Izmišlja li CareerStoryMap moja postignuća?", answer: "Ne. Svaki prijedlog mora se povezati s dokazom koji ste dali. Nepotkrijepljeno ostaje vidljivo kao stvarni nedostatak." },
      { question: "Što trebam za početak?", answer: "Dovoljni su stvarni životopis i stvarni opis posla. Datum razgovora ili faza prijave poboljšavaju plan." },
      { question: "Je li rezultat podudaranja ATS ocjena?", answer: "Ne. Prikazuje snažan, djelomičan ili nedostajući dokaz za svaki važan zahtjev, bez obećanja univerzalne ATS ocjene." },
      { question: "Trebam li račun?", answer: "Ne. Glavni radni prostor radi bez prijave. Prijava je neobavezna u trenutačnoj otvorenoj verziji." },
      { question: "Koje dokumente mogu uvesti i ostaju li privatni?", answer: "Uobičajeni PDF, DOCX, PPTX, XLSX, tekst i OpenDocument obrađuju se u pregledniku. Skenovi ili stari formati mogu zahtijevati OCR ili pretvorbu." },
      { question: "Prijavljuje li CareerStoryMap poslove automatski?", answer: "Ne. Javna verzija nikada ne šalje prijavu umjesto vas. Vi pregledavate i kontrolirate svaku radnju." },
      { question: "Mogu li ga koristiti globalno i na svom jeziku?", answer: "Sučelje podržava 40 jezika i globalne filtre. Pokrivenost uživo ovisi o odobrenim izvorima po regiji." },
    ],
  },
  sr: {
    eyebrow: "Честа питања",
    title: "Јасни одговори пре израде пакета доказа.",
    intro: "Шта CareerStoryMap ради данас, шта ви контролишете и која су тренутна ограничења.",
    items: [
      { question: "Да ли CareerStoryMap измишља моја достигнућа?", answer: "Не. Сваки предлог мора бити повезан са доказом који сте дали. Непоткрепљено остаје видљиво као стварни недостатак." },
      { question: "Шта ми треба за почетак?", answer: "Довољни су стварни резиме и стварни опис посла. Датум интервјуа или фаза пријаве побољшавају план." },
      { question: "Да ли је резултат подударања ATS оцена?", answer: "Не. Приказује јак, делимичан или недостајући доказ за сваки важан захтев, без обећања универзалне ATS оцене." },
      { question: "Да ли ми треба налог?", answer: "Не. Главни радни простор ради без пријаве. Пријава је опциона у тренутној верзији отвореног кода." },
      { question: "Које документе могу да увезем и да ли су приватни?", answer: "Уобичајени PDF, DOCX, PPTX, XLSX, текст и OpenDocument обрађују се у прегледачу. Скенирани или стари формати могу захтевати OCR или конверзију." },
      { question: "Да ли CareerStoryMap аутоматски шаље пријаве?", answer: "Не. Јавна верзија никада не шаље пријаву уместо вас. Ви контролишете сваку радњу." },
      { question: "Могу ли да га користим глобално и на свом језику?", answer: "Интерфејс подржава 40 језика и глобалне филтере. Покривеност уживо зависи од одобрених извора по региону." },
    ],
  },
  sl: {
    eyebrow: "Pogosta vprašanja",
    title: "Jasni odgovori pred izdelavo paketa dokazov.",
    intro: "Kaj CareerStoryMap počne danes, kaj nadzirate vi in katere so trenutne omejitve.",
    items: [
      { question: "Ali CareerStoryMap izmišlja moje dosežke?", answer: "Ne. Vsak predlog mora izhajati iz dokaza, ki ga zagotovite. Nepodprto ostane vidno kot resnična vrzel." },
      { question: "Kaj potrebujem za začetek?", answer: "Dovolj sta resničen življenjepis in resničen opis dela. Datum razgovora ali faza prijave izboljšata načrt." },
      { question: "Je rezultat ujemanja ocena ATS?", answer: "Ne. Prikaže močne, delne ali manjkajoče dokaze za vsako pomembno zahtevo, namesto da bi obljubljal eno univerzalno oceno ATS." },
      { question: "Ali potrebujem račun?", answer: "Ne. Glavni delovni prostor lahko uporabljate brez prijave. Prijava je v trenutni odprtokodni različici izbirna." },
      { question: "Katere dokumente lahko uvozim in ali so zasebni?", answer: "Običajni PDF, DOCX, PPTX, XLSX, besedilo in OpenDocument se privzeto obdelajo v brskalniku. Skeni ali stari formati lahko zahtevajo OCR ali pretvorbo." },
      { question: "Ali CareerStoryMap samodejno pošilja prijave?", answer: "Ne. Javna različica nikoli ne odda prijave namesto vas. Vsako dejanje nadzirate vi." },
      { question: "Ali ga lahko uporabljam globalno in v svojem jeziku?", answer: "Vmesnik podpira 40 jezikov in globalne filtre. Pokritost v živo je odvisna od odobrenih virov po regiji." },
    ],
  },
  sw: {
    eyebrow: "Maswali yanayoulizwa mara kwa mara",
    title: "Majibu wazi kabla ya kujenga kifurushi chako cha ushahidi.",
    intro: "CareerStoryMap inafanya nini leo, nini kinasalia chini ya udhibiti wako, na mipaka ya sasa.",
    items: [
      { question: "Je, CareerStoryMap itatunga mafanikio yangu?", answer: "Hapana. Kila pendekezo lazima liunganishwe na ushahidi unaotoa. Kisicho na ushahidi kitaendelea kuonekana kama pengo halisi." },
      { question: "Nahitaji nini ili kuanza?", answer: "Wasifu halisi mmoja na maelezo halisi ya kazi yanatosha. Tarehe ya usaili au hatua ya ombi huongeza ubora wa mpango." },
      { question: "Je, matokeo ya ulinganisho ni alama ya ATS?", answer: "Hapana. Huonyesha ushahidi imara, wa sehemu au unaokosekana kwa kila hitaji muhimu badala ya kudai alama moja ya ATS." },
      { question: "Je, nahitaji akaunti?", answer: "Hapana. Nafasi kuu ya kazi inaweza kutumika bila kuingia. Kuingia ni hiari katika toleo la sasa la chanzo huria." },
      { question: "Ni nyaraka zipi ninaweza kuleta na je ni za faragha?", answer: "PDF, DOCX, PPTX, XLSX, maandishi na OpenDocument za kawaida huchakatwa kwenye kivinjari kwa chaguo-msingi. Skani au miundo ya zamani inaweza kuhitaji OCR au ubadilishaji." },
      { question: "Je, CareerStoryMap hutuma maombi kiotomatiki?", answer: "Hapana. Toleo la umma halitumii ombi kwa niaba yako. Unakagua na kudhibiti kila hatua." },
      { question: "Naweza kuitumia duniani kote na kwa lugha yangu?", answer: "Kiolesura kinaunga mkono lugha 40 na vichujio vya kimataifa. Ufikaji wa moja kwa moja hutegemea vyanzo vilivyoidhinishwa katika kila eneo." },
    ],
  },
  fa: {
    eyebrow: "پرسش‌های متداول",
    title: "پاسخ‌های روشن پیش از ساخت بسته شواهد.",
    intro: "CareerStoryMap امروز چه می‌کند، چه چیزهایی در کنترل شماست و محدودیت‌های فعلی چیست.",
    items: [
      { question: "آیا CareerStoryMap دستاوردی برای من می‌سازد؟", answer: "خیر. هر پیشنهاد باید به مدرکی که شما ارائه می‌کنید متصل باشد. موارد بدون مدرک به‌عنوان شکاف واقعی دیده می‌شوند." },
      { question: "برای شروع به چه چیزی نیاز دارم؟", answer: "یک رزومه واقعی و یک شرح شغل واقعی کافی است. تاریخ مصاحبه یا مرحله درخواست، برنامه را مفیدتر می‌کند." },
      { question: "آیا نتیجه تطبیق همان امتیاز ATS است؟", answer: "خیر. به‌جای ادعای یک امتیاز عمومی، برای هر نیاز مهم شواهد قوی، جزئی یا مفقود را نشان می‌دهد." },
      { question: "آیا به حساب نیاز دارم؟", answer: "خیر. فضای کاری اصلی بدون ورود قابل استفاده است. ورود در نسخه متن‌باز فعلی اختیاری است." },
      { question: "چه اسنادی را می‌توان وارد کرد و آیا خصوصی می‌مانند؟", answer: "فایل‌های رایج PDF، DOCX، PPTX، XLSX، متن و OpenDocument به‌طور پیش‌فرض در مرورگر پردازش می‌شوند. اسکن‌ها یا قالب‌های قدیمی ممکن است به OCR یا تبدیل نیاز داشته باشند." },
      { question: "آیا CareerStoryMap خودکار درخواست می‌فرستد؟", answer: "خیر. نسخه عمومی هیچ درخواست شغلی را به‌جای شما ارسال نمی‌کند. هر اقدام زیر نظر شماست." },
      { question: "آیا می‌توانم در سراسر جهان و به زبان خودم استفاده کنم؟", answer: "رابط از ۴۰ زبان و فیلترهای جهانی پشتیبانی می‌کند. پوشش زنده به منابع تأییدشده هر منطقه بستگی دارد." },
    ],
  },
} satisfies Record<LocaleCode, FaqCopy>;

export function faqCopyFor(locale: LocaleCode): FaqCopy {
  return faqCopy[locale];
}
