export const LANGUAGES = [
  ["en", "English"], ["ja", "日本語"], ["ko", "한국어"], ["zh-CN", "简体中文"],
  ["zh-TW", "繁體中文"], ["es", "Español"], ["fr", "Français"], ["de", "Deutsch"],
  ["pt-BR", "Português (Brasil)"], ["it", "Italiano"], ["nl", "Nederlands"], ["pl", "Polski"],
  ["tr", "Türkçe"], ["ru", "Русский"], ["uk", "Українська"], ["ar", "العربية"],
  ["he", "עברית"], ["hi", "हिन्दी"], ["bn", "বাংলা"], ["ur", "اردو"],
  ["id", "Bahasa Indonesia"], ["ms", "Bahasa Melayu"], ["th", "ไทย"], ["vi", "Tiếng Việt"],
  ["fil", "Filipino"], ["sv", "Svenska"], ["no", "Norsk"], ["da", "Dansk"],
  ["fi", "Suomi"], ["cs", "Čeština"], ["sk", "Slovenčina"], ["hu", "Magyar"],
  ["ro", "Română"], ["el", "Ελληνικά"], ["bg", "Български"], ["hr", "Hrvatski"],
  ["sr", "Српски"], ["sl", "Slovenščina"], ["sw", "Kiswahili"], ["fa", "فارسی"],
] as const;

export type LocaleCode = (typeof LANGUAGES)[number][0];

export type CoreCopy = {
  heroTitle: string;
  heroBody: string;
  enter: string;
  analyze: string;
  recommendations: string;
  market: string;
  tracker: string;
  copilot: string;
  feedback: string;
  worldwide: string;
  language: string;
  mode: string;
  manual: string;
  hybrid: string;
  automatic: string;
};

const en: CoreCopy = {
  heroTitle: "Find the right role for the story only you can prove.",
  heroBody: "Translate your career evidence into credible applications, discover stronger-fit jobs worldwide, and understand where hiring demand is moving.",
  enter: "Enter global workspace", analyze: "Analyze", recommendations: "Recommendations",
  market: "Market Insights", tracker: "Tracker", copilot: "Copilot", feedback: "Feedback",
  worldwide: "Worldwide", language: "Language", mode: "Application mode",
  manual: "Manual", hybrid: "Hybrid", automatic: "Automatic",
};

const translations: Record<LocaleCode, Partial<CoreCopy>> = {
  en,
  ja: { heroTitle: "あなたにしか証明できない経験に合う仕事を見つけましょう。", heroBody: "キャリアの実績を信頼できる応募書類に変え、世界中から相性の良い仕事を探し、採用需要の変化を把握できます。", enter: "グローバルワークスペースへ", analyze: "分析", recommendations: "おすすめ", market: "市場インサイト", tracker: "進捗管理", copilot: "コパイロット", feedback: "フィードバック", worldwide: "全世界", language: "言語", mode: "応募モード", manual: "手動", hybrid: "ハイブリッド", automatic: "自動" },
  ko: { heroTitle: "오직 당신만 증명할 수 있는 이야기에 맞는 직무를 찾으세요.", heroBody: "경력 근거를 신뢰할 수 있는 지원서로 바꾸고, 전 세계에서 더 잘 맞는 채용 공고를 찾으며 채용 수요의 변화를 파악하세요.", enter: "글로벌 워크스페이스 열기", analyze: "분석", recommendations: "추천", market: "시장 인사이트", tracker: "지원 관리", copilot: "코파일럿", feedback: "피드백", worldwide: "전 세계", language: "언어", mode: "지원 모드", manual: "수동", hybrid: "하이브리드", automatic: "자동" },
  "zh-CN": { heroTitle: "找到最适合你真实经历的职位。", heroBody: "将职业证据转化为可信的申请材料，在全球发现更匹配的职位，并了解招聘需求的变化。", enter: "进入全球工作区", analyze: "分析", recommendations: "职位推荐", market: "市场洞察", tracker: "申请追踪", copilot: "AI 助手", feedback: "反馈", worldwide: "全球", language: "语言", mode: "投递模式", manual: "手动", hybrid: "混合", automatic: "全自动" },
  "zh-TW": { heroTitle: "找到最適合你真實故事的職缺。", heroBody: "把職涯證據轉成可信的申請內容，在全球探索更合適的工作，並掌握招聘需求的變化。", enter: "進入全球工作區", analyze: "分析", recommendations: "職缺推薦", market: "市場洞察", tracker: "申請追蹤", copilot: "AI 助手", feedback: "意見回饋", worldwide: "全世界", language: "語言", mode: "投遞模式", manual: "全手動", hybrid: "混合", automatic: "全自動" },
  es: { heroTitle: "Encuentra el puesto adecuado para la historia que solo tú puedes demostrar.", heroBody: "Convierte tu experiencia verificable en candidaturas creíbles, descubre mejores oportunidades en todo el mundo y entiende cómo cambia la demanda.", enter: "Abrir espacio global", analyze: "Analizar", recommendations: "Recomendaciones", market: "Mercado laboral", tracker: "Seguimiento", copilot: "Copiloto", feedback: "Comentarios", worldwide: "Todo el mundo", language: "Idioma", mode: "Modo de candidatura", manual: "Manual", hybrid: "Híbrido", automatic: "Automático" },
  fr: { heroTitle: "Trouvez le poste adapté à l’histoire que vous seul pouvez prouver.", heroBody: "Transformez vos preuves professionnelles en candidatures crédibles, trouvez de meilleures offres dans le monde et suivez l’évolution de la demande.", enter: "Ouvrir l’espace mondial", analyze: "Analyser", recommendations: "Recommandations", market: "Marché de l’emploi", tracker: "Suivi", copilot: "Copilote", feedback: "Avis", worldwide: "Monde entier", language: "Langue", mode: "Mode de candidature", manual: "Manuel", hybrid: "Hybride", automatic: "Automatique" },
  de: { heroTitle: "Finde die Stelle, die zu deiner belegbaren Geschichte passt.", heroBody: "Verwandle nachweisbare Erfahrung in glaubwürdige Bewerbungen, entdecke weltweit passendere Stellen und erkenne Veränderungen der Nachfrage.", enter: "Globalen Arbeitsbereich öffnen", analyze: "Analysieren", recommendations: "Empfehlungen", market: "Arbeitsmarkt", tracker: "Bewerbungen", copilot: "Copilot", feedback: "Feedback", worldwide: "Weltweit", language: "Sprache", mode: "Bewerbungsmodus", manual: "Manuell", hybrid: "Hybrid", automatic: "Automatisch" },
  "pt-BR": { heroTitle: "Encontre a vaga certa para a história que só você pode comprovar.", heroBody: "Transforme evidências da sua carreira em candidaturas confiáveis, encontre vagas melhores no mundo todo e acompanhe a demanda.", enter: "Abrir espaço global", analyze: "Analisar", recommendations: "Recomendações", market: "Mercado de trabalho", tracker: "Acompanhamento", copilot: "Copiloto", feedback: "Feedback", worldwide: "Mundo todo", language: "Idioma", mode: "Modo de candidatura", manual: "Manual", hybrid: "Híbrido", automatic: "Automático" },
  it: { heroTitle: "Trova il ruolo giusto per la storia che solo tu puoi dimostrare.", heroBody: "Trasforma le prove della tua carriera in candidature credibili, scopri ruoli più adatti nel mondo e segui la domanda.", enter: "Apri lo spazio globale", analyze: "Analizza", recommendations: "Consigli", market: "Mercato del lavoro", tracker: "Monitoraggio", copilot: "Copilota", feedback: "Feedback", worldwide: "Tutto il mondo", language: "Lingua", mode: "Modalità candidatura", manual: "Manuale", hybrid: "Ibrida", automatic: "Automatica" },
  nl: { heroTitle: "Vind de functie die past bij het verhaal dat alleen jij kunt bewijzen.", heroBody: "Zet aantoonbare ervaring om in geloofwaardige sollicitaties, ontdek wereldwijd betere vacatures en volg de vraag.", enter: "Open wereldwijde werkruimte", analyze: "Analyseren", recommendations: "Aanbevelingen", market: "Arbeidsmarkt", tracker: "Volgen", copilot: "Copilot", feedback: "Feedback", worldwide: "Wereldwijd", language: "Taal", mode: "Sollicitatiemodus", manual: "Handmatig", hybrid: "Hybride", automatic: "Automatisch" },
  pl: { heroTitle: "Znajdź rolę pasującą do historii, którą tylko Ty możesz udowodnić.", heroBody: "Zamień potwierdzone doświadczenie w wiarygodne aplikacje, odkrywaj lepsze oferty na świecie i śledź popyt.", enter: "Otwórz globalną przestrzeń", analyze: "Analiza", recommendations: "Rekomendacje", market: "Rynek pracy", tracker: "Śledzenie", copilot: "Copilot", feedback: "Opinie", worldwide: "Cały świat", language: "Język", mode: "Tryb aplikowania", manual: "Ręczny", hybrid: "Hybrydowy", automatic: "Automatyczny" },
  tr: { heroTitle: "Yalnızca sizin kanıtlayabileceğiniz hikâyeye uygun işi bulun.", heroBody: "Kariyer kanıtlarınızı güvenilir başvurulara dönüştürün, dünya çapında daha uygun işler bulun ve talebi izleyin.", enter: "Küresel çalışma alanını aç", analyze: "Analiz", recommendations: "Öneriler", market: "Pazar içgörüleri", tracker: "Takip", copilot: "Yardımcı", feedback: "Geri bildirim", worldwide: "Dünya çapında", language: "Dil", mode: "Başvuru modu", manual: "Manuel", hybrid: "Hibrit", automatic: "Otomatik" },
  ru: { heroTitle: "Найдите роль для истории, которую можете подтвердить только вы.", heroBody: "Превратите подтверждённый опыт в убедительные отклики, находите подходящие вакансии по всему миру и следите за спросом.", enter: "Открыть глобальное пространство", analyze: "Анализ", recommendations: "Рекомендации", market: "Рынок труда", tracker: "Трекер", copilot: "Помощник", feedback: "Отзыв", worldwide: "Весь мир", language: "Язык", mode: "Режим отклика", manual: "Вручную", hybrid: "Гибридный", automatic: "Автоматический" },
  uk: { heroTitle: "Знайдіть роль для історії, яку можете підтвердити лише ви.", heroBody: "Перетворюйте підтверджений досвід на переконливі заявки, знаходьте кращі вакансії у світі та стежте за попитом.", enter: "Відкрити глобальний простір", analyze: "Аналіз", recommendations: "Рекомендації", market: "Ринок праці", tracker: "Трекер", copilot: "Помічник", feedback: "Відгук", worldwide: "Увесь світ", language: "Мова", mode: "Режим подання", manual: "Вручну", hybrid: "Гібридний", automatic: "Автоматичний" },
  ar: { heroTitle: "اعثر على الوظيفة المناسبة للقصة التي يمكنك وحدك إثباتها.", heroBody: "حوّل أدلة مسيرتك إلى طلبات موثوقة، واكتشف وظائف أنسب حول العالم، وتابع تغيّر الطلب.", enter: "افتح مساحة العمل العالمية", analyze: "تحليل", recommendations: "توصيات", market: "رؤى السوق", tracker: "متابعة الطلبات", copilot: "المساعد", feedback: "ملاحظات", worldwide: "العالم", language: "اللغة", mode: "وضع التقديم", manual: "يدوي", hybrid: "هجين", automatic: "تلقائي" },
  he: { heroTitle: "מצאו את התפקיד שמתאים לסיפור שרק אתם יכולים להוכיח.", heroBody: "הפכו ראיות מקצועיות למועמדות אמינה, גלו משרות מתאימות בעולם ועקבו אחר הביקוש.", enter: "פתיחת סביבת העבודה הגלובלית", analyze: "ניתוח", recommendations: "המלצות", market: "תובנות שוק", tracker: "מעקב", copilot: "עוזר", feedback: "משוב", worldwide: "כל העולם", language: "שפה", mode: "מצב הגשה", manual: "ידני", hybrid: "משולב", automatic: "אוטומטי" },
  hi: { heroTitle: "उस भूमिका को खोजें जो केवल आपकी प्रमाणित कहानी से मेल खाती है।", heroBody: "अपने करियर प्रमाण को विश्वसनीय आवेदन में बदलें, दुनिया भर में बेहतर नौकरियाँ खोजें और माँग में बदलाव समझें।", enter: "वैश्विक कार्यक्षेत्र खोलें", analyze: "विश्लेषण", recommendations: "सुझाव", market: "बाज़ार जानकारी", tracker: "ट्रैकर", copilot: "सहायक", feedback: "प्रतिक्रिया", worldwide: "पूरी दुनिया", language: "भाषा", mode: "आवेदन मोड", manual: "मैनुअल", hybrid: "हाइब्रिड", automatic: "स्वचालित" },
  bn: { heroTitle: "শুধু আপনি যে গল্প প্রমাণ করতে পারেন তার জন্য সঠিক কাজ খুঁজুন।", heroBody: "ক্যারিয়ারের প্রমাণকে বিশ্বাসযোগ্য আবেদনে রূপ দিন, বিশ্বজুড়ে উপযুক্ত কাজ খুঁজুন এবং চাহিদার পরিবর্তন বুঝুন।", enter: "গ্লোবাল ওয়ার্কস্পেস খুলুন", analyze: "বিশ্লেষণ", recommendations: "সুপারিশ", market: "বাজারের তথ্য", tracker: "ট্র্যাকার", copilot: "সহায়ক", feedback: "মতামত", worldwide: "বিশ্বজুড়ে", language: "ভাষা", mode: "আবেদনের ধরন", manual: "ম্যানুয়াল", hybrid: "হাইব্রিড", automatic: "স্বয়ংক্রিয়" },
  ur: { heroTitle: "اس کردار کو تلاش کریں جو صرف آپ کی ثابت شدہ کہانی سے میل کھاتا ہو۔", heroBody: "اپنے کیریئر کے ثبوت کو قابلِ اعتماد درخواستوں میں بدلیں، دنیا بھر میں بہتر ملازمتیں تلاش کریں اور طلب سمجھیں۔", enter: "عالمی ورک اسپیس کھولیں", analyze: "تجزیہ", recommendations: "تجاویز", market: "مارکیٹ کی معلومات", tracker: "ٹریکنگ", copilot: "معاون", feedback: "رائے", worldwide: "دنیا بھر", language: "زبان", mode: "درخواست کا طریقہ", manual: "دستی", hybrid: "ہائبرڈ", automatic: "خودکار" },
  id: { heroTitle: "Temukan peran yang tepat untuk kisah yang hanya dapat Anda buktikan.", heroBody: "Ubah bukti karier menjadi lamaran tepercaya, temukan pekerjaan yang lebih sesuai di seluruh dunia, dan pahami permintaan.", enter: "Buka ruang kerja global", analyze: "Analisis", recommendations: "Rekomendasi", market: "Wawasan pasar", tracker: "Pelacak", copilot: "Asisten", feedback: "Umpan balik", worldwide: "Seluruh dunia", language: "Bahasa", mode: "Mode lamaran", manual: "Manual", hybrid: "Hibrida", automatic: "Otomatis" },
  ms: { heroTitle: "Cari peranan yang sesuai dengan kisah yang hanya anda boleh buktikan.", heroBody: "Tukar bukti kerjaya kepada permohonan yang diyakini, temui kerja lebih sesuai di seluruh dunia dan fahami permintaan.", enter: "Buka ruang kerja global", analyze: "Analisis", recommendations: "Cadangan", market: "Cerapan pasaran", tracker: "Penjejak", copilot: "Pembantu", feedback: "Maklum balas", worldwide: "Seluruh dunia", language: "Bahasa", mode: "Mod permohonan", manual: "Manual", hybrid: "Hibrid", automatic: "Automatik" },
  th: { heroTitle: "ค้นหางานที่เหมาะกับเรื่องราวที่มีเพียงคุณเท่านั้นที่พิสูจน์ได้", heroBody: "เปลี่ยนหลักฐานอาชีพเป็นใบสมัครที่น่าเชื่อถือ ค้นหางานที่เหมาะกว่าทั่วโลก และติดตามความต้องการ", enter: "เปิดพื้นที่ทำงานทั่วโลก", analyze: "วิเคราะห์", recommendations: "คำแนะนำ", market: "ข้อมูลตลาด", tracker: "ติดตาม", copilot: "ผู้ช่วย", feedback: "ข้อเสนอแนะ", worldwide: "ทั่วโลก", language: "ภาษา", mode: "โหมดสมัครงาน", manual: "ด้วยตนเอง", hybrid: "ผสม", automatic: "อัตโนมัติ" },
  vi: { heroTitle: "Tìm công việc phù hợp với câu chuyện chỉ bạn mới có thể chứng minh.", heroBody: "Biến bằng chứng nghề nghiệp thành hồ sơ đáng tin cậy, khám phá việc làm phù hợp trên toàn cầu và theo dõi nhu cầu.", enter: "Mở không gian toàn cầu", analyze: "Phân tích", recommendations: "Đề xuất", market: "Thị trường việc làm", tracker: "Theo dõi", copilot: "Trợ lý", feedback: "Phản hồi", worldwide: "Toàn cầu", language: "Ngôn ngữ", mode: "Chế độ ứng tuyển", manual: "Thủ công", hybrid: "Kết hợp", automatic: "Tự động" },
  fil: { heroTitle: "Hanapin ang trabahong akma sa kuwentong ikaw lang ang makapagpapatunay.", heroBody: "Gawing mapagkakatiwalaang aplikasyon ang ebidensya ng karera, humanap ng mas angkop na trabaho sa buong mundo, at unawain ang demand.", enter: "Buksan ang global workspace", analyze: "Suriin", recommendations: "Mga rekomendasyon", market: "Market insights", tracker: "Tracker", copilot: "Katulong", feedback: "Feedback", worldwide: "Buong mundo", language: "Wika", mode: "Paraan ng pag-apply", manual: "Manwal", hybrid: "Hybrid", automatic: "Awtomatiko" },
  sv: { heroTitle: "Hitta rollen som passar berättelsen bara du kan bevisa.", heroBody: "Förvandla verifierad erfarenhet till trovärdiga ansökningar, hitta bättre jobb globalt och följ efterfrågan.", enter: "Öppna global arbetsyta", analyze: "Analysera", recommendations: "Rekommendationer", market: "Arbetsmarknad", tracker: "Spårning", copilot: "Assistent", feedback: "Feedback", worldwide: "Hela världen", language: "Språk", mode: "Ansökningsläge", manual: "Manuellt", hybrid: "Hybrid", automatic: "Automatiskt" },
  no: { heroTitle: "Finn rollen som passer historien bare du kan bevise.", heroBody: "Gjør dokumentert erfaring til troverdige søknader, finn bedre jobber globalt og følg etterspørselen.", enter: "Åpne globalt arbeidsområde", analyze: "Analyser", recommendations: "Anbefalinger", market: "Arbeidsmarked", tracker: "Sporing", copilot: "Assistent", feedback: "Tilbakemelding", worldwide: "Hele verden", language: "Språk", mode: "Søknadsmodus", manual: "Manuell", hybrid: "Hybrid", automatic: "Automatisk" },
  da: { heroTitle: "Find rollen, der passer til historien, kun du kan bevise.", heroBody: "Gør dokumenteret erfaring til troværdige ansøgninger, find bedre job globalt, og følg efterspørgslen.", enter: "Åbn globalt arbejdsområde", analyze: "Analysér", recommendations: "Anbefalinger", market: "Arbejdsmarked", tracker: "Sporing", copilot: "Assistent", feedback: "Feedback", worldwide: "Hele verden", language: "Sprog", mode: "Ansøgningstilstand", manual: "Manuel", hybrid: "Hybrid", automatic: "Automatisk" },
  fi: { heroTitle: "Löydä tehtävä, joka sopii vain sinun todistamaasi tarinaan.", heroBody: "Muuta todennettu kokemus uskottaviksi hakemuksiksi, löydä sopivampia töitä maailmalta ja seuraa kysyntää.", enter: "Avaa globaali työtila", analyze: "Analysoi", recommendations: "Suositukset", market: "Työmarkkinat", tracker: "Seuranta", copilot: "Avustaja", feedback: "Palaute", worldwide: "Koko maailma", language: "Kieli", mode: "Hakutila", manual: "Manuaalinen", hybrid: "Hybridi", automatic: "Automaattinen" },
  cs: { heroTitle: "Najděte roli pro příběh, který můžete doložit jen vy.", heroBody: "Proměňte doložené zkušenosti ve věrohodné žádosti, objevujte lepší pracovní místa po světě a sledujte poptávku.", enter: "Otevřít globální prostor", analyze: "Analyzovat", recommendations: "Doporučení", market: "Trh práce", tracker: "Sledování", copilot: "Asistent", feedback: "Zpětná vazba", worldwide: "Celý svět", language: "Jazyk", mode: "Režim žádosti", manual: "Ruční", hybrid: "Hybridní", automatic: "Automatický" },
  sk: { heroTitle: "Nájdite rolu pre príbeh, ktorý môžete dokázať len vy.", heroBody: "Premeňte doložené skúsenosti na dôveryhodné žiadosti, nájdite lepšie pracovné miesta vo svete a sledujte dopyt.", enter: "Otvoriť globálny priestor", analyze: "Analyzovať", recommendations: "Odporúčania", market: "Trh práce", tracker: "Sledovanie", copilot: "Asistent", feedback: "Spätná väzba", worldwide: "Celý svet", language: "Jazyk", mode: "Režim žiadosti", manual: "Ručný", hybrid: "Hybridný", automatic: "Automatický" },
  hu: { heroTitle: "Találd meg a szerepet ahhoz a történethez, amelyet csak te tudsz bizonyítani.", heroBody: "Alakítsd az igazolt tapasztalatot hiteles jelentkezéssé, találj jobb állásokat világszerte, és kövesd a keresletet.", enter: "Globális munkatér megnyitása", analyze: "Elemzés", recommendations: "Ajánlások", market: "Munkaerőpiac", tracker: "Követés", copilot: "Segítő", feedback: "Visszajelzés", worldwide: "Világszerte", language: "Nyelv", mode: "Jelentkezési mód", manual: "Kézi", hybrid: "Hibrid", automatic: "Automatikus" },
  ro: { heroTitle: "Găsește rolul potrivit poveștii pe care numai tu o poți demonstra.", heroBody: "Transformă experiența verificată în candidaturi credibile, găsește joburi mai bune în lume și urmărește cererea.", enter: "Deschide spațiul global", analyze: "Analiză", recommendations: "Recomandări", market: "Piața muncii", tracker: "Urmărire", copilot: "Asistent", feedback: "Feedback", worldwide: "În toată lumea", language: "Limbă", mode: "Mod de candidatură", manual: "Manual", hybrid: "Hibrid", automatic: "Automat" },
  el: { heroTitle: "Βρείτε τον ρόλο που ταιριάζει στην ιστορία που μόνο εσείς μπορείτε να αποδείξετε.", heroBody: "Μετατρέψτε την τεκμηριωμένη εμπειρία σε αξιόπιστες αιτήσεις, βρείτε καλύτερες θέσεις παγκοσμίως και παρακολουθήστε τη ζήτηση.", enter: "Άνοιγμα παγκόσμιου χώρου", analyze: "Ανάλυση", recommendations: "Προτάσεις", market: "Αγορά εργασίας", tracker: "Παρακολούθηση", copilot: "Βοηθός", feedback: "Σχόλια", worldwide: "Παγκοσμίως", language: "Γλώσσα", mode: "Τρόπος αίτησης", manual: "Χειροκίνητος", hybrid: "Υβριδικός", automatic: "Αυτόματος" },
  bg: { heroTitle: "Намерете ролята за историята, която само вие можете да докажете.", heroBody: "Превърнете доказания опит в надеждни кандидатури, намерете по-добри позиции по света и следете търсенето.", enter: "Отвори глобалното пространство", analyze: "Анализ", recommendations: "Препоръки", market: "Пазар на труда", tracker: "Проследяване", copilot: "Асистент", feedback: "Обратна връзка", worldwide: "Цял свят", language: "Език", mode: "Режим на кандидатстване", manual: "Ръчен", hybrid: "Хибриден", automatic: "Автоматичен" },
  hr: { heroTitle: "Pronađite ulogu koja odgovara priči koju samo vi možete dokazati.", heroBody: "Pretvorite dokazano iskustvo u vjerodostojne prijave, pronađite bolje poslove diljem svijeta i pratite potražnju.", enter: "Otvori globalni prostor", analyze: "Analiza", recommendations: "Preporuke", market: "Tržište rada", tracker: "Praćenje", copilot: "Asistent", feedback: "Povratne informacije", worldwide: "Cijeli svijet", language: "Jezik", mode: "Način prijave", manual: "Ručno", hybrid: "Hibridno", automatic: "Automatski" },
  sr: { heroTitle: "Пронађите улогу која одговара причи коју само ви можете доказати.", heroBody: "Претворите доказано искуство у веродостојне пријаве, пронађите боље послове широм света и пратите потражњу.", enter: "Отвори глобални простор", analyze: "Анализа", recommendations: "Препоруке", market: "Тржиште рада", tracker: "Праћење", copilot: "Асистент", feedback: "Повратне информације", worldwide: "Цео свет", language: "Језик", mode: "Начин пријаве", manual: "Ручно", hybrid: "Хибридно", automatic: "Аутоматски" },
  sl: { heroTitle: "Poiščite vlogo, ki ustreza zgodbi, ki jo lahko dokažete le vi.", heroBody: "Pretvorite dokazljive izkušnje v verodostojne prijave, poiščite boljša dela po svetu in spremljajte povpraševanje.", enter: "Odpri globalni prostor", analyze: "Analiza", recommendations: "Priporočila", market: "Trg dela", tracker: "Sledenje", copilot: "Pomočnik", feedback: "Povratne informacije", worldwide: "Ves svet", language: "Jezik", mode: "Način prijave", manual: "Ročno", hybrid: "Hibridno", automatic: "Samodejno" },
  sw: { heroTitle: "Pata nafasi inayolingana na hadithi ambayo ni wewe tu unaweza kuthibitisha.", heroBody: "Geuza ushahidi wa kazi kuwa maombi ya kuaminika, pata kazi bora duniani, na ufuatilie mahitaji.", enter: "Fungua nafasi ya kimataifa", analyze: "Changanua", recommendations: "Mapendekezo", market: "Maarifa ya soko", tracker: "Ufuatiliaji", copilot: "Msaidizi", feedback: "Maoni", worldwide: "Dunia nzima", language: "Lugha", mode: "Hali ya kutuma ombi", manual: "Mwenyewe", hybrid: "Mseto", automatic: "Otomatiki" },
  fa: { heroTitle: "نقشی را پیدا کنید که با داستانی هماهنگ است که فقط شما می‌توانید ثابت کنید.", heroBody: "شواهد شغلی را به درخواست‌های معتبر تبدیل کنید، فرصت‌های مناسب‌تر را در جهان بیابید و تغییر تقاضا را دنبال کنید.", enter: "فضای کاری جهانی را باز کنید", analyze: "تحلیل", recommendations: "پیشنهادها", market: "بینش بازار", tracker: "پیگیری", copilot: "دستیار", feedback: "بازخورد", worldwide: "سراسر جهان", language: "زبان", mode: "حالت درخواست", manual: "دستی", hybrid: "ترکیبی", automatic: "خودکار" },
};

export const RTL_LOCALES = new Set<LocaleCode>(["ar", "he", "ur", "fa"]);

export function copyFor(locale: LocaleCode): CoreCopy {
  return { ...en, ...translations[locale] };
}
