import type { LocaleCode } from "./i18n.ts";
import { marketValueFor } from "./market-localization.ts";

export const JOB_SEARCH_COPY_KEYS = [
  "searchPlaceholder",
  "allIndustries",
  "allWorkStyles",
  "employmentType",
  "allEmploymentTypes",
  "fullTime",
  "partTime",
  "contract",
  "internship",
  "temporary",
  "experienceLevel",
  "allExperienceLevels",
  "entryLevel",
  "midLevel",
  "senior",
  "leadManager",
  "executive",
  "datePosted",
  "anyTime",
  "past24Hours",
  "pastWeek",
  "pastMonth",
  "sortBy",
  "bestStoryFit",
  "newest",
  "fewestGaps",
  "clearFilters",
  "activeFilters",
  "liveOnlyDateHint",
  "noMatchesTitle",
  "noMatchesBody",
  "sourceLabelExample",
  "sourceLabelLive",
] as const;

export type JobSearchCopyKey = (typeof JOB_SEARCH_COPY_KEYS)[number];
export type JobSearchCopy = Readonly<Record<JobSearchCopyKey, string>>;

function defineRow<const T extends readonly string[]>(
  ...values: T & { readonly length: typeof JOB_SEARCH_COPY_KEYS.length }
): T {
  return values;
}

const JOB_SEARCH_COPY_ROWS = {
  en: defineRow(
    "Search roles, skills, or companies",
    "All industries",
    "All work styles",
    "Employment type",
    "All employment types",
    "Full-time",
    "Part-time",
    "Contract",
    "Internship",
    "Temporary",
    "Experience level",
    "All experience levels",
    "Entry level",
    "Mid-level",
    "Senior",
    "Lead / Manager",
    "Executive",
    "Date posted",
    "Any time",
    "Past 24 hours",
    "Past week",
    "Past month",
    "Sort by",
    "Best story fit",
    "Newest",
    "Fewest evidence gaps",
    "Clear filters",
    "Active filters",
    "Posted-date filters apply only to live roles with a published date.",
    "No matching roles",
    "Try broadening your search or clearing one or more filters.",
    "Example",
    "Live",
  ),
  ja: defineRow(
    "求人、スキル、企業名で検索",
    "すべての業界",
    "すべての働き方",
    "雇用形態",
    "すべての雇用形態",
    "正社員",
    "パートタイム",
    "契約社員",
    "インターンシップ",
    "臨時雇用",
    "経験レベル",
    "すべての経験レベル",
    "未経験・初級",
    "中堅",
    "シニア",
    "リード／マネージャー",
    "経営幹部",
    "掲載日",
    "指定なし",
    "過去24時間",
    "過去1週間",
    "過去1か月",
    "並べ替え",
    "ストーリーとの適合度順",
    "新着順",
    "証拠の不足が少ない順",
    "フィルターをクリア",
    "適用中のフィルター",
    "掲載日の絞り込みは、掲載日がある実在求人にのみ適用されます。",
    "条件に合う求人がありません",
    "検索条件を広げるか、いくつかのフィルターを解除してください。",
    "サンプル",
    "実在求人",
  ),
  ko: defineRow(
    "직무, 기술 또는 회사 검색",
    "모든 산업",
    "모든 근무 방식",
    "고용 형태",
    "모든 고용 형태",
    "정규직",
    "파트타임",
    "계약직",
    "인턴십",
    "임시직",
    "경력 수준",
    "모든 경력 수준",
    "신입",
    "중급",
    "시니어",
    "리드 / 관리자",
    "임원",
    "게시일",
    "전체 기간",
    "최근 24시간",
    "최근 1주",
    "최근 1개월",
    "정렬 기준",
    "스토리 적합도순",
    "최신순",
    "증거 공백이 적은 순",
    "필터 지우기",
    "적용 중인 필터",
    "게시일 필터는 게시일이 있는 실제 채용 공고에만 적용됩니다.",
    "조건에 맞는 직무가 없습니다",
    "검색 범위를 넓히거나 일부 필터를 지워 보세요.",
    "예시",
    "실제 공고",
  ),
  "zh-CN": defineRow(
    "搜索职位、技能或公司",
    "所有行业",
    "所有办公方式",
    "雇用类型",
    "所有雇用类型",
    "全职",
    "兼职",
    "合同制",
    "实习",
    "临时工作",
    "经验级别",
    "所有经验级别",
    "初级",
    "中级",
    "高级",
    "负责人／经理",
    "高管",
    "发布日期",
    "不限时间",
    "过去 24 小时",
    "过去一周",
    "过去一个月",
    "排序方式",
    "故事匹配度最高",
    "最新发布",
    "证据缺口最少",
    "清除筛选条件",
    "已启用的筛选条件",
    "发布日期筛选仅适用于标有发布日期的实时职位。",
    "没有匹配的职位",
    "请扩大搜索范围，或清除一个或多个筛选条件。",
    "示例",
    "实时职位",
  ),
  "zh-TW": defineRow(
    "搜尋職缺、技能或公司",
    "所有產業",
    "所有工作型態",
    "聘僱類型",
    "所有聘僱類型",
    "全職",
    "兼職",
    "約聘",
    "實習",
    "臨時職",
    "經驗層級",
    "所有經驗層級",
    "初階",
    "中階",
    "資深",
    "主管／經理",
    "高階主管",
    "刊登日期",
    "不限時間",
    "過去 24 小時",
    "過去一週",
    "過去一個月",
    "排序方式",
    "故事契合度最高",
    "最新刊登",
    "證據缺口最少",
    "清除篩選條件",
    "已套用的篩選條件",
    "刊登日期篩選僅適用於有標示刊登日期的即時職缺。",
    "找不到符合條件的職缺",
    "請放寬搜尋條件，或清除一個或多個篩選條件。",
    "範例",
    "即時職缺",
  ),
  es: defineRow(
    "Buscar puestos, habilidades o empresas",
    "Todos los sectores",
    "Todas las modalidades de trabajo",
    "Tipo de empleo",
    "Todos los tipos de empleo",
    "Jornada completa",
    "Media jornada",
    "Contrato",
    "Prácticas",
    "Temporal",
    "Nivel de experiencia",
    "Todos los niveles de experiencia",
    "Nivel inicial",
    "Nivel intermedio",
    "Sénior",
    "Responsable / Gerente",
    "Dirección ejecutiva",
    "Fecha de publicación",
    "Cualquier fecha",
    "Últimas 24 horas",
    "Última semana",
    "Último mes",
    "Ordenar por",
    "Mejor ajuste con tu historia",
    "Más recientes",
    "Menos brechas de evidencia",
    "Borrar filtros",
    "Filtros activos",
    "El filtro de fecha solo se aplica a ofertas reales con fecha de publicación.",
    "No hay puestos que coincidan",
    "Amplía la búsqueda o elimina uno o varios filtros.",
    "Ejemplo",
    "Oferta real",
  ),
  fr: defineRow(
    "Rechercher un poste, une compétence ou une entreprise",
    "Tous les secteurs",
    "Tous les modes de travail",
    "Type de contrat",
    "Tous les types de contrat",
    "Temps plein",
    "Temps partiel",
    "Contrat",
    "Stage",
    "Temporaire",
    "Niveau d’expérience",
    "Tous les niveaux d’expérience",
    "Débutant",
    "Intermédiaire",
    "Senior",
    "Responsable / Manager",
    "Direction",
    "Date de publication",
    "Toutes les dates",
    "Dernières 24 heures",
    "Dernière semaine",
    "Dernier mois",
    "Trier par",
    "Meilleure adéquation avec votre histoire",
    "Plus récentes",
    "Moins de lacunes de preuves",
    "Effacer les filtres",
    "Filtres actifs",
    "Le filtre de date s’applique uniquement aux offres réelles indiquant une date de publication.",
    "Aucun poste correspondant",
    "Élargissez votre recherche ou effacez un ou plusieurs filtres.",
    "Exemple",
    "Offre réelle",
  ),
  de: defineRow(
    "Nach Rollen, Fähigkeiten oder Unternehmen suchen",
    "Alle Branchen",
    "Alle Arbeitsmodelle",
    "Beschäftigungsart",
    "Alle Beschäftigungsarten",
    "Vollzeit",
    "Teilzeit",
    "Vertrag",
    "Praktikum",
    "Befristet",
    "Erfahrungsstufe",
    "Alle Erfahrungsstufen",
    "Berufseinstieg",
    "Mittlere Erfahrungsstufe",
    "Senior",
    "Teamleitung / Management",
    "Geschäftsleitung",
    "Veröffentlichungsdatum",
    "Jederzeit",
    "Letzte 24 Stunden",
    "Letzte Woche",
    "Letzter Monat",
    "Sortieren nach",
    "Beste Übereinstimmung mit Ihrer Story",
    "Neueste",
    "Wenigste Nachweislücken",
    "Filter zurücksetzen",
    "Aktive Filter",
    "Der Datumsfilter gilt nur für echte Stellen mit angegebenem Veröffentlichungsdatum.",
    "Keine passenden Stellen",
    "Erweitern Sie Ihre Suche oder setzen Sie einen oder mehrere Filter zurück.",
    "Beispiel",
    "Echte Stelle",
  ),
  "pt-BR": defineRow(
    "Buscar vagas, competências ou empresas",
    "Todos os setores",
    "Todos os modelos de trabalho",
    "Tipo de contratação",
    "Todos os tipos de contratação",
    "Tempo integral",
    "Meio período",
    "Contrato",
    "Estágio",
    "Temporário",
    "Nível de experiência",
    "Todos os níveis de experiência",
    "Nível inicial",
    "Nível intermediário",
    "Sênior",
    "Liderança / Gerência",
    "Executivo",
    "Data de publicação",
    "Qualquer período",
    "Últimas 24 horas",
    "Última semana",
    "Último mês",
    "Ordenar por",
    "Melhor aderência à sua história",
    "Mais recentes",
    "Menos lacunas de evidências",
    "Limpar filtros",
    "Filtros ativos",
    "O filtro de data vale apenas para vagas reais com data de publicação.",
    "Nenhuma vaga correspondente",
    "Amplie a busca ou remova um ou mais filtros.",
    "Exemplo",
    "Vaga real",
  ),
  it: defineRow(
    "Cerca ruoli, competenze o aziende",
    "Tutti i settori",
    "Tutte le modalità di lavoro",
    "Tipo di impiego",
    "Tutti i tipi di impiego",
    "Tempo pieno",
    "Part-time",
    "Contratto",
    "Tirocinio",
    "Temporaneo",
    "Livello di esperienza",
    "Tutti i livelli di esperienza",
    "Livello iniziale",
    "Livello intermedio",
    "Senior",
    "Responsabile / Manager",
    "Dirigente",
    "Data di pubblicazione",
    "Qualsiasi data",
    "Ultime 24 ore",
    "Ultima settimana",
    "Ultimo mese",
    "Ordina per",
    "Migliore aderenza alla tua storia",
    "Più recenti",
    "Meno lacune nelle prove",
    "Cancella filtri",
    "Filtri attivi",
    "Il filtro per data si applica solo alle offerte reali con una data di pubblicazione.",
    "Nessun ruolo corrispondente",
    "Amplia la ricerca o rimuovi uno o più filtri.",
    "Esempio",
    "Offerta reale",
  ),
  nl: defineRow(
    "Zoek op functie, vaardigheid of bedrijf",
    "Alle sectoren",
    "Alle werkvormen",
    "Dienstverband",
    "Alle dienstverbanden",
    "Voltijds",
    "Deeltijds",
    "Contract",
    "Stage",
    "Tijdelijk",
    "Ervaringsniveau",
    "Alle ervaringsniveaus",
    "Starter",
    "Medior",
    "Senior",
    "Lead / Manager",
    "Directie",
    "Publicatiedatum",
    "Alle datums",
    "Afgelopen 24 uur",
    "Afgelopen week",
    "Afgelopen maand",
    "Sorteren op",
    "Beste match met je verhaal",
    "Nieuwste",
    "Minste bewijshiaten",
    "Filters wissen",
    "Actieve filters",
    "Het datumfilter geldt alleen voor actuele vacatures met een publicatiedatum.",
    "Geen passende functies",
    "Maak je zoekopdracht ruimer of wis een of meer filters.",
    "Voorbeeld",
    "Actuele vacature",
  ),
  pl: defineRow(
    "Szukaj stanowisk, umiejętności lub firm",
    "Wszystkie branże",
    "Wszystkie tryby pracy",
    "Forma zatrudnienia",
    "Wszystkie formy zatrudnienia",
    "Pełny etat",
    "Niepełny etat",
    "Kontrakt",
    "Staż",
    "Praca tymczasowa",
    "Poziom doświadczenia",
    "Wszystkie poziomy doświadczenia",
    "Poziom początkujący",
    "Poziom średniozaawansowany",
    "Senior",
    "Lider / Menedżer",
    "Kadra zarządzająca",
    "Data publikacji",
    "Dowolny termin",
    "Ostatnie 24 godziny",
    "Ostatni tydzień",
    "Ostatni miesiąc",
    "Sortuj według",
    "Najlepsze dopasowanie do Twojej historii",
    "Najnowsze",
    "Najmniej luk w dowodach",
    "Wyczyść filtry",
    "Aktywne filtry",
    "Filtr daty dotyczy tylko aktualnych ofert z podaną datą publikacji.",
    "Brak pasujących stanowisk",
    "Poszerz wyszukiwanie lub wyczyść co najmniej jeden filtr.",
    "Przykład",
    "Aktualna oferta",
  ),
  tr: defineRow(
    "Pozisyon, beceri veya şirket ara",
    "Tüm sektörler",
    "Tüm çalışma biçimleri",
    "Çalışma türü",
    "Tüm çalışma türleri",
    "Tam zamanlı",
    "Yarı zamanlı",
    "Sözleşmeli",
    "Staj",
    "Geçici",
    "Deneyim seviyesi",
    "Tüm deneyim seviyeleri",
    "Başlangıç seviyesi",
    "Orta seviye",
    "Kıdemli",
    "Lider / Yönetici",
    "Üst düzey yönetici",
    "Yayınlanma tarihi",
    "Tüm zamanlar",
    "Son 24 saat",
    "Son hafta",
    "Son ay",
    "Sıralama ölçütü",
    "Hikâyenizle en iyi eşleşen",
    "En yeni",
    "En az kanıt açığı",
    "Filtreleri temizle",
    "Etkin filtreler",
    "Tarih filtresi yalnızca yayın tarihi bulunan güncel ilanlara uygulanır.",
    "Eşleşen pozisyon yok",
    "Aramanızı genişletin veya bir ya da daha fazla filtreyi temizleyin.",
    "Örnek",
    "Güncel ilan",
  ),
  ru: defineRow(
    "Поиск по должностям, навыкам или компаниям",
    "Все отрасли",
    "Все форматы работы",
    "Тип занятости",
    "Все типы занятости",
    "Полная занятость",
    "Частичная занятость",
    "Контракт",
    "Стажировка",
    "Временная работа",
    "Уровень опыта",
    "Все уровни опыта",
    "Начальный уровень",
    "Средний уровень",
    "Старший специалист",
    "Руководитель / Менеджер",
    "Высшее руководство",
    "Дата публикации",
    "За всё время",
    "За последние 24 часа",
    "За последнюю неделю",
    "За последний месяц",
    "Сортировать по",
    "Лучшему соответствию вашей истории",
    "Сначала новые",
    "Минимуму пробелов в доказательствах",
    "Сбросить фильтры",
    "Активные фильтры",
    "Фильтр по дате применяется только к актуальным вакансиям с датой публикации.",
    "Подходящих вакансий нет",
    "Расширьте поиск или сбросьте один или несколько фильтров.",
    "Пример",
    "Актуальная вакансия",
  ),
  uk: defineRow(
    "Шукати посади, навички або компанії",
    "Усі галузі",
    "Усі формати роботи",
    "Тип зайнятості",
    "Усі типи зайнятості",
    "Повна зайнятість",
    "Часткова зайнятість",
    "Контракт",
    "Стажування",
    "Тимчасова робота",
    "Рівень досвіду",
    "Усі рівні досвіду",
    "Початковий рівень",
    "Середній рівень",
    "Старший фахівець",
    "Керівник / Менеджер",
    "Вище керівництво",
    "Дата публікації",
    "За весь час",
    "За останні 24 години",
    "За останній тиждень",
    "За останній місяць",
    "Сортувати за",
    "Найкращою відповідністю вашій історії",
    "Найновіші",
    "Найменшою кількістю прогалин у доказах",
    "Очистити фільтри",
    "Активні фільтри",
    "Фільтр за датою діє лише для актуальних вакансій із датою публікації.",
    "Відповідних вакансій немає",
    "Розширте пошук або очистьте один чи кілька фільтрів.",
    "Приклад",
    "Актуальна вакансія",
  ),
  ar: defineRow(
    "ابحث عن وظائف أو مهارات أو شركات",
    "جميع القطاعات",
    "جميع أنماط العمل",
    "نوع التوظيف",
    "جميع أنواع التوظيف",
    "دوام كامل",
    "دوام جزئي",
    "عقد",
    "تدريب",
    "عمل مؤقت",
    "مستوى الخبرة",
    "جميع مستويات الخبرة",
    "مستوى مبتدئ",
    "مستوى متوسط",
    "مستوى خبير",
    "قائد / مدير",
    "إدارة تنفيذية",
    "تاريخ النشر",
    "أي وقت",
    "آخر 24 ساعة",
    "الأسبوع الماضي",
    "الشهر الماضي",
    "الترتيب حسب",
    "الأفضل توافقًا مع قصتك",
    "الأحدث",
    "أقل فجوات في الأدلة",
    "مسح عوامل التصفية",
    "عوامل التصفية النشطة",
    "يُطبّق فلتر التاريخ فقط على الوظائف الفعلية التي لها تاريخ نشر.",
    "لا توجد وظائف مطابقة",
    "وسّع نطاق البحث أو امسح عامل تصفية واحدًا أو أكثر.",
    "مثال",
    "وظيفة فعلية",
  ),
  he: defineRow(
    "חיפוש לפי תפקידים, מיומנויות או חברות",
    "כל הענפים",
    "כל צורות העבודה",
    "סוג העסקה",
    "כל סוגי ההעסקה",
    "משרה מלאה",
    "משרה חלקית",
    "חוזה",
    "התמחות",
    "משרה זמנית",
    "רמת ניסיון",
    "כל רמות הניסיון",
    "דרגת כניסה",
    "דרגת ביניים",
    "בכיר/ה",
    "ראש צוות / מנהל/ת",
    "הנהלה בכירה",
    "תאריך פרסום",
    "בכל זמן",
    "ב־24 השעות האחרונות",
    "בשבוע האחרון",
    "בחודש האחרון",
    "מיון לפי",
    "ההתאמה הטובה ביותר לסיפור שלך",
    "החדשות ביותר",
    "הכי מעט פערים בראיות",
    "ניקוי מסננים",
    "מסננים פעילים",
    "סינון לפי תאריך חל רק על משרות פעילות עם תאריך פרסום.",
    "לא נמצאו משרות תואמות",
    "אפשר להרחיב את החיפוש או לנקות מסנן אחד או יותר.",
    "דוגמה",
    "משרה פעילה",
  ),
  hi: defineRow(
    "भूमिकाएँ, कौशल या कंपनियाँ खोजें",
    "सभी उद्योग",
    "सभी कार्य व्यवस्थाएँ",
    "रोज़गार का प्रकार",
    "सभी रोज़गार प्रकार",
    "पूर्णकालिक",
    "अंशकालिक",
    "अनुबंध",
    "इंटर्नशिप",
    "अस्थायी",
    "अनुभव स्तर",
    "सभी अनुभव स्तर",
    "प्रारंभिक स्तर",
    "मध्य स्तर",
    "वरिष्ठ",
    "लीड / प्रबंधक",
    "कार्यकारी",
    "पोस्ट करने की तारीख",
    "कभी भी",
    "पिछले 24 घंटे",
    "पिछला सप्ताह",
    "पिछला महीना",
    "इसके अनुसार क्रमबद्ध करें",
    "आपकी कहानी से सबसे अच्छा मेल",
    "सबसे नए",
    "सबसे कम प्रमाण-अंतर",
    "फ़िल्टर हटाएँ",
    "सक्रिय फ़िल्टर",
    "तारीख वाला फ़िल्टर केवल प्रकाशन तारीख वाली वास्तविक नौकरियों पर लागू होता है।",
    "कोई मेल खाती भूमिका नहीं",
    "अपनी खोज का दायरा बढ़ाएँ या एक या अधिक फ़िल्टर हटाएँ।",
    "उदाहरण",
    "वास्तविक नौकरी",
  ),
  bn: defineRow(
    "পদ, দক্ষতা বা কোম্পানি খুঁজুন",
    "সব শিল্পখাত",
    "সব কাজের ধরন",
    "চাকরির ধরন",
    "সব চাকরির ধরন",
    "পূর্ণকালীন",
    "খণ্ডকালীন",
    "চুক্তিভিত্তিক",
    "ইন্টার্নশিপ",
    "অস্থায়ী",
    "অভিজ্ঞতার স্তর",
    "সব অভিজ্ঞতার স্তর",
    "প্রাথমিক স্তর",
    "মধ্যম স্তর",
    "সিনিয়র",
    "লিড / ম্যানেজার",
    "নির্বাহী",
    "প্রকাশের তারিখ",
    "যেকোনো সময়",
    "গত ২৪ ঘণ্টা",
    "গত সপ্তাহ",
    "গত মাস",
    "সাজান",
    "আপনার গল্পের সঙ্গে সেরা মিল",
    "সর্বশেষ",
    "সবচেয়ে কম প্রমাণের ঘাটতি",
    "ফিল্টার মুছুন",
    "সক্রিয় ফিল্টার",
    "তারিখের ফিল্টার কেবল প্রকাশের তারিখ থাকা বাস্তব চাকরিতে প্রযোজ্য।",
    "কোনো মিলযুক্ত পদ নেই",
    "অনুসন্ধান বিস্তৃত করুন বা এক বা একাধিক ফিল্টার মুছে দিন।",
    "উদাহরণ",
    "বাস্তব চাকরি",
  ),
  ur: defineRow(
    "عہدے، مہارتیں یا کمپنیاں تلاش کریں",
    "تمام صنعتیں",
    "کام کے تمام طریقے",
    "ملازمت کی قسم",
    "ملازمت کی تمام اقسام",
    "کل وقتی",
    "جز وقتی",
    "معاہدہ",
    "انٹرن شپ",
    "عارضی",
    "تجربے کی سطح",
    "تجربے کی تمام سطحیں",
    "ابتدائی سطح",
    "درمیانی سطح",
    "سینئر",
    "لیڈ / مینیجر",
    "اعلیٰ انتظامیہ",
    "اشتہار کی تاریخ",
    "کسی بھی وقت",
    "گزشتہ 24 گھنٹے",
    "گزشتہ ہفتہ",
    "گزشتہ مہینہ",
    "ترتیب دیں",
    "آپ کی کہانی سے بہترین مطابقت",
    "تازہ ترین",
    "ثبوت میں سب سے کم خلا",
    "فلٹر صاف کریں",
    "فعال فلٹرز",
    "تاریخ کا فلٹر صرف ان حقیقی آسامیوں پر لاگو ہوتا ہے جن کی اشاعت کی تاریخ موجود ہو۔",
    "کوئی موزوں آسامی نہیں ملی",
    "تلاش کا دائرہ بڑھائیں یا ایک یا زیادہ فلٹر صاف کریں۔",
    "مثال",
    "حقیقی آسامی",
  ),
  id: defineRow(
    "Cari posisi, keterampilan, atau perusahaan",
    "Semua industri",
    "Semua cara kerja",
    "Jenis pekerjaan",
    "Semua jenis pekerjaan",
    "Purnawaktu",
    "Paruh waktu",
    "Kontrak",
    "Magang",
    "Sementara",
    "Tingkat pengalaman",
    "Semua tingkat pengalaman",
    "Tingkat pemula",
    "Tingkat menengah",
    "Senior",
    "Pimpinan / Manajer",
    "Eksekutif",
    "Tanggal dipasang",
    "Kapan saja",
    "24 jam terakhir",
    "Minggu lalu",
    "Bulan lalu",
    "Urutkan berdasarkan",
    "Kecocokan terbaik dengan cerita Anda",
    "Terbaru",
    "Kesenjangan bukti paling sedikit",
    "Hapus filter",
    "Filter aktif",
    "Filter tanggal hanya berlaku untuk lowongan aktif yang memiliki tanggal publikasi.",
    "Tidak ada posisi yang cocok",
    "Perluas pencarian atau hapus satu atau beberapa filter.",
    "Contoh",
    "Lowongan aktif",
  ),
  ms: defineRow(
    "Cari jawatan, kemahiran atau syarikat",
    "Semua industri",
    "Semua cara kerja",
    "Jenis pekerjaan",
    "Semua jenis pekerjaan",
    "Sepenuh masa",
    "Separuh masa",
    "Kontrak",
    "Latihan industri",
    "Sementara",
    "Tahap pengalaman",
    "Semua tahap pengalaman",
    "Peringkat permulaan",
    "Peringkat pertengahan",
    "Senior",
    "Ketua / Pengurus",
    "Eksekutif",
    "Tarikh disiarkan",
    "Bila-bila masa",
    "24 jam lalu",
    "Minggu lalu",
    "Bulan lalu",
    "Isih mengikut",
    "Padanan terbaik dengan kisah anda",
    "Terbaharu",
    "Jurang bukti paling sedikit",
    "Kosongkan penapis",
    "Penapis aktif",
    "Penapis tarikh hanya digunakan untuk jawatan sebenar yang mempunyai tarikh siaran.",
    "Tiada jawatan yang sepadan",
    "Luaskan carian atau kosongkan satu atau beberapa penapis.",
    "Contoh",
    "Jawatan sebenar",
  ),
  th: defineRow(
    "ค้นหาตำแหน่ง ทักษะ หรือบริษัท",
    "ทุกอุตสาหกรรม",
    "รูปแบบการทำงานทั้งหมด",
    "ประเภทการจ้างงาน",
    "ประเภทการจ้างงานทั้งหมด",
    "เต็มเวลา",
    "พาร์ตไทม์",
    "สัญญาจ้าง",
    "ฝึกงาน",
    "ชั่วคราว",
    "ระดับประสบการณ์",
    "ทุกระดับประสบการณ์",
    "ระดับเริ่มต้น",
    "ระดับกลาง",
    "ระดับอาวุโส",
    "หัวหน้าทีม / ผู้จัดการ",
    "ผู้บริหาร",
    "วันที่ประกาศ",
    "ไม่จำกัดเวลา",
    "24 ชั่วโมงที่ผ่านมา",
    "สัปดาห์ที่ผ่านมา",
    "เดือนที่ผ่านมา",
    "เรียงตาม",
    "ตรงกับเรื่องราวของคุณมากที่สุด",
    "ใหม่ล่าสุด",
    "ช่องว่างของหลักฐานน้อยที่สุด",
    "ล้างตัวกรอง",
    "ตัวกรองที่ใช้อยู่",
    "ตัวกรองวันที่ใช้ได้เฉพาะงานจริงที่ระบุวันที่ประกาศเท่านั้น",
    "ไม่พบตำแหน่งที่ตรงกัน",
    "ลองขยายการค้นหาหรือล้างตัวกรองอย่างน้อยหนึ่งรายการ",
    "ตัวอย่าง",
    "งานจริง",
  ),
  vi: defineRow(
    "Tìm vị trí, kỹ năng hoặc công ty",
    "Tất cả ngành nghề",
    "Tất cả hình thức làm việc",
    "Loại hình việc làm",
    "Tất cả loại hình việc làm",
    "Toàn thời gian",
    "Bán thời gian",
    "Hợp đồng",
    "Thực tập",
    "Tạm thời",
    "Cấp độ kinh nghiệm",
    "Tất cả cấp độ kinh nghiệm",
    "Mới vào nghề",
    "Trung cấp",
    "Cao cấp",
    "Trưởng nhóm / Quản lý",
    "Điều hành",
    "Ngày đăng",
    "Bất kỳ thời điểm nào",
    "24 giờ qua",
    "Tuần qua",
    "Tháng qua",
    "Sắp xếp theo",
    "Phù hợp nhất với câu chuyện của bạn",
    "Mới nhất",
    "Ít khoảng trống bằng chứng nhất",
    "Xóa bộ lọc",
    "Bộ lọc đang áp dụng",
    "Bộ lọc ngày chỉ áp dụng cho tin tuyển dụng thực có ngày đăng.",
    "Không có vị trí phù hợp",
    "Hãy mở rộng tìm kiếm hoặc xóa một hay nhiều bộ lọc.",
    "Ví dụ",
    "Tin tuyển dụng thực",
  ),
  fil: defineRow(
    "Maghanap ng tungkulin, kasanayan, o kumpanya",
    "Lahat ng industriya",
    "Lahat ng paraan ng pagtatrabaho",
    "Uri ng trabaho",
    "Lahat ng uri ng trabaho",
    "Full-time",
    "Part-time",
    "Kontrata",
    "Internship",
    "Pansamantala",
    "Antas ng karanasan",
    "Lahat ng antas ng karanasan",
    "Entry level",
    "Mid-level",
    "Senior",
    "Lead / Manager",
    "Ehekutibo",
    "Petsa ng pag-post",
    "Anumang oras",
    "Nakaraang 24 oras",
    "Nakaraang linggo",
    "Nakaraang buwan",
    "Ayusin ayon sa",
    "Pinakamahusay na tugma sa kuwento mo",
    "Pinakabago",
    "Pinakakaunting puwang sa ebidensya",
    "I-clear ang mga filter",
    "Mga aktibong filter",
    "Nalalapat lang ang filter ng petsa sa mga aktuwal na trabahong may petsa ng pag-post.",
    "Walang tugmang tungkulin",
    "Palawakin ang paghahanap o i-clear ang isa o higit pang filter.",
    "Halimbawa",
    "Aktuwal na trabaho",
  ),
  sv: defineRow(
    "Sök efter roller, kompetenser eller företag",
    "Alla branscher",
    "Alla arbetsformer",
    "Anställningsform",
    "Alla anställningsformer",
    "Heltid",
    "Deltid",
    "Kontrakt",
    "Praktik",
    "Tillfällig anställning",
    "Erfarenhetsnivå",
    "Alla erfarenhetsnivåer",
    "Ingångsnivå",
    "Mellannivå",
    "Senior",
    "Teamledare / Chef",
    "Företagsledning",
    "Publiceringsdatum",
    "När som helst",
    "Senaste 24 timmarna",
    "Senaste veckan",
    "Senaste månaden",
    "Sortera efter",
    "Bästa matchning mot din berättelse",
    "Nyast",
    "Minst antal bevisluckor",
    "Rensa filter",
    "Aktiva filter",
    "Datumfiltret gäller endast aktuella jobb med ett publiceringsdatum.",
    "Inga matchande roller",
    "Bredda sökningen eller rensa ett eller flera filter.",
    "Exempel",
    "Aktuellt jobb",
  ),
  no: defineRow(
    "Søk etter roller, ferdigheter eller selskaper",
    "Alle bransjer",
    "Alle arbeidsformer",
    "Ansettelsesform",
    "Alle ansettelsesformer",
    "Heltid",
    "Deltid",
    "Kontrakt",
    "Praksis",
    "Midlertidig",
    "Erfaringsnivå",
    "Alle erfaringsnivåer",
    "Inngangsnivå",
    "Mellomnivå",
    "Senior",
    "Fagleder / Leder",
    "Toppledelse",
    "Publiseringsdato",
    "Når som helst",
    "Siste 24 timer",
    "Siste uke",
    "Siste måned",
    "Sorter etter",
    "Beste samsvar med historien din",
    "Nyeste",
    "Færrest dokumentasjonshull",
    "Tøm filtre",
    "Aktive filtre",
    "Datofilteret gjelder bare aktive stillinger med publiseringsdato.",
    "Ingen roller samsvarer",
    "Utvid søket eller fjern ett eller flere filtre.",
    "Eksempel",
    "Aktiv stilling",
  ),
  da: defineRow(
    "Søg efter roller, kompetencer eller virksomheder",
    "Alle brancher",
    "Alle arbejdsformer",
    "Ansættelsesform",
    "Alle ansættelsesformer",
    "Fuldtid",
    "Deltid",
    "Kontrakt",
    "Praktik",
    "Midlertidig",
    "Erfaringsniveau",
    "Alle erfaringsniveauer",
    "Begynderniveau",
    "Mellemniveau",
    "Senior",
    "Teamleder / Leder",
    "Direktion",
    "Opslagsdato",
    "Når som helst",
    "Seneste 24 timer",
    "Seneste uge",
    "Seneste måned",
    "Sortér efter",
    "Bedste match med din historie",
    "Nyeste",
    "Færrest dokumentationshuller",
    "Ryd filtre",
    "Aktive filtre",
    "Datofilteret gælder kun aktive stillinger med en opslagsdato.",
    "Ingen matchende roller",
    "Udvid søgningen, eller ryd et eller flere filtre.",
    "Eksempel",
    "Aktiv stilling",
  ),
  fi: defineRow(
    "Hae tehtäviä, taitoja tai yrityksiä",
    "Kaikki toimialat",
    "Kaikki työskentelytavat",
    "Työsuhteen tyyppi",
    "Kaikki työsuhdetyypit",
    "Kokoaikainen",
    "Osa-aikainen",
    "Sopimustyö",
    "Harjoittelu",
    "Määräaikainen",
    "Kokemustaso",
    "Kaikki kokemustasot",
    "Aloitustaso",
    "Keskitaso",
    "Senior",
    "Tiiminvetäjä / Esihenkilö",
    "Johtotaso",
    "Julkaisupäivä",
    "Milloin tahansa",
    "Viimeiset 24 tuntia",
    "Viimeinen viikko",
    "Viimeinen kuukausi",
    "Lajittele",
    "Paras vastaavuus tarinaasi",
    "Uusimmat",
    "Vähiten näyttöaukkoja",
    "Tyhjennä suodattimet",
    "Aktiiviset suodattimet",
    "Päivämääräsuodatin koskee vain ajankohtaisia työpaikkoja, joilla on julkaisupäivä.",
    "Vastaavia tehtäviä ei löytynyt",
    "Laajenna hakua tai tyhjennä yksi tai useampi suodatin.",
    "Esimerkki",
    "Ajankohtainen työpaikka",
  ),
  cs: defineRow(
    "Hledat pozice, dovednosti nebo firmy",
    "Všechna odvětví",
    "Všechny režimy práce",
    "Typ úvazku",
    "Všechny typy úvazku",
    "Plný úvazek",
    "Částečný úvazek",
    "Smlouva",
    "Stáž",
    "Dočasná práce",
    "Úroveň zkušeností",
    "Všechny úrovně zkušeností",
    "Nástupní úroveň",
    "Středně pokročilý",
    "Senior",
    "Vedoucí / Manažer",
    "Vrcholové vedení",
    "Datum zveřejnění",
    "Kdykoli",
    "Posledních 24 hodin",
    "Poslední týden",
    "Poslední měsíc",
    "Seřadit podle",
    "Nejlepší shody s vaším příběhem",
    "Nejnovější",
    "Nejméně mezer v důkazech",
    "Vymazat filtry",
    "Aktivní filtry",
    "Filtr data platí pouze pro aktuální nabídky s datem zveřejnění.",
    "Žádné odpovídající pozice",
    "Rozšiřte hledání nebo vymažte jeden či více filtrů.",
    "Příklad",
    "Aktuální nabídka",
  ),
  sk: defineRow(
    "Hľadať pozície, zručnosti alebo firmy",
    "Všetky odvetvia",
    "Všetky režimy práce",
    "Typ pracovného pomeru",
    "Všetky typy pracovného pomeru",
    "Plný úväzok",
    "Čiastočný úväzok",
    "Zmluva",
    "Stáž",
    "Dočasná práca",
    "Úroveň skúseností",
    "Všetky úrovne skúseností",
    "Začiatočník",
    "Stredne pokročilý",
    "Senior",
    "Vedúci / Manažér",
    "Vrcholový manažment",
    "Dátum zverejnenia",
    "Kedykoľvek",
    "Posledných 24 hodín",
    "Posledný týždeň",
    "Posledný mesiac",
    "Zoradiť podľa",
    "Najlepšej zhody s vaším príbehom",
    "Najnovšie",
    "Najmenej medzier v dôkazoch",
    "Vymazať filtre",
    "Aktívne filtre",
    "Filter dátumu platí len pre aktuálne ponuky s dátumom zverejnenia.",
    "Žiadne zodpovedajúce pozície",
    "Rozšírte hľadanie alebo vymažte jeden či viac filtrov.",
    "Príklad",
    "Aktuálna ponuka",
  ),
  hu: defineRow(
    "Keresés pozíciók, készségek vagy cégek szerint",
    "Minden iparág",
    "Minden munkavégzési mód",
    "Foglalkoztatás típusa",
    "Minden foglalkoztatási típus",
    "Teljes munkaidő",
    "Részmunkaidő",
    "Szerződéses",
    "Gyakornoki",
    "Ideiglenes",
    "Tapasztalati szint",
    "Minden tapasztalati szint",
    "Pályakezdő",
    "Középhaladó",
    "Senior",
    "Csoportvezető / Menedzser",
    "Felsővezető",
    "Közzététel dátuma",
    "Bármikor",
    "Az elmúlt 24 órában",
    "Az elmúlt héten",
    "Az elmúlt hónapban",
    "Rendezés",
    "A történetéhez legjobban illeszkedő",
    "Legújabb",
    "Legkevesebb bizonyítékhiány",
    "Szűrők törlése",
    "Aktív szűrők",
    "A dátumszűrő csak a közzétételi dátummal rendelkező aktuális állásokra vonatkozik.",
    "Nincs megfelelő pozíció",
    "Bővítse a keresést, vagy töröljön egy vagy több szűrőt.",
    "Példa",
    "Aktuális állás",
  ),
  ro: defineRow(
    "Caută roluri, competențe sau companii",
    "Toate industriile",
    "Toate modurile de lucru",
    "Tipul contractului",
    "Toate tipurile de contract",
    "Normă întreagă",
    "Part-time",
    "Contract",
    "Stagiu",
    "Temporar",
    "Nivel de experiență",
    "Toate nivelurile de experiență",
    "Nivel începător",
    "Nivel intermediar",
    "Senior",
    "Coordonator / Manager",
    "Executiv",
    "Data publicării",
    "Oricând",
    "Ultimele 24 de ore",
    "Ultima săptămână",
    "Ultima lună",
    "Sortează după",
    "Cea mai bună potrivire cu povestea ta",
    "Cele mai noi",
    "Cele mai puține lacune în dovezi",
    "Șterge filtrele",
    "Filtre active",
    "Filtrul de dată se aplică doar joburilor active care au o dată de publicare.",
    "Nu există roluri potrivite",
    "Extinde căutarea sau șterge unul ori mai multe filtre.",
    "Exemplu",
    "Job activ",
  ),
  el: defineRow(
    "Αναζήτηση ρόλων, δεξιοτήτων ή εταιρειών",
    "Όλοι οι κλάδοι",
    "Όλοι οι τρόποι εργασίας",
    "Τύπος απασχόλησης",
    "Όλοι οι τύποι απασχόλησης",
    "Πλήρης απασχόληση",
    "Μερική απασχόληση",
    "Σύμβαση",
    "Πρακτική άσκηση",
    "Προσωρινή εργασία",
    "Επίπεδο εμπειρίας",
    "Όλα τα επίπεδα εμπειρίας",
    "Εισαγωγικό επίπεδο",
    "Μεσαίο επίπεδο",
    "Ανώτερο επίπεδο",
    "Επικεφαλής / Διευθυντής",
    "Ανώτατη διοίκηση",
    "Ημερομηνία δημοσίευσης",
    "Οποτεδήποτε",
    "Τελευταίες 24 ώρες",
    "Τελευταία εβδομάδα",
    "Τελευταίος μήνας",
    "Ταξινόμηση κατά",
    "Καλύτερη αντιστοίχιση με την ιστορία σας",
    "Νεότερα",
    "Λιγότερα κενά τεκμηρίωσης",
    "Εκκαθάριση φίλτρων",
    "Ενεργά φίλτρα",
    "Το φίλτρο ημερομηνίας ισχύει μόνο για ενεργές θέσεις με ημερομηνία δημοσίευσης.",
    "Δεν υπάρχουν θέσεις που να ταιριάζουν",
    "Διευρύνετε την αναζήτηση ή καταργήστε ένα ή περισσότερα φίλτρα.",
    "Παράδειγμα",
    "Ενεργή θέση",
  ),
  bg: defineRow(
    "Търсене на роли, умения или компании",
    "Всички отрасли",
    "Всички режими на работа",
    "Вид заетост",
    "Всички видове заетост",
    "Пълно работно време",
    "Непълно работно време",
    "Договор",
    "Стаж",
    "Временна работа",
    "Ниво на опит",
    "Всички нива на опит",
    "Начално ниво",
    "Средно ниво",
    "Старши специалист",
    "Ръководител / Мениджър",
    "Висше ръководство",
    "Дата на публикуване",
    "По всяко време",
    "Последните 24 часа",
    "Последната седмица",
    "Последния месец",
    "Сортиране по",
    "Най-добро съответствие с вашата история",
    "Най-нови",
    "Най-малко пропуски в доказателствата",
    "Изчистване на филтрите",
    "Активни филтри",
    "Филтърът по дата важи само за актуални обяви с дата на публикуване.",
    "Няма съвпадащи позиции",
    "Разширете търсенето или изчистете един или повече филтри.",
    "Пример",
    "Актуална обява",
  ),
  hr: defineRow(
    "Pretražite uloge, vještine ili tvrtke",
    "Sve industrije",
    "Svi načini rada",
    "Vrsta zaposlenja",
    "Sve vrste zaposlenja",
    "Puno radno vrijeme",
    "Nepuno radno vrijeme",
    "Ugovor",
    "Praksa",
    "Privremeno",
    "Razina iskustva",
    "Sve razine iskustva",
    "Početna razina",
    "Srednja razina",
    "Viša razina",
    "Voditelj / Menadžer",
    "Izvršna razina",
    "Datum objave",
    "Bilo kada",
    "Posljednja 24 sata",
    "Posljednji tjedan",
    "Posljednji mjesec",
    "Poredaj prema",
    "Najboljem podudaranju s vašom pričom",
    "Najnovije",
    "Najmanjem broju praznina u dokazima",
    "Očisti filtre",
    "Aktivni filtri",
    "Filtar datuma primjenjuje se samo na aktualne oglase s datumom objave.",
    "Nema odgovarajućih uloga",
    "Proširite pretragu ili očistite jedan ili više filtara.",
    "Primjer",
    "Aktualni oglas",
  ),
  sr: defineRow(
    "Претражите улоге, вештине или компаније",
    "Све индустрије",
    "Сви начини рада",
    "Врста запослења",
    "Све врсте запослења",
    "Пуно радно време",
    "Непуно радно време",
    "Уговор",
    "Пракса",
    "Привремено",
    "Ниво искуства",
    "Сви нивои искуства",
    "Почетни ниво",
    "Средњи ниво",
    "Сениор",
    "Вођа / Менаџер",
    "Извршни ниво",
    "Датум објаве",
    "Било када",
    "Последња 24 сата",
    "Последња недеља",
    "Последњи месец",
    "Сортирај према",
    "Најбољем подударању са вашом причом",
    "Најновије",
    "Најмањем броју празнина у доказима",
    "Обриши филтере",
    "Активни филтери",
    "Филтер датума важи само за актуелне огласе са датумом објаве.",
    "Нема одговарајућих улога",
    "Проширите претрагу или обришите један или више филтера.",
    "Пример",
    "Актуелни оглас",
  ),
  sl: defineRow(
    "Iščite vloge, znanja ali podjetja",
    "Vse panoge",
    "Vsi načini dela",
    "Vrsta zaposlitve",
    "Vse vrste zaposlitve",
    "Polni delovni čas",
    "Krajši delovni čas",
    "Pogodbeno delo",
    "Pripravništvo",
    "Začasno delo",
    "Raven izkušenj",
    "Vse ravni izkušenj",
    "Začetna raven",
    "Srednja raven",
    "Višja raven",
    "Vodja / Menedžer",
    "Izvršna raven",
    "Datum objave",
    "Kadar koli",
    "Zadnjih 24 ur",
    "Zadnji teden",
    "Zadnji mesec",
    "Razvrsti po",
    "Najboljšem ujemanju z vašo zgodbo",
    "Najnovejše",
    "Najmanj vrzelih v dokazih",
    "Počisti filtre",
    "Aktivni filtri",
    "Filter datuma velja samo za aktualne zaposlitve z datumom objave.",
    "Ni ujemajočih se vlog",
    "Razširite iskanje ali počistite enega ali več filtrov.",
    "Primer",
    "Aktualna zaposlitev",
  ),
  sw: defineRow(
    "Tafuta nafasi, ujuzi au kampuni",
    "Sekta zote",
    "Mitindo yote ya kazi",
    "Aina ya ajira",
    "Aina zote za ajira",
    "Muda wote",
    "Muda mfupi",
    "Mkataba",
    "Mafunzo kwa vitendo",
    "Ajira ya muda",
    "Kiwango cha uzoefu",
    "Viwango vyote vya uzoefu",
    "Kiwango cha kuanzia",
    "Kiwango cha kati",
    "Mwandamizi",
    "Kiongozi / Meneja",
    "Mtendaji mkuu",
    "Tarehe ya kuchapishwa",
    "Wakati wowote",
    "Saa 24 zilizopita",
    "Wiki iliyopita",
    "Mwezi uliopita",
    "Panga kwa",
    "Ulinganifu bora na hadithi yako",
    "Mpya zaidi",
    "Mapengo machache zaidi ya ushahidi",
    "Ondoa vichujio",
    "Vichujio vinavyotumika",
    "Kichujio cha tarehe kinatumika tu kwa nafasi halisi zenye tarehe ya kuchapishwa.",
    "Hakuna nafasi zinazolingana",
    "Panua utafutaji au ondoa kichujio kimoja au zaidi.",
    "Mfano",
    "Nafasi halisi",
  ),
  fa: defineRow(
    "جست‌وجوی موقعیت، مهارت یا شرکت",
    "همهٔ صنایع",
    "همهٔ شیوه‌های کاری",
    "نوع استخدام",
    "همهٔ انواع استخدام",
    "تمام‌وقت",
    "پاره‌وقت",
    "قراردادی",
    "کارآموزی",
    "موقت",
    "سطح تجربه",
    "همهٔ سطوح تجربه",
    "سطح ورودی",
    "سطح میانی",
    "ارشد",
    "سرپرست / مدیر",
    "مدیریت اجرایی",
    "تاریخ انتشار",
    "هر زمانی",
    "۲۴ ساعت گذشته",
    "هفتهٔ گذشته",
    "ماه گذشته",
    "مرتب‌سازی بر اساس",
    "بهترین تطابق با داستان شما",
    "جدیدترین",
    "کمترین شکاف در شواهد",
    "پاک‌کردن فیلترها",
    "فیلترهای فعال",
    "فیلتر تاریخ فقط برای موقعیت‌های واقعی دارای تاریخ انتشار اعمال می‌شود.",
    "هیچ موقعیت مطابقی پیدا نشد",
    "دامنهٔ جست‌وجو را گسترده‌تر کنید یا یک یا چند فیلتر را پاک کنید.",
    "نمونه",
    "موقعیت واقعی",
  ),
} satisfies Record<LocaleCode, readonly string[]>;

function copyFromRow(row: readonly string[]): JobSearchCopy {
  return Object.freeze(
    Object.fromEntries(
      JOB_SEARCH_COPY_KEYS.map((key, index) => [key, row[index]]),
    ) as Record<JobSearchCopyKey, string>,
  );
}

export const JOB_SEARCH_COPY_BY_LOCALE = Object.freeze(
  Object.fromEntries(
    (Object.entries(JOB_SEARCH_COPY_ROWS) as [LocaleCode, readonly string[]][]).map(
      ([locale, row]) => [locale, copyFromRow(row)],
    ),
  ) as Record<LocaleCode, JobSearchCopy>,
);

export function jobSearchCopyFor(locale: LocaleCode): JobSearchCopy {
  return JOB_SEARCH_COPY_BY_LOCALE[locale];
}

export const JOB_SEARCH_EXTRA_INDUSTRY_KEYS = [
  "Education",
  "Government & public sector",
  "Media & communications",
  "Manufacturing",
  "Retail & e-commerce",
  "Nonprofit & social impact",
  "Other",
] as const;

export type JobSearchExtraIndustry =
  (typeof JOB_SEARCH_EXTRA_INDUSTRY_KEYS)[number];

function defineIndustryRow<const T extends readonly string[]>(
  ...values: T & {
    readonly length: typeof JOB_SEARCH_EXTRA_INDUSTRY_KEYS.length;
  }
): T {
  return values;
}

const ALL_COUNTRIES_LABELS = {
  en: "All countries",
  ja: "すべての国",
  ko: "모든 국가",
  "zh-CN": "所有国家和地区",
  "zh-TW": "所有國家與地區",
  es: "Todos los países",
  fr: "Tous les pays",
  de: "Alle Länder",
  "pt-BR": "Todos os países",
  it: "Tutti i Paesi",
  nl: "Alle landen",
  pl: "Wszystkie kraje",
  tr: "Tüm ülkeler",
  ru: "Все страны",
  uk: "Усі країни",
  ar: "جميع البلدان",
  he: "כל המדינות",
  hi: "सभी देश",
  bn: "সব দেশ",
  ur: "تمام ممالک",
  id: "Semua negara",
  ms: "Semua negara",
  th: "ทุกประเทศ",
  vi: "Tất cả quốc gia",
  fil: "Lahat ng bansa",
  sv: "Alla länder",
  no: "Alle land",
  da: "Alle lande",
  fi: "Kaikki maat",
  cs: "Všechny země",
  sk: "Všetky krajiny",
  hu: "Minden ország",
  ro: "Toate țările",
  el: "Όλες οι χώρες",
  bg: "Всички държави",
  hr: "Sve države",
  sr: "Све земље",
  sl: "Vse države",
  sw: "Nchi zote",
  fa: "همهٔ کشورها",
} satisfies Record<LocaleCode, string>;

const JOB_SEARCH_EXTRA_INDUSTRY_ROWS = {
  en: defineIndustryRow(
    "Education",
    "Government & public sector",
    "Media & communications",
    "Manufacturing",
    "Retail & e-commerce",
    "Nonprofit & social impact",
    "Other",
  ),
  ja: defineIndustryRow(
    "教育",
    "政府・公共部門",
    "メディア・通信",
    "製造業",
    "小売・Eコマース",
    "非営利・社会的インパクト",
    "その他",
  ),
  ko: defineIndustryRow(
    "교육",
    "정부 및 공공 부문",
    "미디어 및 커뮤니케이션",
    "제조업",
    "소매 및 전자상거래",
    "비영리 및 사회적 가치",
    "기타",
  ),
  "zh-CN": defineIndustryRow(
    "教育",
    "政府与公共部门",
    "媒体与传播",
    "制造业",
    "零售与电子商务",
    "非营利与社会影响",
    "其他",
  ),
  "zh-TW": defineIndustryRow(
    "教育",
    "政府與公共部門",
    "媒體與傳播",
    "製造業",
    "零售與電子商務",
    "非營利與社會影響",
    "其他",
  ),
  es: defineIndustryRow(
    "Educación",
    "Gobierno y sector público",
    "Medios y comunicaciones",
    "Manufactura",
    "Comercio minorista y electrónico",
    "Organizaciones sin fines de lucro e impacto social",
    "Otros",
  ),
  fr: defineIndustryRow(
    "Éducation",
    "Administration et secteur public",
    "Médias et communication",
    "Industrie manufacturière",
    "Commerce de détail et e-commerce",
    "Secteur associatif et impact social",
    "Autre",
  ),
  de: defineIndustryRow(
    "Bildung",
    "Regierung und öffentlicher Sektor",
    "Medien und Kommunikation",
    "Fertigung",
    "Einzelhandel und E-Commerce",
    "Gemeinnütziger Sektor und soziale Wirkung",
    "Sonstige",
  ),
  "pt-BR": defineIndustryRow(
    "Educação",
    "Governo e setor público",
    "Mídia e comunicação",
    "Indústria",
    "Varejo e comércio eletrônico",
    "Terceiro setor e impacto social",
    "Outros",
  ),
  it: defineIndustryRow(
    "Istruzione",
    "Governo e settore pubblico",
    "Media e comunicazione",
    "Produzione industriale",
    "Commercio al dettaglio ed e-commerce",
    "Non profit e impatto sociale",
    "Altro",
  ),
  nl: defineIndustryRow(
    "Onderwijs",
    "Overheid en publieke sector",
    "Media en communicatie",
    "Productie",
    "Detailhandel en e-commerce",
    "Non-profit en maatschappelijke impact",
    "Overig",
  ),
  pl: defineIndustryRow(
    "Edukacja",
    "Administracja i sektor publiczny",
    "Media i komunikacja",
    "Produkcja",
    "Handel detaliczny i e-commerce",
    "Organizacje non-profit i wpływ społeczny",
    "Inne",
  ),
  tr: defineIndustryRow(
    "Eğitim",
    "Kamu ve devlet",
    "Medya ve iletişim",
    "Üretim",
    "Perakende ve e-ticaret",
    "Kâr amacı gütmeyen kuruluşlar ve sosyal etki",
    "Diğer",
  ),
  ru: defineIndustryRow(
    "Образование",
    "Государственный и общественный сектор",
    "СМИ и коммуникации",
    "Производство",
    "Розничная торговля и электронная коммерция",
    "Некоммерческий сектор и социальное влияние",
    "Другое",
  ),
  uk: defineIndustryRow(
    "Освіта",
    "Уряд і державний сектор",
    "Медіа та комунікації",
    "Виробництво",
    "Роздрібна торгівля та електронна комерція",
    "Некомерційний сектор і соціальний вплив",
    "Інше",
  ),
  ar: defineIndustryRow(
    "التعليم",
    "الحكومة والقطاع العام",
    "الإعلام والاتصالات",
    "التصنيع",
    "البيع بالتجزئة والتجارة الإلكترونية",
    "القطاع غير الربحي والأثر الاجتماعي",
    "أخرى",
  ),
  he: defineIndustryRow(
    "חינוך",
    "ממשל והמגזר הציבורי",
    "מדיה ותקשורת",
    "ייצור",
    "קמעונאות ומסחר אלקטרוני",
    "ארגונים ללא כוונת רווח והשפעה חברתית",
    "אחר",
  ),
  hi: defineIndustryRow(
    "शिक्षा",
    "सरकार और सार्वजनिक क्षेत्र",
    "मीडिया और संचार",
    "विनिर्माण",
    "खुदरा और ई-कॉमर्स",
    "गैर-लाभकारी और सामाजिक प्रभाव",
    "अन्य",
  ),
  bn: defineIndustryRow(
    "শিক্ষা",
    "সরকার ও সরকারি খাত",
    "গণমাধ্যম ও যোগাযোগ",
    "উৎপাদন",
    "খুচরা বিক্রয় ও ই-কমার্স",
    "অলাভজনক ও সামাজিক প্রভাব",
    "অন্যান্য",
  ),
  ur: defineIndustryRow(
    "تعلیم",
    "حکومت اور سرکاری شعبہ",
    "میڈیا اور مواصلات",
    "مینوفیکچرنگ",
    "ریٹیل اور ای کامرس",
    "غیر منافع بخش اور سماجی اثرات",
    "دیگر",
  ),
  id: defineIndustryRow(
    "Pendidikan",
    "Pemerintah dan sektor publik",
    "Media dan komunikasi",
    "Manufaktur",
    "Ritel dan e-commerce",
    "Nirlaba dan dampak sosial",
    "Lainnya",
  ),
  ms: defineIndustryRow(
    "Pendidikan",
    "Kerajaan dan sektor awam",
    "Media dan komunikasi",
    "Pembuatan",
    "Peruncitan dan e-dagang",
    "Bukan untung dan impak sosial",
    "Lain-lain",
  ),
  th: defineIndustryRow(
    "การศึกษา",
    "ภาครัฐและภาคสาธารณะ",
    "สื่อและการสื่อสาร",
    "การผลิต",
    "ค้าปลีกและอีคอมเมิร์ซ",
    "องค์กรไม่แสวงหากำไรและผลกระทบทางสังคม",
    "อื่น ๆ",
  ),
  vi: defineIndustryRow(
    "Giáo dục",
    "Chính phủ và khu vực công",
    "Truyền thông và báo chí",
    "Sản xuất",
    "Bán lẻ và thương mại điện tử",
    "Phi lợi nhuận và tác động xã hội",
    "Khác",
  ),
  fil: defineIndustryRow(
    "Edukasyon",
    "Pamahalaan at pampublikong sektor",
    "Media at komunikasyon",
    "Pagmamanupaktura",
    "Retail at e-commerce",
    "Nonprofit at panlipunang epekto",
    "Iba pa",
  ),
  sv: defineIndustryRow(
    "Utbildning",
    "Myndigheter och offentlig sektor",
    "Media och kommunikation",
    "Tillverkning",
    "Detaljhandel och e-handel",
    "Ideell sektor och social påverkan",
    "Övrigt",
  ),
  no: defineIndustryRow(
    "Utdanning",
    "Offentlig sektor",
    "Medier og kommunikasjon",
    "Produksjon",
    "Detaljhandel og netthandel",
    "Ideell sektor og sosial påvirkning",
    "Annet",
  ),
  da: defineIndustryRow(
    "Uddannelse",
    "Myndigheder og offentlig sektor",
    "Medier og kommunikation",
    "Produktion",
    "Detailhandel og e-handel",
    "Nonprofit og social effekt",
    "Andet",
  ),
  fi: defineIndustryRow(
    "Koulutus",
    "Hallinto ja julkinen sektori",
    "Media ja viestintä",
    "Valmistus",
    "Vähittäiskauppa ja verkkokauppa",
    "Voittoa tavoittelematon toiminta ja yhteiskunnallinen vaikuttavuus",
    "Muu",
  ),
  cs: defineIndustryRow(
    "Vzdělávání",
    "Státní správa a veřejný sektor",
    "Média a komunikace",
    "Výroba",
    "Maloobchod a e-commerce",
    "Neziskový sektor a společenský dopad",
    "Ostatní",
  ),
  sk: defineIndustryRow(
    "Vzdelávanie",
    "Štátna správa a verejný sektor",
    "Médiá a komunikácia",
    "Výroba",
    "Maloobchod a e-commerce",
    "Neziskový sektor a spoločenský vplyv",
    "Ostatné",
  ),
  hu: defineIndustryRow(
    "Oktatás",
    "Kormányzat és közszféra",
    "Média és kommunikáció",
    "Gyártás",
    "Kiskereskedelem és e-kereskedelem",
    "Nonprofit és társadalmi hatás",
    "Egyéb",
  ),
  ro: defineIndustryRow(
    "Educație",
    "Administrație și sector public",
    "Media și comunicații",
    "Producție",
    "Comerț cu amănuntul și comerț electronic",
    "Sector nonprofit și impact social",
    "Altele",
  ),
  el: defineIndustryRow(
    "Εκπαίδευση",
    "Κυβέρνηση και δημόσιος τομέας",
    "Μέσα ενημέρωσης και επικοινωνία",
    "Μεταποίηση",
    "Λιανικό εμπόριο και ηλεκτρονικό εμπόριο",
    "Μη κερδοσκοπικός τομέας και κοινωνικός αντίκτυπος",
    "Άλλο",
  ),
  bg: defineIndustryRow(
    "Образование",
    "Правителство и публичен сектор",
    "Медии и комуникации",
    "Производство",
    "Търговия на дребно и електронна търговия",
    "Нестопански сектор и социално въздействие",
    "Друго",
  ),
  hr: defineIndustryRow(
    "Obrazovanje",
    "Vlada i javni sektor",
    "Mediji i komunikacije",
    "Proizvodnja",
    "Maloprodaja i e-trgovina",
    "Neprofitni sektor i društveni utjecaj",
    "Ostalo",
  ),
  sr: defineIndustryRow(
    "Образовање",
    "Влада и јавни сектор",
    "Медији и комуникације",
    "Производња",
    "Малопродаја и е-трговина",
    "Непрофитни сектор и друштвени утицај",
    "Остало",
  ),
  sl: defineIndustryRow(
    "Izobraževanje",
    "Vlada in javni sektor",
    "Mediji in komunikacije",
    "Proizvodnja",
    "Maloprodaja in e-trgovina",
    "Neprofitni sektor in družbeni vpliv",
    "Drugo",
  ),
  sw: defineIndustryRow(
    "Elimu",
    "Serikali na sekta ya umma",
    "Vyombo vya habari na mawasiliano",
    "Utengenezaji",
    "Rejareja na biashara mtandaoni",
    "Mashirika yasiyo ya faida na athari za kijamii",
    "Nyingine",
  ),
  fa: defineIndustryRow(
    "آموزش",
    "دولت و بخش عمومی",
    "رسانه و ارتباطات",
    "تولید",
    "خرده‌فروشی و تجارت الکترونیک",
    "غیرانتفاعی و تأثیر اجتماعی",
    "سایر",
  ),
} satisfies Record<LocaleCode, readonly string[]>;

const JOB_SEARCH_EXTRA_INDUSTRY_CATALOGS = Object.fromEntries(
  (
    Object.entries(JOB_SEARCH_EXTRA_INDUSTRY_ROWS) as [
      LocaleCode,
      readonly string[],
    ][]
  ).map(([locale, values]) => [
    locale,
    Object.fromEntries(
      JOB_SEARCH_EXTRA_INDUSTRY_KEYS.map((key, index) => [key, values[index]]),
    ),
  ]),
) as Record<LocaleCode, Record<JobSearchExtraIndustry, string>>;

export function allCountriesLabelFor(locale: LocaleCode): string {
  return ALL_COUNTRIES_LABELS[locale];
}

export function jobIndustryLabelFor(
  locale: LocaleCode,
  value: string,
): string {
  if (value === "All industries") {
    return jobSearchCopyFor(locale).allIndustries;
  }

  const extraIndustry =
    JOB_SEARCH_EXTRA_INDUSTRY_CATALOGS[locale][
      value as JobSearchExtraIndustry
    ];
  if (extraIndustry) return extraIndustry;

  return marketValueFor(locale, value);
}
