import type { LocaleCode } from "./i18n.ts";

export type JobTrackingCopy = {
  eyebrow: string;
  title: string;
  intro: string;
  provider: string;
  reference: string;
  referencePlaceholder: string;
  add: string;
  adding: string;
  signIn: string;
  signInBody: string;
  sources: string;
  activeJobs: string;
  checked: string;
  nextCheck: string;
  everyFiveMinutes: string;
  noAutoApply: string;
  healthy: string;
  checking: string;
  delayed: string;
  newJobs: string;
  updated: string;
  removed: string;
  checkNow: string;
  remove: string;
  alerts: string;
  emailAlerts: string;
  browserAlerts: string;
  emailNotice: string;
  updatesAvailable: string;
  refreshed: string;
  empty: string;
  error: string;
  sourceLimit: string;
  recentActivity: string;
  noRecentActivity: string;
  jobsLimited: string;
};

const REFERENCE_PLACEHOLDER = "https://boards.greenhouse.io/company";

const COPY: Record<LocaleCode, JobTrackingCopy> = {
  en: {
    eyebrow: "Background job tracking",
    title: "Track official employer job boards",
    intro: "Follow companies through official Greenhouse, Lever, and Ashby APIs. Checks are scheduled about every 5 minutes, subject to provider availability. InterviewThread never applies for you.",
    provider: "Provider",
    reference: "Careers URL or board ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Track company",
    adding: "Connecting…",
    signIn: "Sign in to track companies",
    signInBody: "Sign in for background tracking, cross-device sync, and alerts. Guest mode still supports one-time previews.",
    sources: "companies",
    activeJobs: "active jobs",
    checked: "checked",
    nextCheck: "next check scheduled in about 5 minutes, subject to provider availability",
    everyFiveMinutes: "Scheduled about every 5 minutes · provider availability may vary",
    noAutoApply: "No automatic applications",
    healthy: "Healthy",
    checking: "Checking",
    delayed: "Delayed",
    newJobs: "New",
    updated: "Updated",
    removed: "Closed",
    checkNow: "Check now",
    remove: "Stop tracking",
    alerts: "New-job alerts for this company",
    emailAlerts: "Email new-job alerts",
    browserAlerts: "Browser alerts while this page is open",
    emailNotice: "Email is opt-in and goes only to the verified address from your sign-in account.",
    updatesAvailable: "job changes synchronized",
    refreshed: "Tracking data is up to date.",
    empty: "Add a company to start your private job feed.",
    error: "Job tracking is temporarily unavailable.",
    sourceLimit: "You can track up to 20 companies.",
    recentActivity: "Recent activity",
    noRecentActivity: "No recent job changes.",
    jobsLimited: "Only the newest jobs are shown. Narrow your filters to see more.",
  },
  ja: {
    eyebrow: "バックグラウンド求人追跡",
    title: "企業の公式求人を追跡",
    intro: "Greenhouse、Lever、Ashby の公式 API で複数社を追跡します。確認は約5分ごとの予定ですが、提供元の稼働状況により変わります。自動応募は行いません。",
    provider: "提供元",
    reference: "採用ページURLまたはボードID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "企業を追跡",
    adding: "接続中…",
    signIn: "ログインして企業を追跡",
    signInBody: "バックグラウンド追跡、端末間同期、通知にはログインが必要です。ゲストは一度だけプレビューできます。",
    sources: "社",
    activeJobs: "件の募集中求人",
    checked: "最終確認",
    nextCheck: "提供元の状況に応じて約5分後に確認予定",
    everyFiveMinutes: "約5分ごとに確認予定・提供元により変動",
    noAutoApply: "自動応募なし",
    healthy: "正常",
    checking: "確認中",
    delayed: "遅延",
    newJobs: "新着",
    updated: "更新",
    removed: "終了",
    checkNow: "今すぐ確認",
    remove: "追跡を停止",
    alerts: "この企業の新着求人通知",
    emailAlerts: "新着求人をメールで通知",
    browserAlerts: "このページを開いている間はブラウザ通知",
    emailNotice: "メール通知は任意で、ログイン時に確認済みのアドレスにのみ届きます。",
    updatesAvailable: "件の変更を同期",
    refreshed: "最新の追跡情報です。",
    empty: "企業を追加して非公開の求人フィードを始めましょう。",
    error: "求人追跡を一時的に利用できません。",
    sourceLimit: "最大20社まで追跡できます。",
    recentActivity: "最近の動き",
    noRecentActivity: "最近の求人変更はありません。",
    jobsLimited: "最新の求人のみ表示中です。絞り込みでさらに確認できます。",
  },
  ko: {
    eyebrow: "백그라운드 채용 추적",
    title: "기업 공식 채용 공고 추적",
    intro: "Greenhouse, Lever, Ashby 공식 API로 여러 회사를 추적합니다. 확인은 약 5분 간격으로 예약되며 제공처 상태에 따라 달라집니다. 자동 지원은 하지 않습니다.",
    provider: "제공처",
    reference: "채용 페이지 URL 또는 보드 ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "회사 추적",
    adding: "연결 중…",
    signIn: "로그인하여 회사 추적",
    signInBody: "백그라운드 추적, 기기 간 동기화, 알림에는 로그인이 필요합니다. 게스트는 1회 미리보기를 이용할 수 있습니다.",
    sources: "개 회사",
    activeJobs: "개 채용 중",
    checked: "마지막 확인",
    nextCheck: "제공처 상태에 따라 약 5분 후 확인 예정",
    everyFiveMinutes: "약 5분마다 예약 · 제공처 상태에 따라 변동",
    noAutoApply: "자동 지원 없음",
    healthy: "정상",
    checking: "확인 중",
    delayed: "지연",
    newJobs: "신규",
    updated: "변경",
    removed: "마감",
    checkNow: "지금 확인",
    remove: "추적 중지",
    alerts: "이 회사의 신규 채용 알림",
    emailAlerts: "신규 채용 이메일 알림",
    browserAlerts: "이 페이지가 열려 있을 때 브라우저 알림",
    emailNotice: "이메일 알림은 선택 사항이며 로그인 계정의 인증된 주소로만 전송됩니다.",
    updatesAvailable: "건의 채용 변경 동기화",
    refreshed: "추적 정보가 최신입니다.",
    empty: "회사를 추가해 비공개 채용 피드를 시작하세요.",
    error: "채용 추적을 일시적으로 사용할 수 없습니다.",
    sourceLimit: "최대 20개 회사를 추적할 수 있습니다.",
    recentActivity: "최근 활동",
    noRecentActivity: "최근 채용 변경이 없습니다.",
    jobsLimited: "최신 공고만 표시됩니다. 필터를 좁혀 더 확인하세요.",
  },
  "zh-CN": {
    eyebrow: "后台职位追踪",
    title: "追踪公司的官方职位",
    intro: "通过 Greenhouse、Lever 与 Ashby 官方 API 追踪多家公司。系统约每 5 分钟安排检查，实际时间取决于来源可用性，且不会自动投递。",
    provider: "来源平台",
    reference: "招聘页网址或看板 ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "追踪公司",
    adding: "连接中…",
    signIn: "登录后追踪公司",
    signInBody: "后台追踪、跨设备同步与通知需要登录；访客仍可单次预览。",
    sources: "家公司",
    activeJobs: "个有效职位",
    checked: "上次检查",
    nextCheck: "预计约 5 分钟后检查，视来源可用性而定",
    everyFiveMinutes: "约每 5 分钟安排检查 · 视来源可用性",
    noAutoApply: "不会自动投递",
    healthy: "正常",
    checking: "检查中",
    delayed: "延迟",
    newJobs: "新增",
    updated: "已更新",
    removed: "已关闭",
    checkNow: "立即检查",
    remove: "停止追踪",
    alerts: "此公司的新职位通知",
    emailAlerts: "邮件新职位通知",
    browserAlerts: "本页打开时显示浏览器通知",
    emailNotice: "邮件通知需主动开启，且只会发送到登录账户的已验证地址。",
    updatesAvailable: "条职位变更已同步",
    refreshed: "追踪数据已是最新状态。",
    empty: "添加公司后即可建立私密职位动态。",
    error: "职位追踪暂时不可用。",
    sourceLimit: "最多可追踪 20 家公司。",
    recentActivity: "近期动态",
    noRecentActivity: "近期没有职位变更。",
    jobsLimited: "仅显示最新职位。缩小筛选范围可查看更多。",
  },
  "zh-TW": {
    eyebrow: "背景職缺追蹤",
    title: "追蹤公司的官方職缺",
    intro: "透過 Greenhouse、Lever 與 Ashby 官方 API 追蹤多家公司。系統約每 5 分鐘排程檢查，實際時間視來源可用性而定，且不會自動投遞。",
    provider: "來源平台",
    reference: "公司職涯頁網址或看板 ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "追蹤公司",
    adding: "連線中…",
    signIn: "登入後追蹤公司",
    signInBody: "背景追蹤、跨裝置同步與通知需要登入；訪客仍可單次預覽。",
    sources: "家公司",
    activeJobs: "個有效職缺",
    checked: "上次檢查",
    nextCheck: "預計約 5 分鐘後檢查，視來源可用性而定",
    everyFiveMinutes: "約每 5 分鐘排程 · 視來源可用性",
    noAutoApply: "不會自動投遞",
    healthy: "正常",
    checking: "檢查中",
    delayed: "延遲",
    newJobs: "新增",
    updated: "已更新",
    removed: "已關閉",
    checkNow: "立即檢查",
    remove: "停止追蹤",
    alerts: "此公司的新職缺通知",
    emailAlerts: "Email 新職缺通知",
    browserAlerts: "本頁開啟時顯示瀏覽器通知",
    emailNotice: "Email 通知需主動開啟，且只會寄到登入帳號的已驗證地址。",
    updatesAvailable: "筆職缺變更已同步",
    refreshed: "追蹤資料已是最新狀態。",
    empty: "新增公司後，即可建立私密職缺動態。",
    error: "職缺追蹤暫時無法使用。",
    sourceLimit: "最多可追蹤 20 家公司。",
    recentActivity: "近期動態",
    noRecentActivity: "近期沒有職缺變更。",
    jobsLimited: "僅顯示最新職缺。縮小篩選範圍可查看更多。",
  },
  es: {
    eyebrow: "Seguimiento en segundo plano",
    title: "Sigue empleos oficiales de empresas",
    intro: "Sigue empresas mediante las API oficiales de Greenhouse, Lever y Ashby. Las revisiones se programan cada 5 minutos aproximadamente, según la disponibilidad del proveedor. Nunca solicitamos empleos por ti.",
    provider: "Proveedor",
    reference: "URL de empleo o ID del portal",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Seguir empresa",
    adding: "Conectando…",
    signIn: "Inicia sesión para seguir empresas",
    signInBody: "Inicia sesión para el seguimiento, la sincronización y las alertas. Como invitado puedes hacer una vista previa.",
    sources: "empresas",
    activeJobs: "vacantes activas",
    checked: "revisado",
    nextCheck: "revisión prevista en unos 5 minutos, según disponibilidad",
    everyFiveMinutes: "Programado cada 5 minutos aprox. · sujeto a disponibilidad",
    noAutoApply: "Sin solicitudes automáticas",
    healthy: "Activo",
    checking: "Revisando",
    delayed: "Con retraso",
    newJobs: "Nuevas",
    updated: "Actualizadas",
    removed: "Cerradas",
    checkNow: "Revisar ahora",
    remove: "Dejar de seguir",
    alerts: "Alertas de nuevas vacantes de esta empresa",
    emailAlerts: "Alertas por correo",
    browserAlerts: "Alertas del navegador con esta página abierta",
    emailNotice: "El correo es opcional y solo se envía a la dirección verificada de tu cuenta.",
    updatesAvailable: "cambios sincronizados",
    refreshed: "Los datos están actualizados.",
    empty: "Añade una empresa para crear tu feed privado.",
    error: "El seguimiento no está disponible temporalmente.",
    sourceLimit: "Puedes seguir hasta 20 empresas.",
    recentActivity: "Actividad reciente",
    noRecentActivity: "No hay cambios recientes.",
    jobsLimited: "Solo se muestran las vacantes más recientes. Ajusta los filtros para ver más.",
  },
  fr: {
    eyebrow: "Suivi des offres en arrière-plan",
    title: "Suivez les offres officielles des entreprises",
    intro: "Suivez des entreprises via les API officielles Greenhouse, Lever et Ashby. Les contrôles sont planifiés environ toutes les 5 minutes, selon la disponibilité du fournisseur. Aucune candidature automatique.",
    provider: "Fournisseur",
    reference: "URL carrières ou ID du portail",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Suivre l’entreprise",
    adding: "Connexion…",
    signIn: "Connectez-vous pour suivre des entreprises",
    signInBody: "Connectez-vous pour le suivi, la synchronisation et les alertes. Le mode invité permet un aperçu ponctuel.",
    sources: "entreprises",
    activeJobs: "offres actives",
    checked: "vérifié",
    nextCheck: "contrôle prévu dans environ 5 minutes, selon disponibilité",
    everyFiveMinutes: "Planifié environ toutes les 5 min · selon disponibilité",
    noAutoApply: "Aucune candidature automatique",
    healthy: "Opérationnel",
    checking: "Vérification",
    delayed: "Retard",
    newJobs: "Nouvelles",
    updated: "Modifiées",
    removed: "Clôturées",
    checkNow: "Vérifier",
    remove: "Arrêter le suivi",
    alerts: "Alertes des nouvelles offres de cette entreprise",
    emailAlerts: "Alertes par e-mail",
    browserAlerts: "Alertes du navigateur quand cette page est ouverte",
    emailNotice: "L’e-mail est facultatif et envoyé uniquement à l’adresse vérifiée du compte.",
    updatesAvailable: "changements synchronisés",
    refreshed: "Les données de suivi sont à jour.",
    empty: "Ajoutez une entreprise pour créer votre flux privé.",
    error: "Le suivi est temporairement indisponible.",
    sourceLimit: "Vous pouvez suivre jusqu’à 20 entreprises.",
    recentActivity: "Activité récente",
    noRecentActivity: "Aucun changement récent.",
    jobsLimited: "Seules les offres les plus récentes sont affichées. Affinez les filtres pour en voir plus.",
  },
  de: {
    eyebrow: "Stellen-Tracking im Hintergrund",
    title: "Offizielle Stellen von Unternehmen verfolgen",
    intro: "Verfolge Unternehmen über die offiziellen Greenhouse-, Lever- und Ashby-APIs. Prüfungen werden ungefähr alle 5 Minuten geplant, abhängig von der Verfügbarkeit des Anbieters. Keine automatische Bewerbung.",
    provider: "Anbieter",
    reference: "Karriere-URL oder Board-ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Unternehmen verfolgen",
    adding: "Verbindung…",
    signIn: "Zum Verfolgen anmelden",
    signInBody: "Melde dich für Hintergrund-Tracking, geräteübergreifende Synchronisierung und Benachrichtigungen an. Gäste können einmalig eine Vorschau öffnen.",
    sources: "Unternehmen",
    activeJobs: "aktive Stellen",
    checked: "geprüft",
    nextCheck: "Prüfung in etwa 5 Minuten geplant, je nach Verfügbarkeit",
    everyFiveMinutes: "Etwa alle 5 Min. geplant · abhängig vom Anbieter",
    noAutoApply: "Keine automatischen Bewerbungen",
    healthy: "Aktiv",
    checking: "Wird geprüft",
    delayed: "Verzögert",
    newJobs: "Neu",
    updated: "Geändert",
    removed: "Geschlossen",
    checkNow: "Jetzt prüfen",
    remove: "Nicht mehr verfolgen",
    alerts: "Neue Stellen dieses Unternehmens melden",
    emailAlerts: "Neue Stellen per E-Mail",
    browserAlerts: "Browser-Meldungen bei geöffneter Seite",
    emailNotice: "E-Mail ist optional und geht nur an die bestätigte Adresse deines Kontos.",
    updatesAvailable: "Stellenänderungen synchronisiert",
    refreshed: "Tracking-Daten sind aktuell.",
    empty: "Füge ein Unternehmen für deinen privaten Stellen-Feed hinzu.",
    error: "Stellen-Tracking ist vorübergehend nicht verfügbar.",
    sourceLimit: "Du kannst bis zu 20 Unternehmen verfolgen.",
    recentActivity: "Letzte Aktivitäten",
    noRecentActivity: "Keine aktuellen Stellenänderungen.",
    jobsLimited: "Nur die neuesten Stellen werden angezeigt. Mit Filtern siehst du mehr.",
  },
  "pt-BR": {
    eyebrow: "Rastreamento de vagas em segundo plano",
    title: "Acompanhe vagas oficiais das empresas",
    intro: "Acompanhe empresas pelas APIs oficiais do Greenhouse, Lever e Ashby. As verificações são agendadas a cada 5 minutos, aproximadamente, conforme a disponibilidade do provedor. Nunca nos candidatamos por você.",
    provider: "Provedor",
    reference: "URL de carreiras ou ID do painel",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Acompanhar empresa",
    adding: "Conectando…",
    signIn: "Entre para acompanhar empresas",
    signInBody: "Entre para usar rastreamento, sincronização entre dispositivos e alertas. Visitantes ainda podem fazer uma prévia única.",
    sources: "empresas",
    activeJobs: "vagas ativas",
    checked: "verificado",
    nextCheck: "verificação prevista em cerca de 5 minutos, conforme disponibilidade",
    everyFiveMinutes: "Agendado a cada 5 min., aproximadamente · sujeito à disponibilidade",
    noAutoApply: "Sem candidaturas automáticas",
    healthy: "Ativo",
    checking: "Verificando",
    delayed: "Atrasado",
    newJobs: "Novas",
    updated: "Atualizadas",
    removed: "Encerradas",
    checkNow: "Verificar agora",
    remove: "Parar de acompanhar",
    alerts: "Alertas de novas vagas desta empresa",
    emailAlerts: "Alertas de vagas por e-mail",
    browserAlerts: "Alertas no navegador com esta página aberta",
    emailNotice: "O e-mail é opcional e enviado apenas ao endereço verificado da sua conta.",
    updatesAvailable: "alterações sincronizadas",
    refreshed: "Os dados estão atualizados.",
    empty: "Adicione uma empresa para iniciar seu feed privado.",
    error: "O rastreamento está temporariamente indisponível.",
    sourceLimit: "Você pode acompanhar até 20 empresas.",
    recentActivity: "Atividade recente",
    noRecentActivity: "Nenhuma mudança recente.",
    jobsLimited: "Só as vagas mais recentes aparecem. Refine os filtros para ver mais.",
  },
  it: {
    eyebrow: "Monitoraggio offerte in background",
    title: "Segui le offerte ufficiali delle aziende",
    intro: "Segui le aziende tramite le API ufficiali di Greenhouse, Lever e Ashby. I controlli sono pianificati ogni 5 minuti circa, in base alla disponibilità del provider. Nessuna candidatura automatica.",
    provider: "Provider",
    reference: "URL carriere o ID bacheca",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Segui azienda",
    adding: "Connessione…",
    signIn: "Accedi per seguire le aziende",
    signInBody: "Accedi per monitoraggio, sincronizzazione e avvisi. Come ospite puoi ancora vedere un’anteprima singola.",
    sources: "aziende",
    activeJobs: "offerte attive",
    checked: "controllato",
    nextCheck: "controllo previsto tra circa 5 minuti, secondo disponibilità",
    everyFiveMinutes: "Pianificato ogni 5 min. circa · secondo disponibilità",
    noAutoApply: "Nessuna candidatura automatica",
    healthy: "Attivo",
    checking: "Controllo",
    delayed: "In ritardo",
    newJobs: "Nuove",
    updated: "Aggiornate",
    removed: "Chiuse",
    checkNow: "Controlla ora",
    remove: "Interrompi monitoraggio",
    alerts: "Avvisi per nuove offerte di questa azienda",
    emailAlerts: "Avvisi via e-mail",
    browserAlerts: "Avvisi del browser con questa pagina aperta",
    emailNotice: "L’e-mail è facoltativa e arriva solo all’indirizzo verificato del tuo account.",
    updatesAvailable: "modifiche sincronizzate",
    refreshed: "I dati sono aggiornati.",
    empty: "Aggiungi un’azienda per creare il tuo feed privato.",
    error: "Il monitoraggio non è temporaneamente disponibile.",
    sourceLimit: "Puoi seguire fino a 20 aziende.",
    recentActivity: "Attività recente",
    noRecentActivity: "Nessuna modifica recente.",
    jobsLimited: "Sono mostrate solo le offerte più recenti. Restringi i filtri per vederne altre.",
  },
  nl: {
    eyebrow: "Vacatures volgen op de achtergrond",
    title: "Volg officiële vacatures van werkgevers",
    intro: "Volg bedrijven via de officiële API’s van Greenhouse, Lever en Ashby. Controles worden ongeveer elke 5 minuten gepland, afhankelijk van beschikbaarheid. We solliciteren nooit voor je.",
    provider: "Aanbieder",
    reference: "Carrière-URL of board-ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Bedrijf volgen",
    adding: "Verbinden…",
    signIn: "Log in om bedrijven te volgen",
    signInBody: "Log in voor achtergrondtracking, synchronisatie en meldingen. Als gast kun je eenmalig een voorbeeld bekijken.",
    sources: "bedrijven",
    activeJobs: "actieve vacatures",
    checked: "gecontroleerd",
    nextCheck: "controle over ongeveer 5 minuten gepland, afhankelijk van beschikbaarheid",
    everyFiveMinutes: "Ongeveer elke 5 min. gepland · afhankelijk van beschikbaarheid",
    noAutoApply: "Geen automatische sollicitaties",
    healthy: "Actief",
    checking: "Controleren",
    delayed: "Vertraagd",
    newJobs: "Nieuw",
    updated: "Bijgewerkt",
    removed: "Gesloten",
    checkNow: "Nu controleren",
    remove: "Niet meer volgen",
    alerts: "Meldingen voor nieuwe vacatures bij dit bedrijf",
    emailAlerts: "Vacaturemeldingen per e-mail",
    browserAlerts: "Browsermeldingen zolang deze pagina open is",
    emailNotice: "E-mail is optioneel en gaat alleen naar het geverifieerde adres van je account.",
    updatesAvailable: "vacaturewijzigingen gesynchroniseerd",
    refreshed: "De trackinggegevens zijn actueel.",
    empty: "Voeg een bedrijf toe voor je privévacaturefeed.",
    error: "Vacaturetracking is tijdelijk niet beschikbaar.",
    sourceLimit: "Je kunt maximaal 20 bedrijven volgen.",
    recentActivity: "Recente activiteit",
    noRecentActivity: "Geen recente vacaturewijzigingen.",
    jobsLimited: "Alleen de nieuwste vacatures worden getoond. Verfijn de filters voor meer.",
  },
  pl: {
    eyebrow: "Śledzenie ofert w tle",
    title: "Śledź oficjalne oferty pracodawców",
    intro: "Śledź firmy przez oficjalne API Greenhouse, Lever i Ashby. Kontrole są planowane mniej więcej co 5 minut, zależnie od dostępności źródła. Nie aplikujemy za Ciebie.",
    provider: "Dostawca",
    reference: "Adres kariery lub ID tablicy",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Śledź firmę",
    adding: "Łączenie…",
    signIn: "Zaloguj się, aby śledzić firmy",
    signInBody: "Zaloguj się, aby korzystać ze śledzenia, synchronizacji i alertów. Gość może wykonać jednorazowy podgląd.",
    sources: "firmy",
    activeJobs: "aktywne oferty",
    checked: "sprawdzono",
    nextCheck: "kontrola za około 5 minut, zależnie od dostępności",
    everyFiveMinutes: "Planowane co ok. 5 min · zależnie od dostępności",
    noAutoApply: "Bez automatycznych aplikacji",
    healthy: "Aktywne",
    checking: "Sprawdzanie",
    delayed: "Opóźnione",
    newJobs: "Nowe",
    updated: "Zmienione",
    removed: "Zamknięte",
    checkNow: "Sprawdź teraz",
    remove: "Przestań śledzić",
    alerts: "Alerty o nowych ofertach tej firmy",
    emailAlerts: "Alerty e-mail o ofertach",
    browserAlerts: "Alerty przeglądarki przy otwartej stronie",
    emailNotice: "E-mail jest opcjonalny i trafia tylko na zweryfikowany adres konta.",
    updatesAvailable: "zmiany ofert zsynchronizowane",
    refreshed: "Dane śledzenia są aktualne.",
    empty: "Dodaj firmę, aby utworzyć prywatny kanał ofert.",
    error: "Śledzenie ofert jest chwilowo niedostępne.",
    sourceLimit: "Możesz śledzić maksymalnie 20 firm.",
    recentActivity: "Ostatnia aktywność",
    noRecentActivity: "Brak ostatnich zmian ofert.",
    jobsLimited: "Wyświetlamy tylko najnowsze oferty. Zawęź filtry, aby zobaczyć więcej.",
  },
  tr: {
    eyebrow: "Arka planda iş takibi",
    title: "Şirketlerin resmî ilanlarını takip edin",
    intro: "Şirketleri resmî Greenhouse, Lever ve Ashby API’leriyle takip edin. Kontroller, sağlayıcının erişilebilirliğine göre yaklaşık 5 dakikada bir planlanır. Sizin adınıza başvuru yapılmaz.",
    provider: "Sağlayıcı",
    reference: "Kariyer URL’si veya pano kimliği",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Şirketi takip et",
    adding: "Bağlanıyor…",
    signIn: "Şirketleri takip etmek için giriş yapın",
    signInBody: "Arka plan takibi, cihazlar arası eşitleme ve uyarılar için giriş yapın. Misafirler tek seferlik önizleme kullanabilir.",
    sources: "şirket",
    activeJobs: "aktif ilan",
    checked: "kontrol edildi",
    nextCheck: "erişilebilirliğe göre yaklaşık 5 dakika sonra planlandı",
    everyFiveMinutes: "Yaklaşık 5 dakikada bir planlanır · erişilebilirlik değişebilir",
    noAutoApply: "Otomatik başvuru yok",
    healthy: "Çalışıyor",
    checking: "Kontrol ediliyor",
    delayed: "Gecikmeli",
    newJobs: "Yeni",
    updated: "Güncellendi",
    removed: "Kapandı",
    checkNow: "Şimdi kontrol et",
    remove: "Takibi bırak",
    alerts: "Bu şirketin yeni iş ilanı uyarıları",
    emailAlerts: "E-posta iş uyarıları",
    browserAlerts: "Bu sayfa açıkken tarayıcı uyarıları",
    emailNotice: "E-posta isteğe bağlıdır ve yalnızca hesabınızdaki doğrulanmış adrese gider.",
    updatesAvailable: "ilan değişikliği eşitlendi",
    refreshed: "Takip verileri güncel.",
    empty: "Özel iş akışınızı başlatmak için şirket ekleyin.",
    error: "İş takibi geçici olarak kullanılamıyor.",
    sourceLimit: "En fazla 20 şirket takip edebilirsiniz.",
    recentActivity: "Son hareketler",
    noRecentActivity: "Yakın zamanda ilan değişikliği yok.",
    jobsLimited: "Yalnızca en yeni ilanlar gösteriliyor. Daha fazlası için filtreleri daraltın.",
  },
  ru: {
    eyebrow: "Фоновое отслеживание вакансий",
    title: "Следите за официальными вакансиями компаний",
    intro: "Следите за компаниями через официальные API Greenhouse, Lever и Ashby. Проверки планируются примерно раз в 5 минут с учётом доступности источника. Мы не откликаемся за вас.",
    provider: "Источник",
    reference: "URL карьеры или ID доски",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Отслеживать компанию",
    adding: "Подключение…",
    signIn: "Войдите для отслеживания компаний",
    signInBody: "Войдите для фонового отслеживания, синхронизации и уведомлений. Гостям доступен разовый просмотр.",
    sources: "компаний",
    activeJobs: "активных вакансий",
    checked: "проверено",
    nextCheck: "проверка запланирована примерно через 5 минут, если источник доступен",
    everyFiveMinutes: "Примерно каждые 5 мин · зависит от доступности источника",
    noAutoApply: "Без автоматических откликов",
    healthy: "Работает",
    checking: "Проверка",
    delayed: "Задержка",
    newJobs: "Новые",
    updated: "Обновлены",
    removed: "Закрыты",
    checkNow: "Проверить сейчас",
    remove: "Не отслеживать",
    alerts: "Уведомления о новых вакансиях этой компании",
    emailAlerts: "Уведомления по почте",
    browserAlerts: "Уведомления браузера, пока страница открыта",
    emailNotice: "Почта подключается по желанию; письма идут только на подтверждённый адрес аккаунта.",
    updatesAvailable: "изменений вакансий синхронизировано",
    refreshed: "Данные отслеживания актуальны.",
    empty: "Добавьте компанию, чтобы создать личную ленту вакансий.",
    error: "Отслеживание вакансий временно недоступно.",
    sourceLimit: "Можно отслеживать до 20 компаний.",
    recentActivity: "Недавние события",
    noRecentActivity: "Недавних изменений нет.",
    jobsLimited: "Показаны только свежие вакансии. Уточните фильтры, чтобы увидеть больше.",
  },
  uk: {
    eyebrow: "Фонове відстеження вакансій",
    title: "Стежте за офіційними вакансіями компаній",
    intro: "Стежте за компаніями через офіційні API Greenhouse, Lever і Ashby. Перевірки плануються приблизно раз на 5 хвилин з урахуванням доступності джерела. Ми не подаємо заявки за вас.",
    provider: "Джерело",
    reference: "URL кар’єри або ID дошки",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Відстежувати компанію",
    adding: "Підключення…",
    signIn: "Увійдіть, щоб стежити за компаніями",
    signInBody: "Увійдіть для фонового відстеження, синхронізації та сповіщень. Гостям доступний одноразовий перегляд.",
    sources: "компаній",
    activeJobs: "активних вакансій",
    checked: "перевірено",
    nextCheck: "перевірку заплановано приблизно через 5 хвилин, якщо джерело доступне",
    everyFiveMinutes: "Приблизно кожні 5 хв · залежить від доступності джерела",
    noAutoApply: "Без автоматичних заявок",
    healthy: "Працює",
    checking: "Перевірка",
    delayed: "Затримка",
    newJobs: "Нові",
    updated: "Оновлені",
    removed: "Закриті",
    checkNow: "Перевірити зараз",
    remove: "Не відстежувати",
    alerts: "Сповіщення про нові вакансії цієї компанії",
    emailAlerts: "Сповіщення електронною поштою",
    browserAlerts: "Сповіщення браузера, поки сторінка відкрита",
    emailNotice: "Пошта вмикається за бажанням і надходить лише на підтверджену адресу акаунта.",
    updatesAvailable: "змін вакансій синхронізовано",
    refreshed: "Дані відстеження актуальні.",
    empty: "Додайте компанію, щоб створити приватну стрічку вакансій.",
    error: "Відстеження вакансій тимчасово недоступне.",
    sourceLimit: "Можна відстежувати до 20 компаній.",
    recentActivity: "Останні події",
    noRecentActivity: "Останніх змін немає.",
    jobsLimited: "Показано лише найновіші вакансії. Звузьте фільтри, щоб побачити більше.",
  },
  ar: {
    eyebrow: "تتبّع الوظائف في الخلفية",
    title: "تابع وظائف الشركات الرسمية",
    intro: "تابع الشركات عبر واجهات Greenhouse وLever وAshby الرسمية. تُجدول عمليات التحقق كل 5 دقائق تقريبًا بحسب توفر المصدر، ولا نقدّم طلبات نيابةً عنك.",
    provider: "المزوّد",
    reference: "رابط الوظائف أو معرّف اللوحة",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "تتبّع الشركة",
    adding: "جارٍ الاتصال…",
    signIn: "سجّل الدخول لتتبّع الشركات",
    signInBody: "سجّل الدخول للتتبّع والمزامنة والتنبيهات. يتيح وضع الضيف معاينة لمرة واحدة.",
    sources: "شركات",
    activeJobs: "وظائف نشطة",
    checked: "آخر تحقق",
    nextCheck: "تحقق مجدول خلال نحو 5 دقائق حسب توفر المصدر",
    everyFiveMinutes: "مجدول كل 5 دقائق تقريبًا · حسب توفر المصدر",
    noAutoApply: "لا تقديم تلقائي",
    healthy: "يعمل",
    checking: "جارٍ التحقق",
    delayed: "متأخر",
    newJobs: "جديدة",
    updated: "محدّثة",
    removed: "مغلقة",
    checkNow: "تحقق الآن",
    remove: "إيقاف التتبّع",
    alerts: "تنبيهات الوظائف الجديدة لهذه الشركة",
    emailAlerts: "تنبيهات وظائف بالبريد",
    browserAlerts: "تنبيهات المتصفح أثناء فتح هذه الصفحة",
    emailNotice: "البريد اختياري ويُرسل فقط إلى العنوان الموثّق في حسابك.",
    updatesAvailable: "تغييرات وظائف تمت مزامنتها",
    refreshed: "بيانات التتبّع محدثة.",
    empty: "أضف شركة لبدء موجز وظائفك الخاص.",
    error: "تتبّع الوظائف غير متاح مؤقتًا.",
    sourceLimit: "يمكنك تتبّع حتى 20 شركة.",
    recentActivity: "النشاط الأخير",
    noRecentActivity: "لا تغييرات حديثة في الوظائف.",
    jobsLimited: "تظهر أحدث الوظائف فقط. ضيّق عوامل التصفية لرؤية المزيد.",
  },
  he: {
    eyebrow: "מעקב משרות ברקע",
    title: "מעקב אחר משרות רשמיות של חברות",
    intro: "עקבו אחר חברות דרך הממשקים הרשמיים של Greenhouse, Lever ו-Ashby. הבדיקות מתוזמנות בערך כל 5 דקות, בהתאם לזמינות המקור. לא נגיש מועמדות בשמכם.",
    provider: "ספק",
    reference: "כתובת קריירה או מזהה לוח",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "מעקב אחר חברה",
    adding: "מתחבר…",
    signIn: "התחברו כדי לעקוב אחר חברות",
    signInBody: "התחברו למעקב ברקע, סנכרון והתראות. אורחים יכולים לבצע תצוגה מקדימה חד-פעמית.",
    sources: "חברות",
    activeJobs: "משרות פעילות",
    checked: "נבדק",
    nextCheck: "בדיקה מתוזמנת בעוד כ-5 דקות, לפי זמינות המקור",
    everyFiveMinutes: "מתוזמן בערך כל 5 דקות · לפי זמינות המקור",
    noAutoApply: "ללא הגשה אוטומטית",
    healthy: "תקין",
    checking: "בודק",
    delayed: "בעיכוב",
    newJobs: "חדשות",
    updated: "עודכנו",
    removed: "נסגרו",
    checkNow: "בדיקה עכשיו",
    remove: "הפסקת מעקב",
    alerts: "התראות על משרות חדשות בחברה זו",
    emailAlerts: "התראות משרות בדוא״ל",
    browserAlerts: "התראות דפדפן כשהעמוד פתוח",
    emailNotice: "דוא״ל הוא לבחירה ונשלח רק לכתובת המאומתת בחשבון.",
    updatesAvailable: "שינויי משרות סונכרנו",
    refreshed: "נתוני המעקב מעודכנים.",
    empty: "הוסיפו חברה כדי להתחיל פיד משרות פרטי.",
    error: "מעקב המשרות אינו זמין זמנית.",
    sourceLimit: "אפשר לעקוב אחר עד 20 חברות.",
    recentActivity: "פעילות אחרונה",
    noRecentActivity: "אין שינויי משרות אחרונים.",
    jobsLimited: "מוצגות רק המשרות החדשות ביותר. צמצמו מסננים כדי לראות עוד.",
  },
  hi: {
    eyebrow: "बैकग्राउंड नौकरी ट्रैकिंग",
    title: "कंपनियों की आधिकारिक नौकरियाँ ट्रैक करें",
    intro: "Greenhouse, Lever और Ashby के आधिकारिक API से कंपनियाँ ट्रैक करें। स्रोत की उपलब्धता के अनुसार जाँच लगभग हर 5 मिनट में निर्धारित होती है। हम आपकी ओर से आवेदन नहीं करते।",
    provider: "प्रदाता",
    reference: "करियर URL या बोर्ड ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "कंपनी ट्रैक करें",
    adding: "कनेक्ट हो रहा है…",
    signIn: "कंपनियाँ ट्रैक करने के लिए साइन इन करें",
    signInBody: "बैकग्राउंड ट्रैकिंग, डिवाइस सिंक और अलर्ट के लिए साइन इन करें। अतिथि एक बार पूर्वावलोकन कर सकते हैं।",
    sources: "कंपनियाँ",
    activeJobs: "सक्रिय नौकरियाँ",
    checked: "जाँच हुई",
    nextCheck: "स्रोत उपलब्ध होने पर लगभग 5 मिनट में अगली जाँच",
    everyFiveMinutes: "लगभग हर 5 मिनट निर्धारित · स्रोत उपलब्धता पर निर्भर",
    noAutoApply: "कोई स्वचालित आवेदन नहीं",
    healthy: "सक्रिय",
    checking: "जाँच जारी",
    delayed: "विलंबित",
    newJobs: "नई",
    updated: "अपडेट हुईं",
    removed: "बंद",
    checkNow: "अभी जाँचें",
    remove: "ट्रैकिंग रोकें",
    alerts: "इस कंपनी की नई नौकरी के अलर्ट",
    emailAlerts: "ईमेल नौकरी अलर्ट",
    browserAlerts: "यह पेज खुला हो तो ब्राउज़र अलर्ट",
    emailNotice: "ईमेल वैकल्पिक है और केवल आपके खाते के सत्यापित पते पर जाता है।",
    updatesAvailable: "नौकरी बदलाव सिंक हुए",
    refreshed: "ट्रैकिंग डेटा नवीनतम है।",
    empty: "अपना निजी नौकरी फ़ीड शुरू करने के लिए कंपनी जोड़ें।",
    error: "नौकरी ट्रैकिंग अभी उपलब्ध नहीं है।",
    sourceLimit: "आप अधिकतम 20 कंपनियाँ ट्रैक कर सकते हैं।",
    recentActivity: "हाल की गतिविधि",
    noRecentActivity: "हाल में कोई नौकरी बदलाव नहीं।",
    jobsLimited: "केवल नई नौकरियाँ दिखाई गई हैं। अधिक के लिए फ़िल्टर सीमित करें।",
  },
  bn: {
    eyebrow: "ব্যাকগ্রাউন্ড চাকরি ট্র্যাকিং",
    title: "কোম্পানির অফিসিয়াল চাকরি ট্র্যাক করুন",
    intro: "Greenhouse, Lever ও Ashby-এর অফিসিয়াল API দিয়ে কোম্পানি ট্র্যাক করুন। উৎসের প্রাপ্যতা অনুযায়ী প্রায় প্রতি ৫ মিনিটে পরীক্ষা নির্ধারিত হয়। আমরা আপনার হয়ে আবেদন করি না।",
    provider: "প্রদানকারী",
    reference: "ক্যারিয়ার URL বা বোর্ড ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "কোম্পানি ট্র্যাক করুন",
    adding: "সংযোগ হচ্ছে…",
    signIn: "কোম্পানি ট্র্যাক করতে সাইন ইন করুন",
    signInBody: "ব্যাকগ্রাউন্ড ট্র্যাকিং, ডিভাইস সিঙ্ক ও সতর্কতার জন্য সাইন ইন করুন। অতিথিরা একবার প্রিভিউ দেখতে পারবেন।",
    sources: "কোম্পানি",
    activeJobs: "সক্রিয় চাকরি",
    checked: "পরীক্ষিত",
    nextCheck: "উৎস পাওয়া গেলে প্রায় ৫ মিনিট পরে পরীক্ষা নির্ধারিত",
    everyFiveMinutes: "প্রায় প্রতি ৫ মিনিটে নির্ধারিত · উৎসের প্রাপ্যতার ওপর নির্ভর",
    noAutoApply: "স্বয়ংক্রিয় আবেদন নয়",
    healthy: "সক্রিয়",
    checking: "পরীক্ষা চলছে",
    delayed: "বিলম্বিত",
    newJobs: "নতুন",
    updated: "হালনাগাদ",
    removed: "বন্ধ",
    checkNow: "এখন পরীক্ষা করুন",
    remove: "ট্র্যাকিং বন্ধ করুন",
    alerts: "এই কোম্পানির নতুন চাকরির সতর্কতা",
    emailAlerts: "ইমেইল চাকরি সতর্কতা",
    browserAlerts: "এই পৃষ্ঠা খোলা থাকলে ব্রাউজার সতর্কতা",
    emailNotice: "ইমেইল ঐচ্ছিক এবং শুধু আপনার অ্যাকাউন্টের যাচাইকৃত ঠিকানায় যাবে।",
    updatesAvailable: "চাকরির পরিবর্তন সিঙ্ক হয়েছে",
    refreshed: "ট্র্যাকিং ডেটা হালনাগাদ।",
    empty: "ব্যক্তিগত চাকরি ফিড শুরু করতে কোম্পানি যোগ করুন।",
    error: "চাকরি ট্র্যাকিং সাময়িকভাবে অনুপলব্ধ।",
    sourceLimit: "সর্বোচ্চ ২০টি কোম্পানি ট্র্যাক করতে পারবেন।",
    recentActivity: "সাম্প্রতিক কার্যকলাপ",
    noRecentActivity: "সাম্প্রতিক কোনো চাকরি পরিবর্তন নেই।",
    jobsLimited: "শুধু নতুন চাকরিগুলো দেখানো হচ্ছে। আরও দেখতে ফিল্টার ছোট করুন।",
  },
  ur: {
    eyebrow: "پس منظر میں ملازمت کی نگرانی",
    title: "کمپنیوں کی سرکاری ملازمتیں ٹریک کریں",
    intro: "Greenhouse، Lever اور Ashby کے سرکاری API سے کمپنیوں کو ٹریک کریں۔ ماخذ کی دستیابی کے مطابق جانچ تقریباً ہر 5 منٹ میں طے ہوتی ہے۔ ہم آپ کی طرف سے درخواست نہیں دیتے۔",
    provider: "فراہم کنندہ",
    reference: "کیریئر URL یا بورڈ ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "کمپنی ٹریک کریں",
    adding: "رابطہ ہو رہا ہے…",
    signIn: "کمپنیاں ٹریک کرنے کے لیے سائن ان کریں",
    signInBody: "پس منظر ٹریکنگ، آلات کی ہم وقت سازی اور الرٹس کے لیے سائن ان کریں۔ مہمان ایک بار پیش منظر دیکھ سکتے ہیں۔",
    sources: "کمپنیاں",
    activeJobs: "فعال ملازمتیں",
    checked: "جانچ ہوئی",
    nextCheck: "ماخذ دستیاب ہونے پر تقریباً 5 منٹ بعد جانچ طے ہے",
    everyFiveMinutes: "تقریباً ہر 5 منٹ طے شدہ · ماخذ کی دستیابی پر منحصر",
    noAutoApply: "خودکار درخواست نہیں",
    healthy: "فعال",
    checking: "جانچ جاری",
    delayed: "تاخیر",
    newJobs: "نئی",
    updated: "تازہ شدہ",
    removed: "بند",
    checkNow: "ابھی جانچیں",
    remove: "ٹریکنگ روکیں",
    alerts: "اس کمپنی کی نئی ملازمتوں کے الرٹس",
    emailAlerts: "ای میل ملازمت الرٹس",
    browserAlerts: "صفحہ کھلا ہو تو براؤزر الرٹس",
    emailNotice: "ای میل اختیاری ہے اور صرف اکاؤنٹ کے تصدیق شدہ پتے پر جاتی ہے۔",
    updatesAvailable: "ملازمت کی تبدیلیاں ہم وقت ہوئیں",
    refreshed: "ٹریکنگ ڈیٹا تازہ ہے۔",
    empty: "اپنی نجی ملازمت فیڈ شروع کرنے کے لیے کمپنی شامل کریں۔",
    error: "ملازمت ٹریکنگ عارضی طور پر دستیاب نہیں۔",
    sourceLimit: "آپ زیادہ سے زیادہ 20 کمپنیاں ٹریک کر سکتے ہیں۔",
    recentActivity: "حالیہ سرگرمی",
    noRecentActivity: "حالیہ ملازمت کی کوئی تبدیلی نہیں۔",
    jobsLimited: "صرف تازہ ترین ملازمتیں دکھائی گئی ہیں۔ مزید کے لیے فلٹر محدود کریں۔",
  },
  id: {
    eyebrow: "Pelacakan lowongan di latar belakang",
    title: "Pantau lowongan resmi perusahaan",
    intro: "Pantau perusahaan melalui API resmi Greenhouse, Lever, dan Ashby. Pemeriksaan dijadwalkan kira-kira setiap 5 menit, bergantung pada ketersediaan penyedia. Kami tidak melamar atas nama Anda.",
    provider: "Penyedia",
    reference: "URL karier atau ID papan",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Pantau perusahaan",
    adding: "Menghubungkan…",
    signIn: "Masuk untuk memantau perusahaan",
    signInBody: "Masuk untuk pelacakan, sinkronisasi perangkat, dan notifikasi. Tamu tetap dapat melihat pratinjau sekali.",
    sources: "perusahaan",
    activeJobs: "lowongan aktif",
    checked: "diperiksa",
    nextCheck: "pemeriksaan dijadwalkan sekitar 5 menit lagi, sesuai ketersediaan",
    everyFiveMinutes: "Dijadwalkan sekitar tiap 5 menit · sesuai ketersediaan",
    noAutoApply: "Tanpa lamaran otomatis",
    healthy: "Aktif",
    checking: "Memeriksa",
    delayed: "Tertunda",
    newJobs: "Baru",
    updated: "Diperbarui",
    removed: "Ditutup",
    checkNow: "Periksa sekarang",
    remove: "Berhenti memantau",
    alerts: "Notifikasi lowongan baru perusahaan ini",
    emailAlerts: "Notifikasi lowongan via email",
    browserAlerts: "Notifikasi browser saat halaman ini terbuka",
    emailNotice: "Email bersifat opsional dan hanya dikirim ke alamat terverifikasi di akun Anda.",
    updatesAvailable: "perubahan lowongan disinkronkan",
    refreshed: "Data pelacakan sudah terbaru.",
    empty: "Tambahkan perusahaan untuk memulai feed lowongan pribadi.",
    error: "Pelacakan lowongan sementara tidak tersedia.",
    sourceLimit: "Anda dapat memantau hingga 20 perusahaan.",
    recentActivity: "Aktivitas terbaru",
    noRecentActivity: "Tidak ada perubahan lowongan terbaru.",
    jobsLimited: "Hanya lowongan terbaru yang ditampilkan. Persempit filter untuk melihat lainnya.",
  },
  ms: {
    eyebrow: "Penjejakan kerja di latar belakang",
    title: "Jejak jawatan rasmi syarikat",
    intro: "Jejak syarikat melalui API rasmi Greenhouse, Lever dan Ashby. Semakan dijadualkan kira-kira setiap 5 minit, bergantung pada ketersediaan penyedia. Kami tidak memohon bagi pihak anda.",
    provider: "Penyedia",
    reference: "URL kerjaya atau ID papan",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Jejak syarikat",
    adding: "Menyambung…",
    signIn: "Log masuk untuk menjejak syarikat",
    signInBody: "Log masuk untuk penjejakan, penyegerakan peranti dan makluman. Tetamu masih boleh membuat pratonton sekali.",
    sources: "syarikat",
    activeJobs: "jawatan aktif",
    checked: "disemak",
    nextCheck: "semakan dijadualkan dalam kira-kira 5 minit, mengikut ketersediaan",
    everyFiveMinutes: "Dijadualkan kira-kira setiap 5 minit · mengikut ketersediaan",
    noAutoApply: "Tiada permohonan automatik",
    healthy: "Aktif",
    checking: "Menyemak",
    delayed: "Tertangguh",
    newJobs: "Baharu",
    updated: "Dikemas kini",
    removed: "Ditutup",
    checkNow: "Semak sekarang",
    remove: "Henti menjejak",
    alerts: "Makluman jawatan baharu syarikat ini",
    emailAlerts: "Makluman kerja melalui e-mel",
    browserAlerts: "Makluman pelayar semasa halaman ini dibuka",
    emailNotice: "E-mel adalah pilihan dan hanya dihantar ke alamat akaun yang disahkan.",
    updatesAvailable: "perubahan jawatan disegerakkan",
    refreshed: "Data penjejakan sudah terkini.",
    empty: "Tambah syarikat untuk memulakan suapan kerja peribadi.",
    error: "Penjejakan kerja tidak tersedia buat sementara waktu.",
    sourceLimit: "Anda boleh menjejak sehingga 20 syarikat.",
    recentActivity: "Aktiviti terkini",
    noRecentActivity: "Tiada perubahan jawatan terkini.",
    jobsLimited: "Hanya jawatan terkini dipaparkan. Kecilkan penapis untuk melihat lagi.",
  },
  th: {
    eyebrow: "ติดตามงานเบื้องหลัง",
    title: "ติดตามประกาศงานทางการของบริษัท",
    intro: "ติดตามบริษัทผ่าน API ทางการของ Greenhouse, Lever และ Ashby ระบบจะกำหนดตรวจประมาณทุก 5 นาทีตามความพร้อมของแหล่งข้อมูล และจะไม่สมัครงานแทนคุณ",
    provider: "ผู้ให้บริการ",
    reference: "URL หน้ารับสมัครหรือรหัสบอร์ด",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "ติดตามบริษัท",
    adding: "กำลังเชื่อมต่อ…",
    signIn: "เข้าสู่ระบบเพื่อติดตามบริษัท",
    signInBody: "เข้าสู่ระบบเพื่อใช้การติดตามเบื้องหลัง การซิงก์ และการแจ้งเตือน ผู้เยี่ยมชมยังดูตัวอย่างได้หนึ่งครั้ง",
    sources: "บริษัท",
    activeJobs: "งานที่เปิดอยู่",
    checked: "ตรวจล่าสุด",
    nextCheck: "กำหนดตรวจในประมาณ 5 นาทีตามความพร้อมของแหล่งข้อมูล",
    everyFiveMinutes: "กำหนดประมาณทุก 5 นาที · ขึ้นกับความพร้อมของแหล่งข้อมูล",
    noAutoApply: "ไม่มีการสมัครอัตโนมัติ",
    healthy: "พร้อมใช้งาน",
    checking: "กำลังตรวจ",
    delayed: "ล่าช้า",
    newJobs: "ใหม่",
    updated: "อัปเดต",
    removed: "ปิดแล้ว",
    checkNow: "ตรวจตอนนี้",
    remove: "หยุดติดตาม",
    alerts: "แจ้งเตือนงานใหม่ของบริษัทนี้",
    emailAlerts: "แจ้งเตือนงานทางอีเมล",
    browserAlerts: "แจ้งเตือนผ่านเบราว์เซอร์เมื่อเปิดหน้านี้",
    emailNotice: "อีเมลเป็นตัวเลือกและส่งเฉพาะไปยังที่อยู่ที่ยืนยันแล้วในบัญชีของคุณ",
    updatesAvailable: "การเปลี่ยนแปลงงานที่ซิงก์แล้ว",
    refreshed: "ข้อมูลติดตามเป็นปัจจุบันแล้ว",
    empty: "เพิ่มบริษัทเพื่อเริ่มฟีดงานส่วนตัวของคุณ",
    error: "การติดตามงานไม่พร้อมใช้งานชั่วคราว",
    sourceLimit: "ติดตามได้สูงสุด 20 บริษัท",
    recentActivity: "กิจกรรมล่าสุด",
    noRecentActivity: "ไม่มีการเปลี่ยนแปลงงานล่าสุด",
    jobsLimited: "แสดงเฉพาะงานล่าสุด ปรับตัวกรองให้แคบลงเพื่อดูเพิ่ม",
  },
  vi: {
    eyebrow: "Theo dõi việc làm nền",
    title: "Theo dõi tin tuyển dụng chính thức",
    intro: "Theo dõi công ty qua API chính thức của Greenhouse, Lever và Ashby. Hệ thống lên lịch kiểm tra khoảng 5 phút một lần, tùy nguồn có sẵn. Chúng tôi không ứng tuyển thay bạn.",
    provider: "Nhà cung cấp",
    reference: "URL tuyển dụng hoặc ID bảng tin",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Theo dõi công ty",
    adding: "Đang kết nối…",
    signIn: "Đăng nhập để theo dõi công ty",
    signInBody: "Đăng nhập để theo dõi nền, đồng bộ thiết bị và nhận thông báo. Khách vẫn có thể xem thử một lần.",
    sources: "công ty",
    activeJobs: "việc đang tuyển",
    checked: "đã kiểm tra",
    nextCheck: "dự kiến kiểm tra sau khoảng 5 phút, tùy nguồn có sẵn",
    everyFiveMinutes: "Lên lịch khoảng 5 phút/lần · tùy nguồn có sẵn",
    noAutoApply: "Không tự động ứng tuyển",
    healthy: "Hoạt động",
    checking: "Đang kiểm tra",
    delayed: "Chậm",
    newJobs: "Mới",
    updated: "Đã cập nhật",
    removed: "Đã đóng",
    checkNow: "Kiểm tra ngay",
    remove: "Ngừng theo dõi",
    alerts: "Thông báo việc mới của công ty này",
    emailAlerts: "Thông báo việc qua email",
    browserAlerts: "Thông báo trình duyệt khi trang này đang mở",
    emailNotice: "Email là tùy chọn và chỉ gửi đến địa chỉ đã xác minh trong tài khoản.",
    updatesAvailable: "thay đổi việc làm đã đồng bộ",
    refreshed: "Dữ liệu theo dõi đã cập nhật.",
    empty: "Thêm công ty để bắt đầu nguồn việc làm riêng tư.",
    error: "Tính năng theo dõi tạm thời không khả dụng.",
    sourceLimit: "Bạn có thể theo dõi tối đa 20 công ty.",
    recentActivity: "Hoạt động gần đây",
    noRecentActivity: "Không có thay đổi việc làm gần đây.",
    jobsLimited: "Chỉ hiển thị việc mới nhất. Thu hẹp bộ lọc để xem thêm.",
  },
  fil: {
    eyebrow: "Pagsubaybay ng trabaho sa background",
    title: "Subaybayan ang opisyal na trabaho ng kumpanya",
    intro: "Subaybayan ang mga kumpanya gamit ang opisyal na API ng Greenhouse, Lever, at Ashby. Naka-iskedyul ang pag-check kada humigit-kumulang 5 minuto, depende sa availability ng provider. Hindi kami nag-a-apply para sa iyo.",
    provider: "Provider",
    reference: "Careers URL o board ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Subaybayan ang kumpanya",
    adding: "Kumokonekta…",
    signIn: "Mag-sign in para subaybayan ang kumpanya",
    signInBody: "Mag-sign in para sa background tracking, device sync, at alerts. May isang beses na preview pa rin ang bisita.",
    sources: "kumpanya",
    activeJobs: "aktibong trabaho",
    checked: "huling check",
    nextCheck: "naka-iskedyul sa humigit-kumulang 5 minuto, depende sa availability",
    everyFiveMinutes: "Naka-iskedyul kada humigit-kumulang 5 minuto · depende sa availability",
    noAutoApply: "Walang awtomatikong pag-apply",
    healthy: "Aktibo",
    checking: "Nagche-check",
    delayed: "Naantala",
    newJobs: "Bago",
    updated: "Na-update",
    removed: "Sarado",
    checkNow: "I-check ngayon",
    remove: "Itigil ang pagsubaybay",
    alerts: "Alerts sa bagong trabaho ng kumpanyang ito",
    emailAlerts: "Email alerts sa trabaho",
    browserAlerts: "Browser alerts habang bukas ang pahinang ito",
    emailNotice: "Opsyonal ang email at sa verified address lang ng account ipapadala.",
    updatesAvailable: "pagbabago sa trabaho ang na-sync",
    refreshed: "Napapanahon ang tracking data.",
    empty: "Magdagdag ng kumpanya para simulan ang pribadong job feed.",
    error: "Pansamantalang hindi available ang job tracking.",
    sourceLimit: "Hanggang 20 kumpanya ang puwedeng subaybayan.",
    recentActivity: "Kamakailang aktibidad",
    noRecentActivity: "Walang kamakailang pagbabago sa trabaho.",
    jobsLimited: "Pinakabagong trabaho lang ang ipinapakita. Higpitan ang filter para makakita pa.",
  },
  sv: {
    eyebrow: "Jobbspårning i bakgrunden",
    title: "Följ företagens officiella jobb",
    intro: "Följ företag via officiella API:er från Greenhouse, Lever och Ashby. Kontroller schemaläggs ungefär var 5:e minut, beroende på leverantörens tillgänglighet. Vi söker aldrig åt dig.",
    provider: "Leverantör",
    reference: "Karriär-URL eller tavlans ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Följ företag",
    adding: "Ansluter…",
    signIn: "Logga in för att följa företag",
    signInBody: "Logga in för bakgrundsspårning, synkning och aviseringar. Gäster kan fortfarande göra en engångsförhandsvisning.",
    sources: "företag",
    activeJobs: "aktiva jobb",
    checked: "kontrollerad",
    nextCheck: "kontroll planerad om cirka 5 minuter, beroende på tillgänglighet",
    everyFiveMinutes: "Planerad ungefär var 5:e min · beror på tillgänglighet",
    noAutoApply: "Inga automatiska ansökningar",
    healthy: "Aktiv",
    checking: "Kontrollerar",
    delayed: "Fördröjd",
    newJobs: "Nya",
    updated: "Uppdaterade",
    removed: "Stängda",
    checkNow: "Kontrollera nu",
    remove: "Sluta följa",
    alerts: "Aviseringar om nya jobb hos detta företag",
    emailAlerts: "Jobbaviseringar via e-post",
    browserAlerts: "Webbläsaraviseringar när sidan är öppen",
    emailNotice: "E-post är valfritt och skickas bara till kontots verifierade adress.",
    updatesAvailable: "jobbändringar synkroniserade",
    refreshed: "Spårningsdata är aktuell.",
    empty: "Lägg till ett företag för att starta ditt privata jobbflöde.",
    error: "Jobbspårning är tillfälligt otillgänglig.",
    sourceLimit: "Du kan följa upp till 20 företag.",
    recentActivity: "Senaste aktivitet",
    noRecentActivity: "Inga senaste jobbändringar.",
    jobsLimited: "Endast de senaste jobben visas. Begränsa filtren för att se fler.",
  },
  no: {
    eyebrow: "Jobbsporing i bakgrunnen",
    title: "Følg bedrifters offisielle jobber",
    intro: "Følg bedrifter via offisielle API-er fra Greenhouse, Lever og Ashby. Kontroller planlegges omtrent hvert 5. minutt, avhengig av leverandørens tilgjengelighet. Vi søker aldri for deg.",
    provider: "Leverandør",
    reference: "Karriere-URL eller tavle-ID",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Følg bedrift",
    adding: "Kobler til…",
    signIn: "Logg inn for å følge bedrifter",
    signInBody: "Logg inn for bakgrunnssporing, synkronisering og varsler. Gjester kan fortsatt forhåndsvise én gang.",
    sources: "bedrifter",
    activeJobs: "aktive jobber",
    checked: "sjekket",
    nextCheck: "kontroll planlagt om cirka 5 minutter, avhengig av tilgjengelighet",
    everyFiveMinutes: "Planlagt omtrent hvert 5. min · avhenger av tilgjengelighet",
    noAutoApply: "Ingen automatiske søknader",
    healthy: "Aktiv",
    checking: "Sjekker",
    delayed: "Forsinket",
    newJobs: "Nye",
    updated: "Oppdatert",
    removed: "Stengt",
    checkNow: "Sjekk nå",
    remove: "Slutt å følge",
    alerts: "Varsler om nye jobber i denne bedriften",
    emailAlerts: "Jobbvarsler på e-post",
    browserAlerts: "Nettleservarsler mens siden er åpen",
    emailNotice: "E-post er valgfritt og sendes bare til den bekreftede kontoadressen.",
    updatesAvailable: "jobbendringer synkronisert",
    refreshed: "Sporingsdata er oppdatert.",
    empty: "Legg til en bedrift for å starte din private jobbstrøm.",
    error: "Jobbsporing er midlertidig utilgjengelig.",
    sourceLimit: "Du kan følge opptil 20 bedrifter.",
    recentActivity: "Nylig aktivitet",
    noRecentActivity: "Ingen nylige jobbendringer.",
    jobsLimited: "Bare de nyeste jobbene vises. Begrens filtrene for å se flere.",
  },
  da: {
    eyebrow: "Jobsporing i baggrunden",
    title: "Følg virksomheders officielle job",
    intro: "Følg virksomheder via officielle API’er fra Greenhouse, Lever og Ashby. Kontroller planlægges cirka hvert 5. minut, afhængigt af udbyderens tilgængelighed. Vi søger aldrig for dig.",
    provider: "Udbyder",
    reference: "Karriere-URL eller tavle-id",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Følg virksomhed",
    adding: "Opretter forbindelse…",
    signIn: "Log ind for at følge virksomheder",
    signInBody: "Log ind for baggrundssporing, synkronisering og beskeder. Gæster kan stadig se en engangsvisning.",
    sources: "virksomheder",
    activeJobs: "aktive job",
    checked: "kontrolleret",
    nextCheck: "kontrol planlagt om cirka 5 minutter, afhængigt af tilgængelighed",
    everyFiveMinutes: "Planlagt cirka hvert 5. min · afhænger af tilgængelighed",
    noAutoApply: "Ingen automatiske ansøgninger",
    healthy: "Aktiv",
    checking: "Kontrollerer",
    delayed: "Forsinket",
    newJobs: "Nye",
    updated: "Opdateret",
    removed: "Lukket",
    checkNow: "Kontrollér nu",
    remove: "Stop med at følge",
    alerts: "Beskeder om nye job i denne virksomhed",
    emailAlerts: "Jobbeskeder via e-mail",
    browserAlerts: "Browserbeskeder, mens siden er åben",
    emailNotice: "E-mail er valgfrit og sendes kun til kontoens bekræftede adresse.",
    updatesAvailable: "jobændringer synkroniseret",
    refreshed: "Sporingsdata er opdateret.",
    empty: "Tilføj en virksomhed for at starte dit private jobfeed.",
    error: "Jobsporing er midlertidigt utilgængelig.",
    sourceLimit: "Du kan følge op til 20 virksomheder.",
    recentActivity: "Seneste aktivitet",
    noRecentActivity: "Ingen seneste jobændringer.",
    jobsLimited: "Kun de nyeste job vises. Begræns filtrene for at se flere.",
  },
  fi: {
    eyebrow: "Työpaikkojen taustaseuranta",
    title: "Seuraa yritysten virallisia työpaikkoja",
    intro: "Seuraa yrityksiä Greenhousen, Leverin ja Ashbyn virallisilla rajapinnoilla. Tarkistukset ajoitetaan noin 5 minuutin välein lähteen saatavuuden mukaan. Emme hae puolestasi.",
    provider: "Tarjoaja",
    reference: "Urasivun URL tai taulun tunnus",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Seuraa yritystä",
    adding: "Yhdistetään…",
    signIn: "Kirjaudu seuraamaan yrityksiä",
    signInBody: "Kirjaudu taustaseurantaa, laitesynkronointia ja ilmoituksia varten. Vieras voi silti tehdä kertakatselun.",
    sources: "yritystä",
    activeJobs: "avointa työpaikkaa",
    checked: "tarkistettu",
    nextCheck: "tarkistus noin 5 minuutin kuluttua lähteen saatavuuden mukaan",
    everyFiveMinutes: "Ajastettu noin 5 min välein · riippuu lähteen saatavuudesta",
    noAutoApply: "Ei automaattisia hakemuksia",
    healthy: "Toimii",
    checking: "Tarkistetaan",
    delayed: "Viivästynyt",
    newJobs: "Uudet",
    updated: "Päivitetty",
    removed: "Suljettu",
    checkNow: "Tarkista nyt",
    remove: "Lopeta seuranta",
    alerts: "Tämän yrityksen uusien työpaikkojen ilmoitukset",
    emailAlerts: "Työpaikkailmoitukset sähköpostiin",
    browserAlerts: "Selainilmoitukset sivun ollessa auki",
    emailNotice: "Sähköposti on valinnainen ja lähetetään vain tilin vahvistettuun osoitteeseen.",
    updatesAvailable: "työpaikkamuutosta synkronoitu",
    refreshed: "Seurantatiedot ovat ajan tasalla.",
    empty: "Lisää yritys aloittaaksesi yksityisen työpaikkasyötteen.",
    error: "Työpaikkaseuranta ei ole tilapäisesti käytettävissä.",
    sourceLimit: "Voit seurata enintään 20 yritystä.",
    recentActivity: "Viimeisimmät tapahtumat",
    noRecentActivity: "Ei viimeaikaisia työpaikkamuutoksia.",
    jobsLimited: "Vain uusimmat työpaikat näytetään. Rajaa suodattimia nähdäksesi lisää.",
  },
  cs: {
    eyebrow: "Sledování nabídek na pozadí",
    title: "Sledujte oficiální nabídky firem",
    intro: "Sledujte firmy přes oficiální API Greenhouse, Lever a Ashby. Kontroly se plánují přibližně každých 5 minut podle dostupnosti zdroje. Nikdy za vás neposíláme přihlášky.",
    provider: "Poskytovatel",
    reference: "URL kariéry nebo ID nástěnky",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Sledovat firmu",
    adding: "Připojování…",
    signIn: "Přihlaste se ke sledování firem",
    signInBody: "Přihlaste se pro sledování na pozadí, synchronizaci a upozornění. Host může provést jednorázový náhled.",
    sources: "firem",
    activeJobs: "aktivních nabídek",
    checked: "zkontrolováno",
    nextCheck: "kontrola za přibližně 5 minut podle dostupnosti zdroje",
    everyFiveMinutes: "Plánováno asi každých 5 min · podle dostupnosti zdroje",
    noAutoApply: "Bez automatických přihlášek",
    healthy: "Aktivní",
    checking: "Kontrola",
    delayed: "Zpožděno",
    newJobs: "Nové",
    updated: "Aktualizované",
    removed: "Uzavřené",
    checkNow: "Zkontrolovat",
    remove: "Přestat sledovat",
    alerts: "Upozornění na nové nabídky této firmy",
    emailAlerts: "Upozornění e-mailem",
    browserAlerts: "Upozornění prohlížeče při otevřené stránce",
    emailNotice: "E-mail je volitelný a přijde jen na ověřenou adresu účtu.",
    updatesAvailable: "změn nabídek synchronizováno",
    refreshed: "Data sledování jsou aktuální.",
    empty: "Přidejte firmu a vytvořte soukromý přehled nabídek.",
    error: "Sledování nabídek je dočasně nedostupné.",
    sourceLimit: "Můžete sledovat až 20 firem.",
    recentActivity: "Nedávná aktivita",
    noRecentActivity: "Žádné nedávné změny nabídek.",
    jobsLimited: "Zobrazeny jsou jen nejnovější nabídky. Pro další zúžte filtry.",
  },
  sk: {
    eyebrow: "Sledovanie ponúk na pozadí",
    title: "Sledujte oficiálne ponuky firiem",
    intro: "Sledujte firmy cez oficiálne API Greenhouse, Lever a Ashby. Kontroly sa plánujú približne každých 5 minút podľa dostupnosti zdroja. Nikdy za vás neposielame žiadosti.",
    provider: "Poskytovateľ",
    reference: "URL kariéry alebo ID nástenky",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Sledovať firmu",
    adding: "Pripájanie…",
    signIn: "Prihláste sa na sledovanie firiem",
    signInBody: "Prihláste sa pre sledovanie na pozadí, synchronizáciu a upozornenia. Hosť môže použiť jednorazový náhľad.",
    sources: "firiem",
    activeJobs: "aktívnych ponúk",
    checked: "skontrolované",
    nextCheck: "kontrola asi o 5 minút podľa dostupnosti zdroja",
    everyFiveMinutes: "Plánované asi každých 5 min · podľa dostupnosti zdroja",
    noAutoApply: "Bez automatických žiadostí",
    healthy: "Aktívne",
    checking: "Kontrola",
    delayed: "Oneskorené",
    newJobs: "Nové",
    updated: "Aktualizované",
    removed: "Ukončené",
    checkNow: "Skontrolovať",
    remove: "Prestať sledovať",
    alerts: "Upozornenia na nové ponuky tejto firmy",
    emailAlerts: "Upozornenia e-mailom",
    browserAlerts: "Upozornenia prehliadača pri otvorenej stránke",
    emailNotice: "E-mail je voliteľný a príde len na overenú adresu účtu.",
    updatesAvailable: "zmien ponúk synchronizovaných",
    refreshed: "Údaje sledovania sú aktuálne.",
    empty: "Pridajte firmu a vytvorte súkromný prehľad ponúk.",
    error: "Sledovanie ponúk je dočasne nedostupné.",
    sourceLimit: "Môžete sledovať najviac 20 firiem.",
    recentActivity: "Nedávna aktivita",
    noRecentActivity: "Žiadne nedávne zmeny ponúk.",
    jobsLimited: "Zobrazené sú len najnovšie ponuky. Ďalšie nájdete zúžením filtrov.",
  },
  hu: {
    eyebrow: "Állások háttérkövetése",
    title: "Kövesse a cégek hivatalos állásait",
    intro: "Kövesse a cégeket a Greenhouse, a Lever és az Ashby hivatalos API-jain keresztül. Az ellenőrzés körülbelül 5 percenként ütemezett, a forrás elérhetőségétől függően. Nem jelentkezünk Ön helyett.",
    provider: "Szolgáltató",
    reference: "Karrier-URL vagy táblaazonosító",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Cég követése",
    adding: "Kapcsolódás…",
    signIn: "Jelentkezzen be a cégek követéséhez",
    signInBody: "Jelentkezzen be a háttérkövetéshez, szinkronizáláshoz és értesítésekhez. Vendégként egyszeri előnézet érhető el.",
    sources: "cég",
    activeJobs: "aktív állás",
    checked: "ellenőrizve",
    nextCheck: "ellenőrzés kb. 5 perc múlva, a forrás elérhetőségétől függően",
    everyFiveMinutes: "Kb. 5 percenként ütemezve · forrásfüggő",
    noAutoApply: "Nincs automatikus jelentkezés",
    healthy: "Aktív",
    checking: "Ellenőrzés",
    delayed: "Késik",
    newJobs: "Új",
    updated: "Frissítve",
    removed: "Lezárva",
    checkNow: "Ellenőrzés most",
    remove: "Követés leállítása",
    alerts: "Értesítések e cég új állásairól",
    emailAlerts: "Állásértesítések e-mailben",
    browserAlerts: "Böngészőértesítés, amíg az oldal nyitva van",
    emailNotice: "Az e-mail opcionális, és csak a fiók igazolt címére érkezik.",
    updatesAvailable: "állásváltozás szinkronizálva",
    refreshed: "A követési adatok naprakészek.",
    empty: "Adjon hozzá céget a privát állásfolyam indításához.",
    error: "Az álláskövetés átmenetileg nem érhető el.",
    sourceLimit: "Legfeljebb 20 céget követhet.",
    recentActivity: "Legutóbbi aktivitás",
    noRecentActivity: "Nincs friss állásváltozás.",
    jobsLimited: "Csak a legújabb állások láthatók. Szűkítse a szűrőket továbbiakért.",
  },
  ro: {
    eyebrow: "Urmărire joburi în fundal",
    title: "Urmărește joburile oficiale ale companiilor",
    intro: "Urmărește companii prin API-urile oficiale Greenhouse, Lever și Ashby. Verificările sunt programate aproximativ la 5 minute, în funcție de disponibilitatea sursei. Nu aplicăm în locul tău.",
    provider: "Furnizor",
    reference: "URL cariere sau ID panou",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Urmărește compania",
    adding: "Se conectează…",
    signIn: "Autentifică-te pentru a urmări companii",
    signInBody: "Autentifică-te pentru urmărire, sincronizare și alerte. Vizitatorii pot face o previzualizare unică.",
    sources: "companii",
    activeJobs: "joburi active",
    checked: "verificat",
    nextCheck: "verificare programată în circa 5 minute, în funcție de disponibilitate",
    everyFiveMinutes: "Programat aproximativ la 5 min · în funcție de disponibilitate",
    noAutoApply: "Fără aplicări automate",
    healthy: "Activ",
    checking: "Se verifică",
    delayed: "Întârziat",
    newJobs: "Noi",
    updated: "Actualizate",
    removed: "Închise",
    checkNow: "Verifică acum",
    remove: "Oprește urmărirea",
    alerts: "Alerte pentru joburile noi ale acestei companii",
    emailAlerts: "Alerte de job prin e-mail",
    browserAlerts: "Alerte în browser cât timp pagina este deschisă",
    emailNotice: "E-mailul este opțional și ajunge doar la adresa verificată a contului.",
    updatesAvailable: "schimbări de job sincronizate",
    refreshed: "Datele de urmărire sunt actualizate.",
    empty: "Adaugă o companie pentru fluxul tău privat de joburi.",
    error: "Urmărirea joburilor este temporar indisponibilă.",
    sourceLimit: "Poți urmări până la 20 de companii.",
    recentActivity: "Activitate recentă",
    noRecentActivity: "Nu există schimbări recente.",
    jobsLimited: "Sunt afișate doar cele mai noi joburi. Restrânge filtrele pentru mai multe.",
  },
  el: {
    eyebrow: "Παρακολούθηση θέσεων στο παρασκήνιο",
    title: "Παρακολουθήστε επίσημες θέσεις εταιρειών",
    intro: "Παρακολουθήστε εταιρείες μέσω των επίσημων API των Greenhouse, Lever και Ashby. Οι έλεγχοι προγραμματίζονται περίπου κάθε 5 λεπτά, ανάλογα με τη διαθεσιμότητα της πηγής. Δεν υποβάλλουμε αιτήσεις για εσάς.",
    provider: "Πάροχος",
    reference: "URL καριέρας ή ID πίνακα",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Παρακολούθηση εταιρείας",
    adding: "Σύνδεση…",
    signIn: "Συνδεθείτε για παρακολούθηση εταιρειών",
    signInBody: "Συνδεθείτε για παρακολούθηση, συγχρονισμό και ειδοποιήσεις. Οι επισκέπτες μπορούν να κάνουν μία προεπισκόπηση.",
    sources: "εταιρείες",
    activeJobs: "ενεργές θέσεις",
    checked: "ελέγχθηκε",
    nextCheck: "έλεγχος σε περίπου 5 λεπτά, ανάλογα με τη διαθεσιμότητα",
    everyFiveMinutes: "Προγραμματισμένο περίπου κάθε 5 λεπτά · ανάλογα με τη διαθεσιμότητα",
    noAutoApply: "Χωρίς αυτόματες αιτήσεις",
    healthy: "Ενεργό",
    checking: "Έλεγχος",
    delayed: "Καθυστέρηση",
    newJobs: "Νέες",
    updated: "Ενημερωμένες",
    removed: "Κλειστές",
    checkNow: "Έλεγχος τώρα",
    remove: "Διακοπή παρακολούθησης",
    alerts: "Ειδοποιήσεις για νέες θέσεις αυτής της εταιρείας",
    emailAlerts: "Ειδοποιήσεις θέσεων με email",
    browserAlerts: "Ειδοποιήσεις προγράμματος περιήγησης όταν η σελίδα είναι ανοιχτή",
    emailNotice: "Το email είναι προαιρετικό και αποστέλλεται μόνο στην επαληθευμένη διεύθυνση του λογαριασμού.",
    updatesAvailable: "αλλαγές θέσεων συγχρονίστηκαν",
    refreshed: "Τα δεδομένα παρακολούθησης είναι ενημερωμένα.",
    empty: "Προσθέστε εταιρεία για την ιδιωτική ροή θέσεων.",
    error: "Η παρακολούθηση θέσεων δεν είναι προσωρινά διαθέσιμη.",
    sourceLimit: "Μπορείτε να παρακολουθείτε έως 20 εταιρείες.",
    recentActivity: "Πρόσφατη δραστηριότητα",
    noRecentActivity: "Δεν υπάρχουν πρόσφατες αλλαγές θέσεων.",
    jobsLimited: "Εμφανίζονται μόνο οι νεότερες θέσεις. Περιορίστε τα φίλτρα για περισσότερες.",
  },
  bg: {
    eyebrow: "Фоново проследяване на обяви",
    title: "Следете официалните обяви на компании",
    intro: "Следете компании чрез официалните API на Greenhouse, Lever и Ashby. Проверките се планират приблизително на 5 минути според наличността на източника. Не кандидатстваме вместо вас.",
    provider: "Доставчик",
    reference: "URL за кариери или ID на табло",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Следене на компания",
    adding: "Свързване…",
    signIn: "Влезте, за да следите компании",
    signInBody: "Влезте за фоново проследяване, синхронизиране и известия. Гостите могат да направят еднократен преглед.",
    sources: "компании",
    activeJobs: "активни обяви",
    checked: "проверено",
    nextCheck: "проверка след около 5 минути според наличността",
    everyFiveMinutes: "Планирано през около 5 мин · според наличността",
    noAutoApply: "Без автоматични кандидатури",
    healthy: "Активно",
    checking: "Проверка",
    delayed: "Забавено",
    newJobs: "Нови",
    updated: "Обновени",
    removed: "Затворени",
    checkNow: "Провери сега",
    remove: "Спри следенето",
    alerts: "Известия за нови обяви на тази компания",
    emailAlerts: "Известия по имейл",
    browserAlerts: "Известия в браузъра при отворена страница",
    emailNotice: "Имейлът е по избор и се изпраща само до потвърдения адрес на акаунта.",
    updatesAvailable: "промени в обяви синхронизирани",
    refreshed: "Данните за проследяване са актуални.",
    empty: "Добавете компания за личния си поток от обяви.",
    error: "Проследяването временно не е достъпно.",
    sourceLimit: "Можете да следите до 20 компании.",
    recentActivity: "Скорошна активност",
    noRecentActivity: "Няма скорошни промени в обявите.",
    jobsLimited: "Показани са само най-новите обяви. Стеснете филтрите за още.",
  },
  hr: {
    eyebrow: "Praćenje poslova u pozadini",
    title: "Pratite službene oglase tvrtki",
    intro: "Pratite tvrtke putem službenih API-ja Greenhousea, Levera i Ashbyja. Provjere se zakazuju otprilike svakih 5 minuta, ovisno o dostupnosti izvora. Ne prijavljujemo se umjesto vas.",
    provider: "Pružatelj",
    reference: "URL karijera ili ID ploče",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Prati tvrtku",
    adding: "Povezivanje…",
    signIn: "Prijavite se za praćenje tvrtki",
    signInBody: "Prijavite se za praćenje, sinkronizaciju i obavijesti. Gosti mogu napraviti jednokratni pregled.",
    sources: "tvrtki",
    activeJobs: "aktivnih poslova",
    checked: "provjereno",
    nextCheck: "provjera za oko 5 minuta, ovisno o dostupnosti izvora",
    everyFiveMinutes: "Zakazano otprilike svakih 5 min · ovisno o dostupnosti",
    noAutoApply: "Bez automatskih prijava",
    healthy: "Aktivno",
    checking: "Provjera",
    delayed: "Odgođeno",
    newJobs: "Novi",
    updated: "Ažurirani",
    removed: "Zatvoreni",
    checkNow: "Provjeri sada",
    remove: "Prestani pratiti",
    alerts: "Obavijesti o novim poslovima ove tvrtke",
    emailAlerts: "Obavijesti e-poštom",
    browserAlerts: "Obavijesti preglednika dok je stranica otvorena",
    emailNotice: "E-pošta je izborna i šalje se samo na potvrđenu adresu računa.",
    updatesAvailable: "promjene poslova sinkronizirane",
    refreshed: "Podaci za praćenje su ažurni.",
    empty: "Dodajte tvrtku za svoj privatni sažetak poslova.",
    error: "Praćenje poslova privremeno nije dostupno.",
    sourceLimit: "Možete pratiti do 20 tvrtki.",
    recentActivity: "Nedavna aktivnost",
    noRecentActivity: "Nema nedavnih promjena poslova.",
    jobsLimited: "Prikazani su samo najnoviji poslovi. Suzite filtre za više.",
  },
  sr: {
    eyebrow: "Праћење послова у позадини",
    title: "Пратите званичне огласе компанија",
    intro: "Пратите компаније преко званичних API-ја Greenhouse, Lever и Ashby. Провере се заказују отприлике сваких 5 минута, у зависности од доступности извора. Не пријављујемо се уместо вас.",
    provider: "Добављач",
    reference: "URL каријере или ID табле",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Прати компанију",
    adding: "Повезивање…",
    signIn: "Пријавите се за праћење компанија",
    signInBody: "Пријавите се за праћење, синхронизацију и обавештења. Гости могу једном да прегледају извор.",
    sources: "компанија",
    activeJobs: "активних послова",
    checked: "проверено",
    nextCheck: "провера за око 5 минута, зависно од доступности извора",
    everyFiveMinutes: "Заказано приближно сваких 5 мин · зависно од доступности",
    noAutoApply: "Без аутоматских пријава",
    healthy: "Активно",
    checking: "Провера",
    delayed: "Кашњење",
    newJobs: "Нови",
    updated: "Ажурирани",
    removed: "Затворени",
    checkNow: "Провери сада",
    remove: "Прекини праћење",
    alerts: "Обавештења о новим пословима ове компаније",
    emailAlerts: "Обавештења е-поштом",
    browserAlerts: "Обавештења прегледача док је страница отворена",
    emailNotice: "Е-пошта је опциона и шаље се само на потврђену адресу налога.",
    updatesAvailable: "промене послова синхронизоване",
    refreshed: "Подаци праћења су ажурни.",
    empty: "Додајте компанију за свој приватни ток послова.",
    error: "Праћење послова привремено није доступно.",
    sourceLimit: "Можете пратити до 20 компанија.",
    recentActivity: "Недавна активност",
    noRecentActivity: "Нема недавних промена послова.",
    jobsLimited: "Приказани су само најновији послови. Сузите филтере за више.",
  },
  sl: {
    eyebrow: "Sledenje zaposlitev v ozadju",
    title: "Spremljajte uradne objave podjetij",
    intro: "Spremljajte podjetja prek uradnih API-jev Greenhouse, Lever in Ashby. Preverjanja so načrtovana približno vsakih 5 minut, odvisno od razpoložljivosti vira. Ne prijavljamo se namesto vas.",
    provider: "Ponudnik",
    reference: "URL kariere ali ID table",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Spremljaj podjetje",
    adding: "Povezovanje…",
    signIn: "Prijavite se za sledenje podjetjem",
    signInBody: "Prijavite se za sledenje, sinhronizacijo in obvestila. Gostje lahko opravijo enkratni predogled.",
    sources: "podjetij",
    activeJobs: "aktivnih zaposlitev",
    checked: "preverjeno",
    nextCheck: "preverjanje čez približno 5 minut, odvisno od razpoložljivosti",
    everyFiveMinutes: "Načrtovano približno vsakih 5 min · odvisno od razpoložljivosti",
    noAutoApply: "Brez samodejnih prijav",
    healthy: "Aktivno",
    checking: "Preverjanje",
    delayed: "Zamuda",
    newJobs: "Nove",
    updated: "Posodobljene",
    removed: "Zaprte",
    checkNow: "Preveri zdaj",
    remove: "Prenehaj spremljati",
    alerts: "Obvestila o novih zaposlitvah tega podjetja",
    emailAlerts: "Obvestila po e-pošti",
    browserAlerts: "Obvestila brskalnika, ko je stran odprta",
    emailNotice: "E-pošta je izbirna in je poslana samo na potrjeni naslov računa.",
    updatesAvailable: "spremembe zaposlitev sinhronizirane",
    refreshed: "Podatki sledenja so posodobljeni.",
    empty: "Dodajte podjetje za svoj zasebni tok zaposlitev.",
    error: "Sledenje zaposlitvam začasno ni na voljo.",
    sourceLimit: "Spremljate lahko do 20 podjetij.",
    recentActivity: "Nedavna dejavnost",
    noRecentActivity: "Ni nedavnih sprememb zaposlitev.",
    jobsLimited: "Prikazane so le najnovejše zaposlitve. Zožite filtre za več.",
  },
  sw: {
    eyebrow: "Ufuatiliaji wa kazi chinichini",
    title: "Fuatilia nafasi rasmi za kampuni",
    intro: "Fuatilia kampuni kupitia API rasmi za Greenhouse, Lever na Ashby. Ukaguzi hupangwa takriban kila dakika 5 kulingana na upatikanaji wa chanzo. Hatuombi kazi kwa niaba yako.",
    provider: "Mtoa huduma",
    reference: "URL ya ajira au kitambulisho cha ubao",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "Fuatilia kampuni",
    adding: "Inaunganisha…",
    signIn: "Ingia ili kufuatilia kampuni",
    signInBody: "Ingia kwa ufuatiliaji, usawazishaji na arifa. Wageni bado wanaweza kuona hakiki ya mara moja.",
    sources: "kampuni",
    activeJobs: "nafasi wazi",
    checked: "imekaguliwa",
    nextCheck: "ukaguzi umepangwa baada ya karibu dakika 5 kulingana na upatikanaji",
    everyFiveMinutes: "Imepangwa karibu kila dakika 5 · kulingana na upatikanaji",
    noAutoApply: "Hakuna maombi ya kiotomatiki",
    healthy: "Inafanya kazi",
    checking: "Inakagua",
    delayed: "Imechelewa",
    newJobs: "Mpya",
    updated: "Zimesasishwa",
    removed: "Zimefungwa",
    checkNow: "Kagua sasa",
    remove: "Acha kufuatilia",
    alerts: "Arifa za nafasi mpya za kampuni hii",
    emailAlerts: "Arifa za kazi kwa barua pepe",
    browserAlerts: "Arifa za kivinjari ukurasa huu ukiwa wazi",
    emailNotice: "Barua pepe ni hiari na hutumwa tu kwa anwani iliyothibitishwa ya akaunti.",
    updatesAvailable: "mabadiliko ya nafasi yamesawazishwa",
    refreshed: "Data ya ufuatiliaji imesasishwa.",
    empty: "Ongeza kampuni ili kuanza mkondo wako binafsi wa kazi.",
    error: "Ufuatiliaji wa kazi haupatikani kwa muda.",
    sourceLimit: "Unaweza kufuatilia hadi kampuni 20.",
    recentActivity: "Shughuli za hivi karibuni",
    noRecentActivity: "Hakuna mabadiliko mapya ya nafasi.",
    jobsLimited: "Nafasi mpya pekee zinaonyeshwa. Punguza vichujio ili kuona zaidi.",
  },
  fa: {
    eyebrow: "پیگیری فرصت‌های شغلی در پس‌زمینه",
    title: "فرصت‌های رسمی شرکت‌ها را دنبال کنید",
    intro: "شرکت‌ها را از طریق API رسمی Greenhouse، Lever و Ashby دنبال کنید. بررسی‌ها با توجه به دسترس‌پذیری منبع، تقریباً هر ۵ دقیقه زمان‌بندی می‌شوند. ما به‌جای شما درخواست نمی‌دهیم.",
    provider: "ارائه‌دهنده",
    reference: "نشانی صفحه مشاغل یا شناسه تابلو",
    referencePlaceholder: REFERENCE_PLACEHOLDER,
    add: "دنبال کردن شرکت",
    adding: "در حال اتصال…",
    signIn: "برای دنبال کردن شرکت‌ها وارد شوید",
    signInBody: "برای پیگیری پس‌زمینه، همگام‌سازی و اعلان‌ها وارد شوید. مهمانان می‌توانند یک‌بار پیش‌نمایش ببینند.",
    sources: "شرکت",
    activeJobs: "فرصت فعال",
    checked: "آخرین بررسی",
    nextCheck: "بررسی حدود ۵ دقیقه دیگر و با توجه به دسترس‌پذیری منبع",
    everyFiveMinutes: "زمان‌بندی تقریباً هر ۵ دقیقه · بسته به دسترس‌پذیری منبع",
    noAutoApply: "بدون درخواست خودکار",
    healthy: "فعال",
    checking: "در حال بررسی",
    delayed: "با تأخیر",
    newJobs: "جدید",
    updated: "به‌روزشده",
    removed: "بسته‌شده",
    checkNow: "اکنون بررسی کن",
    remove: "توقف پیگیری",
    alerts: "اعلان فرصت‌های جدید این شرکت",
    emailAlerts: "اعلان شغلی ایمیلی",
    browserAlerts: "اعلان مرورگر هنگام باز بودن این صفحه",
    emailNotice: "ایمیل اختیاری است و فقط به نشانی تأییدشده حساب ارسال می‌شود.",
    updatesAvailable: "تغییرات فرصت‌ها همگام شد",
    refreshed: "داده‌های پیگیری به‌روز است.",
    empty: "برای شروع فهرست خصوصی فرصت‌ها یک شرکت اضافه کنید.",
    error: "پیگیری فرصت‌های شغلی موقتاً در دسترس نیست.",
    sourceLimit: "می‌توانید حداکثر ۲۰ شرکت را دنبال کنید.",
    recentActivity: "فعالیت اخیر",
    noRecentActivity: "تغییر شغلی تازه‌ای وجود ندارد.",
    jobsLimited: "فقط جدیدترین فرصت‌ها نمایش داده می‌شوند. برای موارد بیشتر فیلترها را محدود کنید.",
  },
};

export function jobTrackingCopyFor(locale: LocaleCode): JobTrackingCopy {
  return COPY[locale];
}

export type JobTrackingRuntimeCopy = {
  nextCheckAt: string;
  noActiveJobs: string;
  browserUnsupported: string;
  browserDenied: string;
  refreshThrottled: string;
};

const RUNTIME_COPY: Record<LocaleCode, readonly [string, string, string, string, string]> = {
  en: ["next check", "No current published jobs were found. Tracking will continue in the background.", "Browser alerts are not supported on this device.", "Browser notification permission was not granted.", "This source was checked recently. Please wait for the next scheduled check."],
  ja: ["次回確認", "現在公開中の求人はありません。バックグラウンドで追跡を続けます。", "この端末はブラウザ通知に対応していません。", "ブラウザ通知が許可されていません。", "この提供元は最近確認済みです。次回の予定確認までお待ちください。"],
  ko: ["다음 확인", "현재 공개된 채용 공고가 없습니다. 백그라운드 추적은 계속됩니다.", "이 기기에서는 브라우저 알림을 지원하지 않습니다.", "브라우저 알림 권한이 허용되지 않았습니다.", "최근에 확인한 제공처입니다. 다음 예약 확인까지 기다려 주세요."],
  "zh-CN": ["下次检查", "目前没有公开职位，系统会继续在后台追踪。", "此设备不支持浏览器通知。", "尚未允许浏览器通知。", "此来源最近已检查，请等待下次排程检查。"],
  "zh-TW": ["下次檢查", "目前沒有公開職缺，系統會繼續在背景追蹤。", "此裝置不支援瀏覽器通知。", "尚未允許瀏覽器通知。", "此來源最近已檢查，請等待下次排程檢查。"],
  es: ["próxima revisión", "No hay vacantes publicadas en este momento. El seguimiento continuará en segundo plano.", "Este dispositivo no admite alertas del navegador.", "No se concedió permiso para las notificaciones del navegador.", "Esta fuente se revisó hace poco. Espera a la próxima revisión programada."],
  fr: ["prochain contrôle", "Aucune offre publiée n’est disponible actuellement. Le suivi continuera en arrière-plan.", "Les alertes du navigateur ne sont pas prises en charge sur cet appareil.", "L’autorisation des notifications du navigateur n’a pas été accordée.", "Cette source a été contrôlée récemment. Attendez le prochain contrôle planifié."],
  de: ["nächste Prüfung", "Derzeit wurden keine veröffentlichten Stellen gefunden. Das Tracking läuft im Hintergrund weiter.", "Browser-Benachrichtigungen werden auf diesem Gerät nicht unterstützt.", "Die Berechtigung für Browser-Benachrichtigungen wurde nicht erteilt.", "Diese Quelle wurde kürzlich geprüft. Bitte warte auf die nächste geplante Prüfung."],
  "pt-BR": ["próxima verificação", "Nenhuma vaga publicada foi encontrada no momento. O acompanhamento continuará em segundo plano.", "Este dispositivo não oferece suporte a alertas do navegador.", "A permissão para notificações do navegador não foi concedida.", "Esta fonte foi verificada recentemente. Aguarde a próxima verificação programada."],
  it: ["prossimo controllo", "Al momento non sono state trovate posizioni pubblicate. Il monitoraggio continuerà in background.", "Gli avvisi del browser non sono supportati su questo dispositivo.", "L’autorizzazione alle notifiche del browser non è stata concessa.", "Questa fonte è stata controllata di recente. Attendi il prossimo controllo programmato."],
  nl: ["volgende controle", "Er zijn momenteel geen gepubliceerde vacatures gevonden. Het volgen gaat op de achtergrond door.", "Browsermeldingen worden niet ondersteund op dit apparaat.", "Toestemming voor browsermeldingen is niet verleend.", "Deze bron is onlangs gecontroleerd. Wacht op de volgende geplande controle."],
  pl: ["następna kontrola", "Obecnie nie znaleziono opublikowanych ofert. Śledzenie będzie kontynuowane w tle.", "Alerty przeglądarki nie są obsługiwane na tym urządzeniu.", "Nie udzielono zgody na powiadomienia przeglądarki.", "To źródło sprawdzono niedawno. Poczekaj na następną zaplanowaną kontrolę."],
  tr: ["sonraki kontrol", "Şu anda yayımlanmış ilan bulunamadı. Arka planda takip devam edecek.", "Bu cihazda tarayıcı bildirimleri desteklenmiyor.", "Tarayıcı bildirimi izni verilmedi.", "Bu kaynak yakın zamanda kontrol edildi. Sonraki planlı kontrolü bekleyin."],
  ru: ["следующая проверка", "Сейчас опубликованных вакансий нет. Фоновое отслеживание продолжится.", "Уведомления браузера не поддерживаются на этом устройстве.", "Разрешение на уведомления браузера не предоставлено.", "Источник недавно проверялся. Дождитесь следующей запланированной проверки."],
  uk: ["наступна перевірка", "Наразі опублікованих вакансій немає. Фонове відстеження продовжиться.", "Сповіщення браузера не підтримуються на цьому пристрої.", "Дозвіл на сповіщення браузера не надано.", "Це джерело нещодавно перевіряли. Зачекайте наступної запланованої перевірки."],
  ar: ["التحقق التالي", "لا توجد وظائف منشورة حاليًا. سيستمر التتبّع في الخلفية.", "تنبيهات المتصفح غير مدعومة على هذا الجهاز.", "لم يتم منح إذن إشعارات المتصفح.", "تم التحقق من هذا المصدر مؤخرًا. انتظر التحقق المجدول التالي."],
  he: ["הבדיקה הבאה", "לא נמצאו כרגע משרות שפורסמו. המעקב יימשך ברקע.", "התראות דפדפן אינן נתמכות במכשיר הזה.", "לא ניתנה הרשאה להתראות דפדפן.", "המקור נבדק לאחרונה. יש להמתין לבדיקה המתוזמנת הבאה."],
  hi: ["अगली जाँच", "अभी कोई प्रकाशित नौकरी नहीं मिली। बैकग्राउंड ट्रैकिंग जारी रहेगी।", "इस डिवाइस पर ब्राउज़र अलर्ट समर्थित नहीं हैं।", "ब्राउज़र सूचना की अनुमति नहीं दी गई।", "इस स्रोत की हाल में जाँच हुई है। अगली निर्धारित जाँच की प्रतीक्षा करें।"],
  bn: ["পরবর্তী পরীক্ষা", "বর্তমানে কোনো প্রকাশিত চাকরি পাওয়া যায়নি। পটভূমিতে ট্র্যাকিং চলবে।", "এই ডিভাইসে ব্রাউজার সতর্কতা সমর্থিত নয়।", "ব্রাউজার বিজ্ঞপ্তির অনুমতি দেওয়া হয়নি।", "উৎসটি সম্প্রতি পরীক্ষা করা হয়েছে। পরবর্তী নির্ধারিত পরীক্ষার জন্য অপেক্ষা করুন।"],
  ur: ["اگلی جانچ", "اس وقت کوئی شائع شدہ ملازمت نہیں ملی۔ پس منظر میں نگرانی جاری رہے گی۔", "اس آلے پر براؤزر الرٹس دستیاب نہیں ہیں۔", "براؤزر اطلاعات کی اجازت نہیں دی گئی۔", "اس ماخذ کو حال ہی میں جانچا گیا ہے۔ اگلی طے شدہ جانچ کا انتظار کریں۔"],
  id: ["pemeriksaan berikutnya", "Saat ini tidak ada lowongan yang dipublikasikan. Pelacakan akan tetap berjalan di latar belakang.", "Peringatan browser tidak didukung di perangkat ini.", "Izin notifikasi browser tidak diberikan.", "Sumber ini baru saja diperiksa. Tunggu pemeriksaan terjadwal berikutnya."],
  ms: ["semakan seterusnya", "Tiada jawatan diterbitkan ditemui buat masa ini. Penjejakan akan diteruskan di latar belakang.", "Amaran pelayar tidak disokong pada peranti ini.", "Kebenaran pemberitahuan pelayar tidak diberikan.", "Sumber ini baru disemak. Tunggu semakan berjadual seterusnya."],
  th: ["ตรวจสอบครั้งถัดไป", "ขณะนี้ไม่พบงานที่ประกาศ ระบบจะติดตามต่อในเบื้องหลัง", "อุปกรณ์นี้ไม่รองรับการแจ้งเตือนของเบราว์เซอร์", "ยังไม่ได้อนุญาตการแจ้งเตือนของเบราว์เซอร์", "เพิ่งตรวจสอบแหล่งข้อมูลนี้ โปรดรอการตรวจสอบตามกำหนดครั้งถัดไป"],
  vi: ["lần kiểm tra tiếp theo", "Hiện chưa có việc làm nào được đăng. Hệ thống sẽ tiếp tục theo dõi trong nền.", "Thiết bị này không hỗ trợ cảnh báo trình duyệt.", "Quyền thông báo của trình duyệt chưa được cấp.", "Nguồn này vừa được kiểm tra. Hãy chờ lần kiểm tra theo lịch tiếp theo."],
  fil: ["susunod na pagsusuri", "Walang kasalukuyang naka-publish na trabaho. Magpapatuloy ang pagsubaybay sa background.", "Hindi sinusuportahan ng device na ito ang browser alerts.", "Hindi pinayagan ang browser notifications.", "Nasuri kamakailan ang source na ito. Hintayin ang susunod na naka-iskedyul na pagsusuri."],
  sv: ["nästa kontroll", "Inga publicerade jobb hittades just nu. Spårningen fortsätter i bakgrunden.", "Webbläsaraviseringar stöds inte på den här enheten.", "Tillstånd för webbläsaraviseringar beviljades inte.", "Källan kontrollerades nyligen. Vänta på nästa schemalagda kontroll."],
  no: ["neste kontroll", "Ingen publiserte jobber ble funnet nå. Sporingen fortsetter i bakgrunnen.", "Nettleservarsler støttes ikke på denne enheten.", "Tillatelse til nettleservarsler ble ikke gitt.", "Kilden ble nylig kontrollert. Vent på neste planlagte kontroll."],
  da: ["næste kontrol", "Der blev ikke fundet nogen aktuelle jobopslag. Sporingen fortsætter i baggrunden.", "Browseradvarsler understøttes ikke på denne enhed.", "Tilladelse til browsernotifikationer blev ikke givet.", "Kilden blev kontrolleret for nylig. Vent på næste planlagte kontrol."],
  fi: ["seuraava tarkistus", "Julkaistuja työpaikkoja ei löytynyt juuri nyt. Seuranta jatkuu taustalla.", "Selainilmoituksia ei tueta tällä laitteella.", "Selaimen ilmoituslupaa ei myönnetty.", "Lähde tarkistettiin äskettäin. Odota seuraavaa ajastettua tarkistusta."],
  cs: ["další kontrola", "Momentálně nebyly nalezeny žádné zveřejněné pozice. Sledování bude pokračovat na pozadí.", "Upozornění prohlížeče nejsou na tomto zařízení podporována.", "Oprávnění k oznámením prohlížeče nebylo uděleno.", "Zdroj byl nedávno zkontrolován. Počkejte na další plánovanou kontrolu."],
  sk: ["ďalšia kontrola", "Momentálne neboli nájdené žiadne zverejnené pozície. Sledovanie bude pokračovať na pozadí.", "Upozornenia prehliadača nie sú na tomto zariadení podporované.", "Povolenie upozornení prehliadača nebolo udelené.", "Zdroj bol nedávno skontrolovaný. Počkajte na ďalšiu plánovanú kontrolu."],
  hu: ["következő ellenőrzés", "Jelenleg nincs közzétett állás. A követés a háttérben folytatódik.", "A böngészőértesítések nem támogatottak ezen az eszközön.", "A böngésző értesítési engedélye nincs megadva.", "Ezt a forrást nemrég ellenőriztük. Várd meg a következő ütemezett ellenőrzést."],
  ro: ["următoarea verificare", "Momentan nu au fost găsite posturi publicate. Urmărirea va continua în fundal.", "Alertele de browser nu sunt acceptate pe acest dispozitiv.", "Permisiunea pentru notificările browserului nu a fost acordată.", "Sursa a fost verificată recent. Așteaptă următoarea verificare programată."],
  el: ["επόμενος έλεγχος", "Δεν βρέθηκαν δημοσιευμένες θέσεις αυτή τη στιγμή. Η παρακολούθηση θα συνεχιστεί στο παρασκήνιο.", "Οι ειδοποιήσεις προγράμματος περιήγησης δεν υποστηρίζονται σε αυτή τη συσκευή.", "Δεν δόθηκε άδεια για ειδοποιήσεις προγράμματος περιήγησης.", "Η πηγή ελέγχθηκε πρόσφατα. Περιμένετε τον επόμενο προγραμματισμένο έλεγχο."],
  bg: ["следваща проверка", "В момента няма публикувани позиции. Проследяването ще продължи във фонов режим.", "Известията на браузъра не се поддържат на това устройство.", "Не е дадено разрешение за известия на браузъра.", "Източникът беше проверен наскоро. Изчакайте следващата планирана проверка."],
  hr: ["sljedeća provjera", "Trenutačno nema objavljenih poslova. Praćenje će se nastaviti u pozadini.", "Obavijesti preglednika nisu podržane na ovom uređaju.", "Dopuštenje za obavijesti preglednika nije dano.", "Izvor je nedavno provjeren. Pričekajte sljedeću zakazanu provjeru."],
  sr: ["следећа провера", "Тренутно нема објављених послова. Праћење ће се наставити у позадини.", "Обавештења прегледача нису подржана на овом уређају.", "Дозвола за обавештења прегледача није дата.", "Извор је недавно проверен. Сачекајте следећу заказану проверу."],
  sl: ["naslednje preverjanje", "Trenutno ni objavljenih delovnih mest. Sledenje se bo nadaljevalo v ozadju.", "Opozorila brskalnika v tej napravi niso podprta.", "Dovoljenje za obvestila brskalnika ni bilo odobreno.", "Vir je bil nedavno preverjen. Počakajte na naslednje načrtovano preverjanje."],
  sw: ["ukaguzi unaofuata", "Hakuna nafasi zilizochapishwa kwa sasa. Ufuatiliaji utaendelea chinichini.", "Arifa za kivinjari hazitumiki kwenye kifaa hiki.", "Ruhusa ya arifa za kivinjari haikutolewa.", "Chanzo hiki kilikaguliwa hivi karibuni. Subiri ukaguzi unaofuata uliopangwa."],
  fa: ["بررسی بعدی", "در حال حاضر فرصت شغلی منتشرشده‌ای یافت نشد. پیگیری در پس‌زمینه ادامه می‌یابد.", "اعلان‌های مرورگر در این دستگاه پشتیبانی نمی‌شوند.", "مجوز اعلان مرورگر داده نشده است.", "این منبع اخیراً بررسی شده است. تا بررسی زمان‌بندی‌شده بعدی صبر کنید."],
};

export function jobTrackingRuntimeCopyFor(locale: LocaleCode): JobTrackingRuntimeCopy {
  const [nextCheckAt, noActiveJobs, browserUnsupported, browserDenied, refreshThrottled] = RUNTIME_COPY[locale];
  return { nextCheckAt, noActiveJobs, browserUnsupported, browserDenied, refreshThrottled };
}
