export const TECHNICAL_RESOURCE_TAGS = [
  "behavioral",
  "coding",
  "system-design",
  "frontend",
  "backend",
  "data-sql",
  "data-science",
  "ml-ai",
  "security",
  "devops-cloud",
  "mobile",
  "qa-testing",
  "product-case",
] as const;

export type TechnicalResourceTag = (typeof TECHNICAL_RESOURCE_TAGS)[number];
export type TechnicalResourceAccess = "free" | "freemium" | "mixed" | "paid";
export type TechnicalResourceFormat =
  | "challenge"
  | "community"
  | "course"
  | "guide"
  | "handbook"
  | "lab"
  | "platform"
  | "practice"
  | "reference"
  | "repository";

export type TechnicalResource = Readonly<{
  id: string;
  name: string;
  href: string;
  tags: readonly TechnicalResourceTag[];
  access: TechnicalResourceAccess;
  format: TechnicalResourceFormat;
  provider: "official" | "community";
  license: string;
  licenseHref?: string;
  bestFor: string;
  sourceNote: string;
}>;

export const TECHNICAL_RESOURCES: readonly TechnicalResource[] = [
  {
    id: "tech-interview-handbook",
    name: "Tech Interview Handbook",
    href: "https://www.techinterviewhandbook.org/",
    tags: ["behavioral", "coding", "frontend", "backend", "system-design", "qa-testing"],
    access: "free",
    format: "handbook",
    provider: "community",
    license: "MIT",
    licenseHref: "https://github.com/yangshun/tech-interview-handbook/blob/main/LICENSE",
    bestFor: "Study plans, coding rounds, behavioral stories, and interview-day checklists",
    sourceNote: "Maintainer-published handbook; outbound link only",
  },
  {
    id: "coding-interview-university",
    name: "Coding Interview University",
    href: "https://github.com/jwasham/coding-interview-university",
    tags: ["coding", "backend", "system-design"],
    access: "free",
    format: "guide",
    provider: "community",
    license: "CC BY-SA 4.0",
    licenseHref: "https://github.com/jwasham/coding-interview-university/blob/main/LICENSE.txt",
    bestFor: "A structured computer-science and coding-interview study plan",
    sourceNote: "Public open-source curriculum; outbound link only",
  },
  {
    id: "leetcode-problem-set",
    name: "LeetCode Problem Set",
    href: "https://leetcode.com/problemset/",
    tags: ["coding", "data-sql"],
    access: "freemium",
    format: "platform",
    provider: "official",
    license: "",
    bestFor: "Timed algorithms, data structures, database questions, and company-style practice",
    sourceNote: "Official LeetCode platform; proprietary content, link only",
  },
  {
    id: "hackerrank-interview-preparation-kit",
    name: "HackerRank Interview Preparation Kit",
    href: "https://www.hackerrank.com/interview/interview-preparation-kit",
    tags: ["coding", "data-sql"],
    access: "freemium",
    format: "platform",
    provider: "official",
    license: "",
    bestFor: "Topic-based coding drills with timed assessments",
    sourceNote: "Official HackerRank preparation path; proprietary content, link only",
  },
  {
    id: "exercism",
    name: "Exercism",
    href: "https://exercism.org/tracks",
    tags: ["coding"],
    access: "free",
    format: "practice",
    provider: "community",
    license: "Mixed open-source licenses; link only",
    bestFor: "Language fluency, tests, iterative exercises, and mentor feedback",
    sourceNote: "Community learning platform; licenses vary by track and content type",
  },
  {
    id: "the-algorithms-python",
    name: "The Algorithms · Python",
    href: "https://github.com/TheAlgorithms/Python",
    tags: ["coding", "data-science"],
    access: "free",
    format: "repository",
    provider: "community",
    license: "MIT",
    licenseHref: "https://github.com/TheAlgorithms/Python/blob/master/LICENSE.md",
    bestFor: "Reviewing readable implementations of common algorithms and data structures",
    sourceNote: "Community educational repository; not presented as an interview question bank",
  },
  {
    id: "system-design-primer",
    name: "System Design Primer",
    href: "https://github.com/donnemartin/system-design-primer",
    tags: ["system-design", "backend", "devops-cloud"],
    access: "free",
    format: "handbook",
    provider: "community",
    license: "CC BY 4.0",
    licenseHref: "https://github.com/donnemartin/system-design-primer/blob/master/LICENSE.txt",
    bestFor: "Scalability, trade-offs, architecture questions, and design walkthroughs",
    sourceNote: "Open-source system-design guide; outbound link only",
  },
  {
    id: "build-your-own-x",
    name: "Build Your Own X",
    href: "https://github.com/codecrafters-io/build-your-own-x",
    tags: ["coding", "backend", "system-design"],
    access: "free",
    format: "repository",
    provider: "community",
    license: "CC0-1.0 index; linked tutorials vary",
    licenseHref: "https://github.com/codecrafters-io/build-your-own-x/blob/master/LICENSE",
    bestFor: "Learning systems by implementing databases, networks, tools, and runtimes",
    sourceNote: "Curated index; each linked tutorial retains its own terms",
  },
  {
    id: "front-end-interview-handbook",
    name: "Front End Interview Handbook",
    href: "https://www.frontendinterviewhandbook.com/",
    tags: ["frontend", "system-design", "behavioral", "qa-testing"],
    access: "free",
    format: "handbook",
    provider: "community",
    license: "MIT",
    licenseHref: "https://github.com/yangshun/front-end-interview-handbook/blob/main/LICENSE",
    bestFor: "HTML, CSS, JavaScript, browser fundamentals, and front-end system design",
    sourceNote: "Maintainer-published handbook; outbound link only",
  },
  {
    id: "h5bp-front-end-interview-questions",
    name: "H5BP Front-end Interview Questions",
    href: "https://github.com/h5bp/Front-end-Developer-Interview-Questions",
    tags: ["frontend", "qa-testing", "security"],
    access: "free",
    format: "repository",
    provider: "community",
    license: "MIT",
    licenseHref: "https://github.com/h5bp/Front-end-Developer-Interview-Questions/blob/main/LICENSE.md",
    bestFor: "Accessibility, performance, testing, networking, HTML, CSS, and JavaScript review",
    sourceNote: "Open-source question collection; attribution retained at the source",
  },
  {
    id: "mdn-learn-web-development",
    name: "MDN Learn Web Development",
    href: "https://developer.mozilla.org/en-US/docs/Learn_web_development",
    tags: ["frontend", "qa-testing"],
    access: "free",
    format: "course",
    provider: "official",
    license: "",
    bestFor: "Standards-based front-end fundamentals, tutorials, and practical challenges",
    sourceNote: "Official MDN curriculum; outbound link only",
  },
  {
    id: "web-dev-learn",
    name: "web.dev Learn",
    href: "https://web.dev/learn/",
    tags: ["frontend", "qa-testing"],
    access: "free",
    format: "course",
    provider: "official",
    license: "",
    bestFor: "Accessibility, performance, testing, HTML, CSS, JavaScript, and web platform skills",
    sourceNote: "Official Google web learning collection; outbound link only",
  },
  {
    id: "postgresql-exercises",
    name: "PostgreSQL Exercises",
    href: "https://pgexercises.com/",
    tags: ["data-sql", "backend"],
    access: "free",
    format: "practice",
    provider: "community",
    license: "BSD-style top-level license; subdirectories vary",
    licenseHref: "https://github.com/AlisdairO/pgexercises/blob/master/LICENSE",
    bestFor: "Progressive SQL practice from SELECT statements through window functions",
    sourceNote: "Community practice site; outbound link is the safest integration",
  },
  {
    id: "sqlzoo",
    name: "SQLZoo",
    href: "https://sqlzoo.net/wiki/SQL_Tutorial",
    tags: ["data-sql", "data-science"],
    access: "free",
    format: "practice",
    provider: "community",
    license: "Link only · site terms",
    bestFor: "Step-by-step SQL tutorials, quizzes, and graded assessments",
    sourceNote: "Community tutorial site; question content is not imported",
  },
  {
    id: "sql-murder-mystery",
    name: "SQL Murder Mystery",
    href: "https://mystery.knightlab.com/",
    tags: ["data-sql"],
    access: "free",
    format: "challenge",
    provider: "community",
    license: "MIT and CC BY-SA 4.0",
    licenseHref: "https://github.com/NUKnightLab/sql-mysteries",
    bestFor: "SQL joins, filtering, investigation, and query reasoning",
    sourceNote: "Knight Lab educational challenge; outbound link only",
  },
  {
    id: "data-engineering-interview-handbook",
    name: "Data Engineering Interview Handbook",
    href: "https://github.com/datadriven-io/data-engineering-interview-handbook",
    tags: ["data-sql", "data-science", "backend", "system-design"],
    access: "free",
    format: "handbook",
    provider: "community",
    license: "CC BY-SA 4.0",
    licenseHref: "https://github.com/datadriven-io/data-engineering-interview-handbook/blob/main/LICENSE",
    bestFor: "SQL, Python, data modeling, pipelines, system design, and behavioral preparation",
    sourceNote: "Community-maintained handbook; verify current repository maturity before relying on it",
  },
  {
    id: "data-engineering-zoomcamp",
    name: "Data Engineering Zoomcamp",
    href: "https://github.com/DataTalksClub/data-engineering-zoomcamp",
    tags: ["data-sql", "data-science", "devops-cloud"],
    access: "free",
    format: "course",
    provider: "community",
    license: "Link only · repository terms",
    bestFor: "End-to-end data pipelines, orchestration, warehouses, streaming, and cloud workflows",
    sourceNote: "Community course repository; outbound link only",
  },
  {
    id: "ml-interviews-book",
    name: "Machine Learning Interviews Book",
    href: "https://huyenchip.com/ml-interviews-book/",
    tags: ["ml-ai", "data-science", "behavioral"],
    access: "free",
    format: "handbook",
    provider: "community",
    license: "Link only · copyright retained",
    bestFor: "ML fundamentals, systems, research, product judgment, and interview process",
    sourceNote: "Author-published book; question wording is not imported or translated",
  },
  {
    id: "google-ml-crash-course",
    name: "Google Machine Learning Crash Course",
    href: "https://developers.google.com/machine-learning/crash-course/",
    tags: ["ml-ai", "data-science"],
    access: "free",
    format: "course",
    provider: "official",
    license: "",
    bestFor: "Practical ML concepts with videos, visualizations, and hands-on exercises",
    sourceNote: "Official Google course; outbound link only",
  },
  {
    id: "made-with-ml",
    name: "Made With ML",
    href: "https://madewithml.com/",
    tags: ["ml-ai", "data-science", "devops-cloud"],
    access: "free",
    format: "course",
    provider: "community",
    license: "MIT",
    licenseHref: "https://github.com/GokuMohandas/Made-With-ML/blob/main/LICENSE",
    bestFor: "Designing, developing, deploying, and iterating on production ML systems",
    sourceNote: "Open-source production-ML curriculum; outbound link only",
  },
  {
    id: "full-stack-deep-learning",
    name: "Full Stack Deep Learning",
    href: "https://fullstackdeeplearning.com/course/",
    tags: ["ml-ai", "data-science", "system-design"],
    access: "free",
    format: "course",
    provider: "community",
    license: "Link only · course terms",
    bestFor: "ML product design, data, experimentation, deployment, and operations",
    sourceNote: "Community course; outbound link only",
  },
  {
    id: "machine-learning-systems-design",
    name: "Machine Learning Systems Design",
    href: "https://github.com/chiphuyen/machine-learning-systems-design",
    tags: ["ml-ai", "data-science", "system-design"],
    access: "free",
    format: "guide",
    provider: "community",
    license: "Link only · no reuse license stated",
    bestFor: "ML problem framing, data, evaluation, serving, monitoring, and trade-offs",
    sourceNote: "Public repository without a verified reuse license; link only",
  },
  {
    id: "owasp-web-security-testing-guide",
    name: "OWASP Web Security Testing Guide",
    href: "https://owasp.org/www-project-web-security-testing-guide/",
    tags: ["security", "qa-testing"],
    access: "free",
    format: "handbook",
    provider: "community",
    license: "CC BY-SA 4.0",
    licenseHref: "https://github.com/OWASP/wstg/blob/master/LICENSE",
    bestFor: "A structured framework for web application security testing",
    sourceNote: "OWASP community project; outbound link only",
  },
  {
    id: "owasp-webgoat",
    name: "OWASP WebGoat",
    href: "https://owasp.org/www-project-webgoat/",
    tags: ["security", "backend"],
    access: "free",
    format: "lab",
    provider: "community",
    license: "GPL-2.0",
    licenseHref: "https://github.com/WebGoat/WebGoat/blob/main/LICENSE",
    bestFor: "Learning vulnerabilities, exploitation, mitigation, and secure design in a safe lab",
    sourceNote: "Deliberately insecure OWASP training application; use only in an authorized environment",
  },
  {
    id: "owasp-juice-shop",
    name: "OWASP Juice Shop",
    href: "https://owasp.org/www-project-juice-shop/",
    tags: ["security", "frontend", "backend", "qa-testing"],
    access: "free",
    format: "lab",
    provider: "community",
    license: "MIT",
    licenseHref: "https://github.com/juice-shop/juice-shop/blob/master/LICENSE",
    bestFor: "Hands-on web security challenges with a tracked scoreboard",
    sourceNote: "Deliberately insecure OWASP training application; use only in an authorized environment",
  },
  {
    id: "portswigger-web-security-academy",
    name: "PortSwigger Web Security Academy",
    href: "https://portswigger.net/web-security",
    tags: ["security", "qa-testing"],
    access: "free",
    format: "lab",
    provider: "official",
    license: "",
    bestFor: "Continuously updated learning paths and interactive application-security labs",
    sourceNote: "Official PortSwigger training center; proprietary lab content, link only",
  },
  {
    id: "owasp-nodegoat",
    name: "OWASP NodeGoat",
    href: "https://github.com/OWASP/NodeGoat",
    tags: ["security", "backend"],
    access: "free",
    format: "lab",
    provider: "community",
    license: "Apache-2.0",
    licenseHref: "https://github.com/OWASP/NodeGoat/blob/master/LICENSE",
    bestFor: "Node.js security risks, exploitation, remediation, and secure coding",
    sourceNote: "OWASP training application; use only in an authorized environment",
  },
  {
    id: "docker-workshop",
    name: "Docker Workshop",
    href: "https://docs.docker.com/get-started/workshop/",
    tags: ["devops-cloud", "backend"],
    access: "free",
    format: "course",
    provider: "official",
    license: "",
    bestFor: "Images, containers, multi-container apps, Compose, and development workflows",
    sourceNote: "Official Docker hands-on workshop; outbound link only",
  },
  {
    id: "kubernetes-tutorials",
    name: "Kubernetes Tutorials",
    href: "https://kubernetes.io/docs/tutorials/",
    tags: ["devops-cloud", "backend", "system-design"],
    access: "free",
    format: "course",
    provider: "official",
    license: "",
    bestFor: "Cluster basics, workloads, services, configuration, security, and observability",
    sourceNote: "Official Kubernetes documentation and interactive tutorials; outbound link only",
  },
  {
    id: "terraform-tutorials",
    name: "HashiCorp Terraform Tutorials",
    href: "https://developer.hashicorp.com/terraform/tutorials",
    tags: ["devops-cloud", "system-design"],
    access: "mixed",
    format: "course",
    provider: "official",
    license: "",
    bestFor: "Infrastructure as code, state, modules, workflows, and multi-cloud provisioning",
    sourceNote: "Official HashiCorp tutorials; some exercises may require provider accounts",
  },
  {
    id: "google-sre-books",
    name: "Google SRE Books",
    href: "https://sre.google/books/",
    tags: ["devops-cloud", "system-design", "behavioral"],
    access: "free",
    format: "reference",
    provider: "official",
    license: "",
    bestFor: "Reliability, incident response, SLOs, operations, and engineering trade-offs",
    sourceNote: "Official free-to-read Google SRE books; link only because reuse terms vary",
  },
  {
    id: "android-basics-compose",
    name: "Android Basics with Compose",
    href: "https://developer.android.com/courses/android-basics-compose/course",
    tags: ["mobile", "frontend", "qa-testing"],
    access: "free",
    format: "course",
    provider: "official",
    license: "",
    bestFor: "Kotlin, Compose UI, app architecture, data, networking, and testing",
    sourceNote: "Official Android Developers course; outbound link only",
  },
  {
    id: "apple-app-development-tutorials",
    name: "Apple App Development Tutorials",
    href: "https://developer.apple.com/tutorials/app-dev-training",
    tags: ["mobile", "frontend", "qa-testing"],
    access: "free",
    format: "course",
    provider: "official",
    license: "",
    bestFor: "Swift, SwiftUI, UIKit, data flow, navigation, and app architecture",
    sourceNote: "Official Apple developer training; outbound link only",
  },
  {
    id: "playwright-documentation",
    name: "Playwright Documentation",
    href: "https://playwright.dev/docs/intro",
    tags: ["qa-testing", "frontend"],
    access: "free",
    format: "guide",
    provider: "official",
    license: "",
    bestFor: "Reliable end-to-end testing, fixtures, isolation, assertions, and debugging",
    sourceNote: "Official Playwright documentation; outbound link only",
  },
  {
    id: "testing-library-documentation",
    name: "Testing Library Documentation",
    href: "https://testing-library.com/docs/",
    tags: ["qa-testing", "frontend"],
    access: "free",
    format: "guide",
    provider: "official",
    license: "",
    bestFor: "User-centered component testing, queries, interactions, and accessibility",
    sourceNote: "Official Testing Library documentation; outbound link only",
  },
  {
    id: "amazon-leadership-principles",
    name: "Amazon Leadership Principles",
    href: "https://www.amazon.jobs/content/en/our-workplace/leadership-principles",
    tags: ["behavioral", "product-case"],
    access: "free",
    format: "reference",
    provider: "official",
    license: "",
    bestFor: "Translating real evidence into values-based behavioral examples",
    sourceNote: "Official employer framework; proprietary content, link only",
  },
  {
    id: "amazon-product-manager-interview-prep",
    name: "Amazon Product Manager Interview Prep",
    href: "https://www.amazon.jobs/content/en-gb/how-we-hire/product-manager-interview-prep",
    tags: ["behavioral", "product-case", "data-science"],
    access: "free",
    format: "guide",
    provider: "official",
    license: "",
    bestFor: "Product judgment, metrics, stakeholder communication, writing, and behavioral preparation",
    sourceNote: "Official employer interview guide; proprietary content, link only",
  },
  {
    id: "mckinsey-interviewing",
    name: "McKinsey Interviewing",
    href: "https://www.mckinsey.com/careers/interviewing",
    tags: ["behavioral", "product-case"],
    access: "free",
    format: "guide",
    provider: "official",
    license: "",
    bestFor: "Personal-experience interviews, structured problem solving, and case practice",
    sourceNote: "Official employer preparation guidance; proprietary content, link only",
  },
  {
    id: "bcg-case-interview-preparation",
    name: "BCG Case Interview Preparation",
    href: "https://careers.bcg.com/global/en/case-interview-preparation",
    tags: ["behavioral", "product-case", "data-science"],
    access: "free",
    format: "practice",
    provider: "official",
    license: "",
    bestFor: "Case framing, quantitative reasoning, synthesis, and interactive practice",
    sourceNote: "Official employer case preparation; proprietary content, link only",
  },
  {
    id: "bain-interview-preparation",
    name: "Bain Interview Preparation",
    href: "https://www.bain.com/careers/interview-preparation/experience-interview.aspx",
    tags: ["behavioral", "product-case"],
    access: "free",
    format: "guide",
    provider: "official",
    license: "",
    bestFor: "Experience interviews, case studies, communication, and recommendation structure",
    sourceNote: "Official employer interview preparation; proprietary content, link only",
  },
] as const;

export function technicalResourcesForPersona(
  requestedTags: readonly string[],
  limit = 6,
): TechnicalResource[] {
  if (limit <= 0 || requestedTags.length === 0) return [];

  const requested = new Set(requestedTags);
  return TECHNICAL_RESOURCES.map((resource, index) => ({
    resource,
    index,
    overlap: resource.tags.filter((tag) => requested.has(tag)).length,
  }))
    .filter(({ overlap }) => overlap > 0)
    .sort(
      (left, right) =>
        right.overlap - left.overlap ||
        Number(right.resource.provider === "official") -
          Number(left.resource.provider === "official") ||
        left.index - right.index,
    )
    .slice(0, limit)
    .map(({ resource }) => ({ ...resource, tags: [...resource.tags] }));
}
