import type { LocaleCode } from "./i18n";

export type MicrophoneConsentCopy = {
  title: string;
  cloudBody: string;
  browserBody: string;
  cloudButton: string;
  browserButton: string;
  typeButton: string;
  privacyLink: string;
  coachedButton: string;
  coachedNotice: string;
  coachedReady: string;
  coachedUnavailable: string;
};

export const MICROPHONE_CONSENT_COPY = {
  en: {
    title: "Use your microphone?",
    cloudBody: "When signed in, your browser creates a live draft. After you stop, the audio, selected language, and up to 80 role terms go to ElevenLabs Scribe first, with Microsoft Azure Speech as a fallback. InterviewThread does not store or log the raw audio; providers may process or retain it under their policies. Nothing is submitted until you review and press Send.",
    browserBody: "Your browser creates captions and may use its vendor’s speech service. InterviewThread does not upload or save audio. Nothing is submitted automatically.",
    cloudButton: "Use cloud voice", browserButton: "Use browser captions", typeButton: "Type instead", privacyLink: "Privacy", coachedButton: "Try coached voice",
    coachedNotice: "Coached voice requires separate consent each time. The current recording is sent to ElevenLabs to return a transformed practice voice. The returned audio is kept only temporarily in this browser for playback and is not automatically submitted. InterviewThread does not store or log it; ElevenLabs may process or retain it under its policy.",
    coachedReady: "Coached voice ready", coachedUnavailable: "Coached voice unavailable",
  },
  ja: {
    title: "マイクを使用しますか？",
    cloudBody: "サインイン中は、ブラウザーにリアルタイムの下書きが表示されます。録音を止めると、音声、選択した言語、最大80件の職務用語がまず ElevenLabs に送信され、利用できない場合は Azure が使われます。InterviewThread は音声を保存・記録しませんが、各提供元はそれぞれのポリシーに基づいて処理・保持する場合があります。内容を確認して「送信」を押すまで、回答は送信されません。",
    browserBody: "ブラウザーが字幕を作成し、ブラウザー提供元の音声サービスを使用する場合があります。InterviewThread は音声をアップロード・保存せず、回答も自動送信しません。",
    cloudButton: "クラウド音声を使う", browserButton: "ブラウザー字幕を使う", typeButton: "文字で入力", privacyLink: "プライバシー", coachedButton: "コーチ音声を試す",
    coachedNotice: "現在の録音が別途 ElevenLabs に送信され、練習用に変換された音声が返されます。InterviewThread は保存しません。ElevenLabs のポリシーが適用されます。",
    coachedReady: "コーチ音声の準備完了", coachedUnavailable: "コーチ音声を利用できません",
  },
  ko: {
    title: "마이크를 사용하시겠어요?",
    cloudBody: "로그인한 경우 브라우저에 실시간 초안이 표시됩니다. 녹음을 멈추면 오디오, 선택한 언어, 최대 80개의 직무 용어가 먼저 ElevenLabs로 전송되고, 실패하면 Azure가 사용됩니다. InterviewThread는 오디오를 저장하거나 기록하지 않지만 제공업체는 각 정책에 따라 처리하거나 보관할 수 있습니다. 내용을 검토하고 ‘보내기’를 누르기 전에는 답변이 제출되지 않습니다.",
    browserBody: "브라우저가 자막을 만들며 브라우저 제공업체의 음성 서비스를 사용할 수 있습니다. InterviewThread는 오디오를 업로드하거나 저장하지 않으며 답변도 자동 제출하지 않습니다.",
    cloudButton: "클라우드 음성 사용", browserButton: "브라우저 자막 사용", typeButton: "직접 입력", privacyLink: "개인정보", coachedButton: "코칭 음성 체험",
    coachedNotice: "현재 녹음이 별도로 ElevenLabs에 전송되어 연습용으로 변환된 음성이 반환됩니다. InterviewThread는 저장하지 않으며 ElevenLabs 정책이 적용됩니다.",
    coachedReady: "코칭 음성 준비 완료", coachedUnavailable: "코칭 음성을 사용할 수 없음",
  },
  "zh-CN": {
    title: "使用麦克风？",
    cloudBody: "登录后，浏览器会实时生成草稿。停止录音后，音频、所选语言和最多 80 个职位术语会先发送给 ElevenLabs Scribe；若不可用，则改用 Microsoft Azure Speech。InterviewThread 不存储或记录原始音频；服务商可能按各自政策处理或保留数据。在你检查内容并点击“发送”前，不会提交任何内容。",
    browserBody: "浏览器会生成字幕，并可能使用其供应商的语音服务。InterviewThread 不会上传或保存音频，也不会自动提交任何内容。",
    cloudButton: "使用云端语音", browserButton: "使用浏览器字幕", typeButton: "改用文字", privacyLink: "隐私", coachedButton: "试用教练语音",
    coachedNotice: "每次使用教练语音都需要单独同意。当前录音会发送给 ElevenLabs，以返回经过转换的练习语音；返回的音频只会临时保留在当前浏览器中供播放，不会自动作为答案提交。InterviewThread 不会存储或记录录音及返回音频；ElevenLabs 可能按其政策处理或保留数据。",
    coachedReady: "教练语音已就绪", coachedUnavailable: "教练语音不可用",
  },
  "zh-TW": {
    title: "使用麥克風？",
    cloudBody: "登入後，瀏覽器會即時產生草稿。停止錄音後，音訊、所選語言和最多 80 個職務用語會先傳送給 ElevenLabs Scribe；若無法使用，則改用 Microsoft Azure Speech。InterviewThread 不會儲存或記錄原始音訊；服務供應商可能依各自政策處理或保留資料。在你檢查內容並按下「傳送」前，不會提交任何內容。",
    browserBody: "瀏覽器會產生字幕，並可能使用其供應商的語音服務。InterviewThread 不會上傳或儲存音訊，也不會自動提交任何內容。",
    cloudButton: "使用雲端語音", browserButton: "使用瀏覽器字幕", typeButton: "改用文字", privacyLink: "隱私權", coachedButton: "試用教練語音",
    coachedNotice: "每次使用教練語音都需要另行同意。目前的錄音會傳送給 ElevenLabs，以傳回經轉換的練習語音；回傳音訊只會暫時保留在目前瀏覽器中供播放，不會自動當作答案送出。InterviewThread 不會儲存或記錄錄音及回傳音訊；ElevenLabs 可能依其政策處理或保留資料。",
    coachedReady: "教練語音已就緒", coachedUnavailable: "教練語音無法使用",
  },
  es: {
    title: "¿Usar el micrófono?",
    cloudBody: "Al iniciar sesión, el navegador crea un borrador en directo. Al detener la grabación, el audio, el idioma elegido y hasta 80 términos del puesto se envían primero a ElevenLabs, con Azure como alternativa. InterviewThread no almacena ni registra audio; los proveedores pueden procesarlo o conservarlo según sus políticas. No se envía nada hasta que lo revises y pulses «Enviar».",
    browserBody: "El navegador crea subtítulos y puede usar el servicio de voz de su proveedor. InterviewThread no sube ni guarda el audio. Nada se envía automáticamente.",
    cloudButton: "Usar voz en la nube", browserButton: "Usar subtítulos", typeButton: "Escribir", privacyLink: "Privacidad", coachedButton: "Probar voz guiada",
    coachedNotice: "La grabación actual se envía por separado a ElevenLabs para devolver una voz de práctica transformada. InterviewThread no la guarda; se aplica la política de ElevenLabs.",
    coachedReady: "Voz guiada lista", coachedUnavailable: "Voz guiada no disponible",
  },
  fr: {
    title: "Utiliser votre microphone ?",
    cloudBody: "Une fois connecté, votre navigateur crée un brouillon en direct. À l’arrêt de l’enregistrement, l’audio, la langue choisie et jusqu’à 80 termes liés au poste sont envoyés d’abord à ElevenLabs, avec Azure en solution de secours. InterviewThread ne stocke ni ne journalise l’audio ; les fournisseurs peuvent le traiter ou le conserver selon leurs politiques. Rien n’est envoyé avant votre vérification et un clic sur « Envoyer ».",
    browserBody: "Votre navigateur crée des sous-titres et peut utiliser le service vocal de son fournisseur. InterviewThread ne téléverse ni ne conserve l’audio. Rien n’est envoyé automatiquement.",
    cloudButton: "Utiliser la voix cloud", browserButton: "Utiliser les sous-titres", typeButton: "Écrire", privacyLink: "Confidentialité", coachedButton: "Essayer la voix coachée",
    coachedNotice: "L’enregistrement actuel est envoyé séparément à ElevenLabs afin de produire une voix d’entraînement transformée. InterviewThread ne le conserve pas ; la politique d’ElevenLabs s’applique.",
    coachedReady: "Voix coachée prête", coachedUnavailable: "Voix coachée indisponible",
  },
  de: {
    title: "Mikrofon verwenden?",
    cloudBody: "Wenn Sie angemeldet sind, erstellt Ihr Browser live einen Entwurf. Nach dem Stoppen werden Audio, ausgewählte Sprache und bis zu 80 Begriffe zur Stelle zuerst an ElevenLabs gesendet; Azure dient als Ausweichlösung. InterviewThread speichert oder protokolliert kein Audio. Anbieter können es gemäß ihren Richtlinien verarbeiten oder aufbewahren. Erst nach Ihrer Prüfung und einem Klick auf „Senden“ wird etwas übermittelt.",
    browserBody: "Ihr Browser erstellt Untertitel und kann dabei den Sprachdienst seines Anbieters nutzen. InterviewThread lädt Audio weder hoch noch speichert es. Nichts wird automatisch übermittelt.",
    cloudButton: "Cloud-Spracheingabe", browserButton: "Browser-Untertitel", typeButton: "Text eingeben", privacyLink: "Datenschutz", coachedButton: "Gecoachte Stimme testen",
    coachedNotice: "Die aktuelle Aufnahme wird separat an ElevenLabs gesendet, um eine umgewandelte Übungsstimme zurückzugeben. InterviewThread speichert sie nicht; es gilt die Richtlinie von ElevenLabs.",
    coachedReady: "Gecoachte Stimme bereit", coachedUnavailable: "Gecoachte Stimme nicht verfügbar",
  },
  "pt-BR": {
    title: "Usar o microfone?",
    cloudBody: "Ao entrar na conta, seu navegador cria um rascunho ao vivo. Quando você para, o áudio, o idioma selecionado e até 80 termos da função são enviados primeiro à ElevenLabs, com o Azure como alternativa. O InterviewThread não armazena nem registra áudio; os provedores podem processá-lo ou retê-lo conforme suas políticas. Nada é enviado até você revisar e clicar em “Enviar”.",
    browserBody: "Seu navegador cria legendas e pode usar o serviço de fala do fornecedor. O InterviewThread não envia nem salva o áudio. Nada é enviado automaticamente.",
    cloudButton: "Usar voz na nuvem", browserButton: "Usar legendas", typeButton: "Digitar", privacyLink: "Privacidade", coachedButton: "Testar voz orientada",
    coachedNotice: "A gravação atual é enviada separadamente à ElevenLabs para gerar uma voz de treino transformada. O InterviewThread não a salva; aplica-se a política da ElevenLabs.",
    coachedReady: "Voz orientada pronta", coachedUnavailable: "Voz orientada indisponível",
  },
  it: {
    title: "Usare il microfono?",
    cloudBody: "Dopo l’accesso, il browser crea una bozza in tempo reale. Quando interrompi la registrazione, l’audio, la lingua scelta e fino a 80 termini del ruolo vengono inviati prima a ElevenLabs, con Azure come alternativa. InterviewThread non archivia né registra l’audio; i fornitori possono elaborarlo o conservarlo secondo le proprie informative. Nulla viene inviato finché non controlli e premi «Invia».",
    browserBody: "Il browser crea sottotitoli e può usare il servizio vocale del proprio fornitore. InterviewThread non carica né salva l’audio. Nulla viene inviato automaticamente.",
    cloudButton: "Usa voce cloud", browserButton: "Usa sottotitoli", typeButton: "Scrivi", privacyLink: "Privacy", coachedButton: "Prova voce guidata",
    coachedNotice: "La registrazione corrente viene inviata separatamente a ElevenLabs per restituire una voce di prova trasformata. InterviewThread non la salva; si applica l’informativa di ElevenLabs.",
    coachedReady: "Voce guidata pronta", coachedUnavailable: "Voce guidata non disponibile",
  },
  nl: {
    title: "Uw microfoon gebruiken?",
    cloudBody: "Wanneer u bent ingelogd, maakt uw browser live een concept. Nadat u stopt, worden de audio, gekozen taal en maximaal 80 functietermen eerst naar ElevenLabs gestuurd, met Azure als uitwijkoptie. InterviewThread bewaart of logt geen audio; aanbieders kunnen deze volgens hun beleid verwerken of bewaren. Er wordt niets verzonden totdat u het controleert en op ‘Verzenden’ klikt.",
    browserBody: "Uw browser maakt ondertiteling en kan de spraakdienst van de leverancier gebruiken. InterviewThread uploadt of bewaart geen audio. Niets wordt automatisch verzonden.",
    cloudButton: "Cloudspraak gebruiken", browserButton: "Ondertiteling gebruiken", typeButton: "Typen", privacyLink: "Privacy", coachedButton: "Coachstem proberen",
    coachedNotice: "De huidige opname wordt apart naar ElevenLabs gestuurd om een omgezette oefenstem terug te geven. InterviewThread bewaart deze niet; het beleid van ElevenLabs is van toepassing.",
    coachedReady: "Coachstem is klaar", coachedUnavailable: "Coachstem niet beschikbaar",
  },
  pl: {
    title: "Użyć mikrofonu?",
    cloudBody: "Po zalogowaniu przeglądarka tworzy wersję roboczą na żywo. Po zatrzymaniu nagrania dźwięk, wybrany język i maksymalnie 80 terminów związanych ze stanowiskiem trafiają najpierw do ElevenLabs, a awaryjnie do Azure. InterviewThread nie przechowuje ani nie rejestruje dźwięku; dostawcy mogą go przetwarzać lub zachowywać zgodnie ze swoimi zasadami. Nic nie zostanie wysłane, dopóki nie sprawdzisz treści i nie klikniesz „Wyślij”.",
    browserBody: "Przeglądarka tworzy napisy i może korzystać z usługi rozpoznawania mowy swojego dostawcy. InterviewThread nie przesyła ani nie zapisuje dźwięku. Nic nie jest wysyłane automatycznie.",
    cloudButton: "Użyj głosu w chmurze", browserButton: "Użyj napisów", typeButton: "Wpisz tekst", privacyLink: "Prywatność", coachedButton: "Wypróbuj głos treningowy",
    coachedNotice: "Bieżące nagranie jest osobno wysyłane do ElevenLabs, aby utworzyć przekształcony głos do ćwiczeń. InterviewThread go nie zapisuje; obowiązują zasady ElevenLabs.",
    coachedReady: "Głos treningowy gotowy", coachedUnavailable: "Głos treningowy niedostępny",
  },
  tr: {
    title: "Mikrofon kullanılsın mı?",
    cloudBody: "Oturum açtığınızda tarayıcınız canlı bir taslak oluşturur. Kaydı durdurunca ses, seçilen dil ve en fazla 80 pozisyon terimi önce ElevenLabs’e, gerekirse Azure’a gönderilir. InterviewThread sesi saklamaz veya kaydetmez; sağlayıcılar kendi politikalarına göre işleyebilir ya da tutabilir. Siz inceleyip “Gönder”e basana kadar hiçbir şey gönderilmez.",
    browserBody: "Tarayıcınız altyazı oluşturur ve sağlayıcısının konuşma hizmetini kullanabilir. InterviewThread sesi yüklemez veya kaydetmez. Hiçbir şey otomatik gönderilmez.",
    cloudButton: "Bulut sesini kullan", browserButton: "Tarayıcı altyazıları", typeButton: "Yazarak yanıtla", privacyLink: "Gizlilik", coachedButton: "Koçlu sesi dene",
    coachedNotice: "Mevcut kayıt, dönüştürülmüş bir alıştırma sesi oluşturulması için ayrıca ElevenLabs’e gönderilir. InterviewThread kaydetmez; ElevenLabs politikası geçerlidir.",
    coachedReady: "Koçlu ses hazır", coachedUnavailable: "Koçlu ses kullanılamıyor",
  },
  ru: {
    title: "Использовать микрофон?",
    cloudBody: "После входа браузер создаёт черновик в реальном времени. После остановки аудио, выбранный язык и до 80 терминов по должности сначала отправляются в ElevenLabs, а при сбое — в Azure. InterviewThread не хранит и не журналирует аудио; поставщики могут обрабатывать или сохранять его по своим правилам. Ничего не отправляется, пока вы не проверите текст и не нажмёте «Отправить».",
    browserBody: "Браузер создаёт субтитры и может использовать речевой сервис своего поставщика. InterviewThread не загружает и не сохраняет аудио. Ничего не отправляется автоматически.",
    cloudButton: "Облачный ввод", browserButton: "Субтитры браузера", typeButton: "Ввести текст", privacyLink: "Конфиденциальность", coachedButton: "Попробовать голос тренера",
    coachedNotice: "Текущая запись отдельно отправляется в ElevenLabs, чтобы вернуть преобразованный голос для тренировки. InterviewThread её не сохраняет; действует политика ElevenLabs.",
    coachedReady: "Голос тренера готов", coachedUnavailable: "Голос тренера недоступен",
  },
  uk: {
    title: "Використати мікрофон?",
    cloudBody: "Після входу браузер створює чернетку наживо. Після зупинки аудіо, вибрана мова й до 80 термінів щодо посади спочатку надсилаються до ElevenLabs, а за потреби — до Azure. InterviewThread не зберігає й не журналює аудіо; постачальники можуть обробляти чи зберігати його за власними правилами. Нічого не надсилається, доки ви не перевірите текст і не натиснете «Надіслати».",
    browserBody: "Браузер створює субтитри й може використовувати мовленнєву службу свого постачальника. InterviewThread не завантажує й не зберігає аудіо. Нічого не надсилається автоматично.",
    cloudButton: "Хмарне введення", browserButton: "Субтитри браузера", typeButton: "Ввести текст", privacyLink: "Конфіденційність", coachedButton: "Спробувати голос тренера",
    coachedNotice: "Поточний запис окремо надсилається до ElevenLabs, щоб повернути перетворений голос для тренування. InterviewThread його не зберігає; діє політика ElevenLabs.",
    coachedReady: "Голос тренера готовий", coachedUnavailable: "Голос тренера недоступний",
  },
  ar: {
    title: "هل تريد استخدام الميكروفون؟",
    cloudBody: "عند تسجيل الدخول، ينشئ المتصفح مسودة مباشرة. بعد إيقاف التسجيل، يُرسل الصوت واللغة المختارة وما يصل إلى 80 مصطلحًا وظيفيًا أولًا إلى ElevenLabs، مع استخدام Azure كخيار احتياطي. لا يخزّن InterviewThread الصوت ولا يسجّله؛ وقد يعالجه مزودو الخدمة أو يحتفظون به وفق سياساتهم. لن يُرسل شيء حتى تراجعه وتضغط «إرسال».",
    browserBody: "ينشئ المتصفح تسميات توضيحية وقد يستخدم خدمة الكلام التابعة لمزوده. لا يرفع InterviewThread الصوت ولا يحفظه، ولا يُرسل شيء تلقائيًا.",
    cloudButton: "استخدام الصوت السحابي", browserButton: "استخدام تسميات المتصفح", typeButton: "الكتابة بدلًا من ذلك", privacyLink: "الخصوصية", coachedButton: "تجربة الصوت التدريبي",
    coachedNotice: "يُرسل التسجيل الحالي بشكل منفصل إلى ElevenLabs لإرجاع صوت تدريبي محوّل. لا يحفظه InterviewThread؛ وتُطبّق سياسة ElevenLabs.",
    coachedReady: "الصوت التدريبي جاهز", coachedUnavailable: "الصوت التدريبي غير متاح",
  },
  he: {
    title: "להשתמש במיקרופון?",
    cloudBody: "לאחר הכניסה לחשבון, הדפדפן יוצר טיוטה בזמן אמת. עם עצירת ההקלטה, השמע, השפה שנבחרה ועד 80 מונחי תפקיד נשלחים תחילה ל-ElevenLabs, ובמקרה הצורך ל-Azure. ‏InterviewThread אינו שומר או מתעד שמע; הספקים עשויים לעבד או לשמור אותו בהתאם למדיניות שלהם. דבר לא נשלח לפני שבודקים ולוחצים על „שליחה”.",
    browserBody: "הדפדפן יוצר כתוביות ועשוי להשתמש בשירות הדיבור של הספק שלו. ‏InterviewThread אינו מעלה או שומר שמע. דבר לא נשלח אוטומטית.",
    cloudButton: "שימוש בקול בענן", browserButton: "שימוש בכתוביות", typeButton: "הקלדה במקום", privacyLink: "פרטיות", coachedButton: "ניסיון קול מודרך",
    coachedNotice: "ההקלטה הנוכחית נשלחת בנפרד ל-ElevenLabs כדי להחזיר קול תרגול שעבר שינוי. ‏InterviewThread אינו שומר אותה; מדיניות ElevenLabs חלה.",
    coachedReady: "הקול המודרך מוכן", coachedUnavailable: "הקול המודרך אינו זמין",
  },
  hi: {
    title: "माइक्रोफ़ोन इस्तेमाल करें?",
    cloudBody: "साइन इन होने पर आपका ब्राउज़र लाइव ड्राफ़्ट बनाता है। रिकॉर्डिंग रोकने के बाद ऑडियो, चुनी हुई भाषा और अधिकतम 80 भूमिका-संबंधी शब्द पहले ElevenLabs को और ज़रूरत पड़ने पर Azure को भेजे जाते हैं। InterviewThread ऑडियो को संग्रहीत या लॉग नहीं करता; प्रदाता अपनी नीतियों के अनुसार इसे प्रोसेस या रख सकते हैं। आपके जाँचकर “भेजें” दबाने तक कुछ भी सबमिट नहीं होता।",
    browserBody: "आपका ब्राउज़र कैप्शन बनाता है और अपने विक्रेता की स्पीच सेवा इस्तेमाल कर सकता है। InterviewThread ऑडियो अपलोड या सेव नहीं करता। कुछ भी अपने-आप सबमिट नहीं होता।",
    cloudButton: "क्लाउड वॉइस इस्तेमाल करें", browserButton: "ब्राउज़र कैप्शन", typeButton: "टाइप करें", privacyLink: "गोपनीयता", coachedButton: "कोच्ड वॉइस आज़माएँ",
    coachedNotice: "मौजूदा रिकॉर्डिंग अलग से ElevenLabs को भेजी जाती है, जो अभ्यास के लिए बदली हुई आवाज़ लौटाता है। InterviewThread इसे सेव नहीं करता; ElevenLabs की नीति लागू होती है।",
    coachedReady: "कोच्ड वॉइस तैयार", coachedUnavailable: "कोच्ड वॉइस उपलब्ध नहीं",
  },
  bn: {
    title: "মাইক্রোফোন ব্যবহার করবেন?",
    cloudBody: "সাইন ইন করা থাকলে ব্রাউজার সরাসরি একটি খসড়া তৈরি করে। রেকর্ডিং থামানোর পর অডিও, নির্বাচিত ভাষা এবং সর্বোচ্চ ৮০টি পদ-সংক্রান্ত শব্দ প্রথমে ElevenLabs-এ, প্রয়োজনে Azure-এ পাঠানো হয়। InterviewThread অডিও সংরক্ষণ বা লগ করে না; সরবরাহকারীরা তাদের নীতি অনুযায়ী এটি প্রক্রিয়া বা রেখে দিতে পারে। আপনি দেখে “পাঠান” চাপার আগে কিছুই জমা হয় না।",
    browserBody: "ব্রাউজার ক্যাপশন তৈরি করে এবং তার সরবরাহকারীর স্পিচ পরিষেবা ব্যবহার করতে পারে। InterviewThread অডিও আপলোড বা সংরক্ষণ করে না। কিছুই স্বয়ংক্রিয়ভাবে জমা হয় না।",
    cloudButton: "ক্লাউড ভয়েস ব্যবহার", browserButton: "ব্রাউজার ক্যাপশন", typeButton: "লিখে উত্তর দিন", privacyLink: "গোপনীয়তা", coachedButton: "প্রশিক্ষিত ভয়েস চেষ্টা করুন",
    coachedNotice: "বর্তমান রেকর্ডিংটি আলাদাভাবে ElevenLabs-এ পাঠিয়ে অনুশীলনের জন্য রূপান্তরিত কণ্ঠ ফেরত আনা হয়। InterviewThread এটি সংরক্ষণ করে না; ElevenLabs-এর নীতি প্রযোজ্য।",
    coachedReady: "প্রশিক্ষিত ভয়েস প্রস্তুত", coachedUnavailable: "প্রশিক্ষিত ভয়েস অনুপলভ্য",
  },
  ur: {
    title: "مائیکروفون استعمال کریں؟",
    cloudBody: "سائن اِن ہونے پر براؤزر براہِ راست مسودہ بناتا ہے۔ ریکارڈنگ روکنے کے بعد آڈیو، منتخب زبان اور عہدے کی 80 تک اصطلاحات پہلے ElevenLabs اور ضرورت پڑنے پر Azure کو بھیجی جاتی ہیں۔ InterviewThread آڈیو محفوظ یا لاگ نہیں کرتا؛ فراہم کنندگان اپنی پالیسیوں کے تحت اسے پراسیس یا برقرار رکھ سکتے ہیں۔ آپ کے جائزہ لینے اور ”بھیجیں“ دبانے تک کچھ جمع نہیں ہوتا۔",
    browserBody: "براؤزر کیپشن بناتا ہے اور اپنے فراہم کنندہ کی اسپیچ سروس استعمال کر سکتا ہے۔ InterviewThread آڈیو اپ لوڈ یا محفوظ نہیں کرتا۔ کچھ بھی خودکار طور پر جمع نہیں ہوتا۔",
    cloudButton: "کلاؤڈ وائس استعمال کریں", browserButton: "براؤزر کیپشن", typeButton: "لکھ کر جواب دیں", privacyLink: "رازداری", coachedButton: "تربیتی آواز آزمائیں",
    coachedNotice: "موجودہ ریکارڈنگ الگ سے ElevenLabs کو بھیجی جاتی ہے تاکہ مشق کے لیے تبدیل شدہ آواز واپس ملے۔ InterviewThread اسے محفوظ نہیں کرتا؛ ElevenLabs کی پالیسی لاگو ہوتی ہے۔",
    coachedReady: "تربیتی آواز تیار ہے", coachedUnavailable: "تربیتی آواز دستیاب نہیں",
  },
  id: {
    title: "Gunakan mikrofon?",
    cloudBody: "Saat masuk, browser Anda membuat draf langsung. Setelah rekaman dihentikan, audio, bahasa pilihan, dan hingga 80 istilah peran dikirim lebih dulu ke ElevenLabs, dengan Azure sebagai cadangan. InterviewThread tidak menyimpan atau mencatat audio; penyedia dapat memproses atau menyimpannya sesuai kebijakan mereka. Tidak ada yang dikirim sebelum Anda meninjau dan menekan “Kirim”.",
    browserBody: "Browser Anda membuat teks dan mungkin memakai layanan ucapan vendornya. InterviewThread tidak mengunggah atau menyimpan audio. Tidak ada yang dikirim otomatis.",
    cloudButton: "Gunakan suara cloud", browserButton: "Gunakan teks browser", typeButton: "Ketik saja", privacyLink: "Privasi", coachedButton: "Coba suara terpandu",
    coachedNotice: "Rekaman saat ini dikirim secara terpisah ke ElevenLabs untuk menghasilkan suara latihan yang diubah. InterviewThread tidak menyimpannya; kebijakan ElevenLabs berlaku.",
    coachedReady: "Suara terpandu siap", coachedUnavailable: "Suara terpandu tidak tersedia",
  },
  ms: {
    title: "Gunakan mikrofon?",
    cloudBody: "Apabila anda mendaftar masuk, pelayar menghasilkan draf langsung. Selepas rakaman dihentikan, audio, bahasa pilihan dan sehingga 80 istilah jawatan dihantar dahulu kepada ElevenLabs, dengan Azure sebagai pilihan sandaran. InterviewThread tidak menyimpan atau merekodkan audio; penyedia boleh memproses atau menyimpannya mengikut dasar mereka. Tiada apa-apa dihantar sehingga anda menyemak dan menekan “Hantar”.",
    browserBody: "Pelayar menghasilkan sari kata dan mungkin menggunakan perkhidmatan pertuturan vendornya. InterviewThread tidak memuat naik atau menyimpan audio. Tiada apa-apa dihantar secara automatik.",
    cloudButton: "Gunakan suara awan", browserButton: "Gunakan sari kata", typeButton: "Taip sahaja", privacyLink: "Privasi", coachedButton: "Cuba suara bimbingan",
    coachedNotice: "Rakaman semasa dihantar secara berasingan kepada ElevenLabs untuk menghasilkan suara latihan yang diubah. InterviewThread tidak menyimpannya; dasar ElevenLabs terpakai.",
    coachedReady: "Suara bimbingan sedia", coachedUnavailable: "Suara bimbingan tidak tersedia",
  },
  th: {
    title: "ใช้ไมโครโฟนหรือไม่?",
    cloudBody: "เมื่อลงชื่อเข้าใช้ เบราว์เซอร์จะสร้างฉบับร่างแบบสด หลังหยุดบันทึก เสียง ภาษาที่เลือก และคำศัพท์เกี่ยวกับตำแหน่งสูงสุด 80 คำจะถูกส่งไปยัง ElevenLabs ก่อน โดยมี Azure เป็นระบบสำรอง InterviewThread ไม่จัดเก็บหรือบันทึกล็อกเสียง แต่ผู้ให้บริการอาจประมวลผลหรือเก็บไว้ตามนโยบายของตน จะไม่มีการส่งคำตอบจนกว่าคุณจะตรวจสอบและกด “ส่ง”",
    browserBody: "เบราว์เซอร์จะสร้างคำบรรยายและอาจใช้บริการเสียงของผู้ให้บริการเบราว์เซอร์ InterviewThread ไม่อัปโหลดหรือบันทึกเสียง และจะไม่ส่งสิ่งใดโดยอัตโนมัติ",
    cloudButton: "ใช้เสียงผ่านคลาวด์", browserButton: "ใช้คำบรรยายเบราว์เซอร์", typeButton: "พิมพ์แทน", privacyLink: "ความเป็นส่วนตัว", coachedButton: "ลองเสียงฝึกซ้อม",
    coachedNotice: "ระบบจะส่งไฟล์บันทึกปัจจุบันแยกต่างหากไปยัง ElevenLabs เพื่อสร้างเสียงฝึกซ้อมที่ผ่านการแปลง InterviewThread ไม่บันทึกไฟล์นี้ และเป็นไปตามนโยบายของ ElevenLabs",
    coachedReady: "เสียงฝึกซ้อมพร้อมแล้ว", coachedUnavailable: "เสียงฝึกซ้อมไม่พร้อมใช้งาน",
  },
  vi: {
    title: "Dùng micrô?",
    cloudBody: "Khi đăng nhập, trình duyệt tạo bản nháp trực tiếp. Sau khi bạn dừng, âm thanh, ngôn ngữ đã chọn và tối đa 80 thuật ngữ về vai trò được gửi trước tới ElevenLabs, với Azure làm phương án dự phòng. InterviewThread không lưu hay ghi nhật ký âm thanh; nhà cung cấp có thể xử lý hoặc lưu giữ theo chính sách của họ. Không nội dung nào được gửi cho đến khi bạn xem lại và nhấn “Gửi”.",
    browserBody: "Trình duyệt tạo phụ đề và có thể dùng dịch vụ giọng nói của nhà cung cấp. InterviewThread không tải lên hoặc lưu âm thanh. Không nội dung nào được tự động gửi.",
    cloudButton: "Dùng giọng nói đám mây", browserButton: "Dùng phụ đề trình duyệt", typeButton: "Nhập văn bản", privacyLink: "Quyền riêng tư", coachedButton: "Thử giọng luyện tập",
    coachedNotice: "Bản ghi hiện tại được gửi riêng tới ElevenLabs để trả về giọng luyện tập đã biến đổi. InterviewThread không lưu bản ghi; chính sách của ElevenLabs được áp dụng.",
    coachedReady: "Giọng luyện tập đã sẵn sàng", coachedUnavailable: "Giọng luyện tập không khả dụng",
  },
  fil: {
    title: "Gamitin ang mikropono?",
    cloudBody: "Kapag naka-sign in, gumagawa ang browser ng live na draft. Pagkatapos mong huminto, ipinapadala muna sa ElevenLabs ang audio, napiling wika, at hanggang 80 termino ng tungkulin, at Azure ang fallback. Hindi sine-save o nila-log ng InterviewThread ang audio; maaari itong iproseso o panatilihin ng mga provider ayon sa kanilang mga patakaran. Walang isusumite hangga’t hindi mo sinusuri at pinipindot ang “Ipadala”.",
    browserBody: "Gumagawa ang browser ng mga caption at maaaring gamitin ang speech service ng vendor nito. Hindi ina-upload o sine-save ng InterviewThread ang audio. Walang awtomatikong isinusumite.",
    cloudButton: "Gamitin ang cloud voice", browserButton: "Gamitin ang mga caption", typeButton: "Mag-type na lang", privacyLink: "Privacy", coachedButton: "Subukan ang guided voice",
    coachedNotice: "Hiwalay na ipinapadala sa ElevenLabs ang kasalukuyang recording para gumawa ng binagong boses sa pagsasanay. Hindi ito sine-save ng InterviewThread; nalalapat ang patakaran ng ElevenLabs.",
    coachedReady: "Handa na ang guided voice", coachedUnavailable: "Hindi available ang guided voice",
  },
  sv: {
    title: "Använda mikrofonen?",
    cloudBody: "När du är inloggad skapar webbläsaren ett utkast direkt. När du stoppar skickas ljudet, valt språk och upp till 80 rolltermer först till ElevenLabs, med Azure som reserv. InterviewThread lagrar eller loggar inte ljud; leverantörerna kan behandla eller behålla det enligt sina policyer. Inget skickas förrän du har granskat och tryckt på ”Skicka”.",
    browserBody: "Webbläsaren skapar undertexter och kan använda leverantörens taltjänst. InterviewThread laddar inte upp eller sparar ljud. Inget skickas automatiskt.",
    cloudButton: "Använd molnröst", browserButton: "Använd undertexter", typeButton: "Skriv i stället", privacyLink: "Integritet", coachedButton: "Prova coachad röst",
    coachedNotice: "Den aktuella inspelningen skickas separat till ElevenLabs för att skapa en omvandlad övningsröst. InterviewThread sparar den inte; ElevenLabs policy gäller.",
    coachedReady: "Coachad röst klar", coachedUnavailable: "Coachad röst ej tillgänglig",
  },
  no: {
    title: "Bruke mikrofonen?",
    cloudBody: "Når du er logget inn, lager nettleseren et direkteutkast. Når du stopper, sendes lyd, valgt språk og opptil 80 stillingstermer først til ElevenLabs, med Azure som reserve. InterviewThread lagrer eller logger ikke lyd; leverandørene kan behandle eller oppbevare den i henhold til sine retningslinjer. Ingenting sendes før du har sett gjennom og trykket «Send».",
    browserBody: "Nettleseren lager undertekster og kan bruke leverandørens taletjeneste. InterviewThread laster ikke opp eller lagrer lyd. Ingenting sendes automatisk.",
    cloudButton: "Bruk skytjeneste", browserButton: "Bruk undertekster", typeButton: "Skriv i stedet", privacyLink: "Personvern", coachedButton: "Prøv veiledet stemme",
    coachedNotice: "Det gjeldende opptaket sendes separat til ElevenLabs for å lage en omformet øvingsstemme. InterviewThread lagrer det ikke; ElevenLabs’ retningslinjer gjelder.",
    coachedReady: "Veiledet stemme klar", coachedUnavailable: "Veiledet stemme utilgjengelig",
  },
  da: {
    title: "Brug mikrofonen?",
    cloudBody: "Når du er logget ind, opretter browseren en livekladde. Når du stopper, sendes lyd, valgt sprog og op til 80 stillingstermer først til ElevenLabs med Azure som reserve. InterviewThread gemmer eller logger ikke lyd; udbyderne kan behandle eller opbevare den efter deres politikker. Intet sendes, før du har gennemset det og trykket på “Send”.",
    browserBody: "Browseren opretter undertekster og kan bruge leverandørens taletjeneste. InterviewThread uploader eller gemmer ikke lyd. Intet sendes automatisk.",
    cloudButton: "Brug cloudstemme", browserButton: "Brug undertekster", typeButton: "Skriv i stedet", privacyLink: "Privatliv", coachedButton: "Prøv vejledt stemme",
    coachedNotice: "Den aktuelle optagelse sendes separat til ElevenLabs for at skabe en omdannet øvelsesstemme. InterviewThread gemmer den ikke; ElevenLabs’ politik gælder.",
    coachedReady: "Vejledt stemme klar", coachedUnavailable: "Vejledt stemme ikke tilgængelig",
  },
  fi: {
    title: "Käytetäänkö mikrofonia?",
    cloudBody: "Kun olet kirjautunut sisään, selain luo luonnoksen reaaliajassa. Kun pysäytät tallennuksen, ääni, valittu kieli ja enintään 80 tehtävätermiä lähetetään ensin ElevenLabsille ja tarvittaessa Azurelle. InterviewThread ei tallenna tai lokita ääntä; palveluntarjoajat voivat käsitellä tai säilyttää sitä omien käytäntöjensä mukaisesti. Mitään ei lähetetä, ennen kuin tarkistat sisällön ja painat Lähetä.",
    browserBody: "Selain luo tekstityksen ja voi käyttää toimittajansa puhepalvelua. InterviewThread ei lataa tai tallenna ääntä. Mitään ei lähetetä automaattisesti.",
    cloudButton: "Käytä pilvipuhetta", browserButton: "Käytä tekstitystä", typeButton: "Kirjoita", privacyLink: "Tietosuoja", coachedButton: "Kokeile ohjattua ääntä",
    coachedNotice: "Nykyinen tallenne lähetetään erikseen ElevenLabsille muunnetun harjoitusäänen tuottamista varten. InterviewThread ei tallenna sitä; ElevenLabsin käytäntöä sovelletaan.",
    coachedReady: "Ohjattu ääni valmis", coachedUnavailable: "Ohjattu ääni ei käytettävissä",
  },
  cs: {
    title: "Použít mikrofon?",
    cloudBody: "Po přihlášení prohlížeč vytváří živý koncept. Po zastavení se zvuk, vybraný jazyk a až 80 pojmů k pracovní pozici odešlou nejprve do ElevenLabs, případně do Azure. InterviewThread zvuk neukládá ani neprotokoluje; poskytovatelé jej mohou zpracovat či uchovat podle svých zásad. Nic se neodešle, dokud obsah nezkontrolujete a nestisknete „Odeslat“.",
    browserBody: "Prohlížeč vytváří titulky a může používat řečovou službu svého dodavatele. InterviewThread zvuk nenahrává ani neukládá. Nic se neodesílá automaticky.",
    cloudButton: "Použít cloudový hlas", browserButton: "Použít titulky", typeButton: "Napsat odpověď", privacyLink: "Soukromí", coachedButton: "Vyzkoušet tréninkový hlas",
    coachedNotice: "Aktuální nahrávka se samostatně odešle do ElevenLabs, aby vznikl upravený hlas pro nácvik. InterviewThread ji neukládá; platí zásady ElevenLabs.",
    coachedReady: "Tréninkový hlas je připraven", coachedUnavailable: "Tréninkový hlas není dostupný",
  },
  sk: {
    title: "Použiť mikrofón?",
    cloudBody: "Po prihlásení prehliadač vytvára živý koncept. Po zastavení sa zvuk, vybraný jazyk a až 80 pojmov k pracovnej pozícii odošlú najprv do ElevenLabs, prípadne do Azure. InterviewThread zvuk neukladá ani nezaznamenáva; poskytovatelia ho môžu spracovať alebo uchovať podľa svojich zásad. Nič sa neodošle, kým obsah neskontrolujete a nestlačíte „Odoslať“.",
    browserBody: "Prehliadač vytvára titulky a môže používať rečovú službu svojho dodávateľa. InterviewThread zvuk nenahráva ani neukladá. Nič sa neodosiela automaticky.",
    cloudButton: "Použiť cloudový hlas", browserButton: "Použiť titulky", typeButton: "Napísať odpoveď", privacyLink: "Súkromie", coachedButton: "Vyskúšať tréningový hlas",
    coachedNotice: "Aktuálna nahrávka sa samostatne odošle do ElevenLabs, aby vznikol upravený hlas na nácvik. InterviewThread ju neukladá; platia zásady ElevenLabs.",
    coachedReady: "Tréningový hlas je pripravený", coachedUnavailable: "Tréningový hlas nie je dostupný",
  },
  hu: {
    title: "Használja a mikrofont?",
    cloudBody: "Bejelentkezés után a böngésző élő piszkozatot készít. A felvétel leállításakor a hang, a kiválasztott nyelv és legfeljebb 80 munkaköri kifejezés először az ElevenLabshoz, szükség esetén az Azure-höz kerül. Az InterviewThread nem tárolja és nem naplózza a hangot; a szolgáltatók saját szabályzatuk szerint feldolgozhatják vagy megőrizhetik. Semmi sem kerül elküldésre, amíg át nem nézi és meg nem nyomja a „Küldés” gombot.",
    browserBody: "A böngésző feliratokat készít, és használhatja a szolgáltató beszédfelismerő szolgáltatását. Az InterviewThread nem tölti fel és nem menti a hangot. Semmi sem kerül automatikusan elküldésre.",
    cloudButton: "Felhőalapú hangbevitel", browserButton: "Böngészőfeliratok", typeButton: "Szöveges válasz", privacyLink: "Adatvédelem", coachedButton: "Gyakorlóhang kipróbálása",
    coachedNotice: "Az aktuális felvétel külön kerül az ElevenLabshoz, amely átalakított gyakorlóhangot ad vissza. Az InterviewThread nem menti; az ElevenLabs szabályzata érvényes.",
    coachedReady: "Gyakorlóhang kész", coachedUnavailable: "Gyakorlóhang nem érhető el",
  },
  ro: {
    title: "Folosiți microfonul?",
    cloudBody: "După autentificare, browserul creează o ciornă în direct. Când opriți înregistrarea, sunetul, limba aleasă și până la 80 de termeni ai rolului sunt trimise mai întâi la ElevenLabs, cu Azure ca rezervă. InterviewThread nu stochează și nu înregistrează în jurnale sunetul; furnizorii îl pot procesa sau păstra conform politicilor proprii. Nimic nu este trimis până când nu verificați și apăsați „Trimiteți”.",
    browserBody: "Browserul creează subtitrări și poate folosi serviciul vocal al furnizorului său. InterviewThread nu încarcă și nu salvează sunetul. Nimic nu este trimis automat.",
    cloudButton: "Folosiți vocea cloud", browserButton: "Folosiți subtitrările", typeButton: "Scrieți", privacyLink: "Confidențialitate", coachedButton: "Încercați vocea ghidată",
    coachedNotice: "Înregistrarea curentă este trimisă separat la ElevenLabs pentru a genera o voce de exercițiu transformată. InterviewThread nu o salvează; se aplică politica ElevenLabs.",
    coachedReady: "Vocea ghidată este gata", coachedUnavailable: "Vocea ghidată nu este disponibilă",
  },
  el: {
    title: "Χρήση μικροφώνου;",
    cloudBody: "Μετά τη σύνδεση, το πρόγραμμα περιήγησης δημιουργεί ζωντανά ένα πρόχειρο. Όταν σταματήσετε, ο ήχος, η επιλεγμένη γλώσσα και έως 80 όροι του ρόλου αποστέλλονται πρώτα στην ElevenLabs, με το Azure ως εφεδρεία. Το InterviewThread δεν αποθηκεύει ούτε καταγράφει τον ήχο· οι πάροχοι μπορεί να τον επεξεργαστούν ή να τον διατηρήσουν βάσει των πολιτικών τους. Τίποτα δεν υποβάλλεται μέχρι να το ελέγξετε και να πατήσετε «Αποστολή».",
    browserBody: "Το πρόγραμμα περιήγησης δημιουργεί υπότιτλους και μπορεί να χρησιμοποιεί την υπηρεσία ομιλίας του προμηθευτή του. Το InterviewThread δεν ανεβάζει ούτε αποθηκεύει ήχο. Τίποτα δεν υποβάλλεται αυτόματα.",
    cloudButton: "Χρήση φωνής cloud", browserButton: "Χρήση υποτίτλων", typeButton: "Πληκτρολόγηση", privacyLink: "Απόρρητο", coachedButton: "Δοκιμή καθοδηγούμενης φωνής",
    coachedNotice: "Η τρέχουσα εγγραφή αποστέλλεται ξεχωριστά στην ElevenLabs για να επιστραφεί μια μεταμορφωμένη φωνή εξάσκησης. Το InterviewThread δεν την αποθηκεύει· ισχύει η πολιτική της ElevenLabs.",
    coachedReady: "Η καθοδηγούμενη φωνή είναι έτοιμη", coachedUnavailable: "Η καθοδηγούμενη φωνή δεν είναι διαθέσιμη",
  },
  bg: {
    title: "Да се използва ли микрофонът?",
    cloudBody: "След влизане браузърът създава чернова на живо. След спиране аудиото, избраният език и до 80 термина за длъжността се изпращат първо до ElevenLabs, а при нужда — до Azure. InterviewThread не съхранява и не регистрира аудио; доставчиците могат да го обработват или пазят според своите правила. Нищо не се изпраща, докато не го прегледате и не натиснете „Изпращане“.",
    browserBody: "Браузърът създава надписи и може да използва речевата услуга на своя доставчик. InterviewThread не качва и не запазва аудио. Нищо не се изпраща автоматично.",
    cloudButton: "Глас през облака", browserButton: "Надписи от браузъра", typeButton: "Въвеждане на текст", privacyLink: "Поверителност", coachedButton: "Проба с тренировъчен глас",
    coachedNotice: "Текущият запис се изпраща отделно до ElevenLabs, за да бъде върнат преобразуван глас за упражнение. InterviewThread не го запазва; прилага се политиката на ElevenLabs.",
    coachedReady: "Тренировъчният глас е готов", coachedUnavailable: "Тренировъчният глас не е достъпен",
  },
  hr: {
    title: "Upotrijebiti mikrofon?",
    cloudBody: "Nakon prijave preglednik uživo izrađuje skicu. Kada zaustavite snimanje, zvuk, odabrani jezik i do 80 pojmova za radno mjesto prvo se šalju ElevenLabsu, a po potrebi Azureu. InterviewThread ne pohranjuje ni bilježi zvuk; pružatelji ga mogu obrađivati ili zadržati prema svojim pravilima. Ništa se ne šalje dok ne pregledate sadržaj i pritisnete „Pošalji”.",
    browserBody: "Preglednik izrađuje titlove i može upotrebljavati govornu uslugu svojeg dobavljača. InterviewThread ne prenosi ni sprema zvuk. Ništa se ne šalje automatski.",
    cloudButton: "Glas putem oblaka", browserButton: "Titlovi preglednika", typeButton: "Upiši tekst", privacyLink: "Privatnost", coachedButton: "Isprobaj vođeni glas",
    coachedNotice: "Trenutačna snimka zasebno se šalje ElevenLabsu kako bi se izradio preoblikovani glas za vježbu. InterviewThread je ne sprema; primjenjuju se pravila ElevenLabsa.",
    coachedReady: "Vođeni glas je spreman", coachedUnavailable: "Vođeni glas nije dostupan",
  },
  sr: {
    title: "Користити микрофон?",
    cloudBody: "Након пријаве прегледач уживо прави нацрт. Када зауставите снимање, звук, изабрани језик и до 80 појмова за радно место прво се шаљу ElevenLabs-у, а по потреби Azure-у. InterviewThread не чува нити евидентира звук; добављачи га могу обрађивати или задржати према својим правилима. Ништа се не шаље док не прегледате садржај и притиснете „Пошаљи”.",
    browserBody: "Прегледач прави титлове и може користити говорну услугу свог добављача. InterviewThread не отпрема нити чува звук. Ништа се не шаље аутоматски.",
    cloudButton: "Глас преко облака", browserButton: "Титлови прегледача", typeButton: "Унеси текст", privacyLink: "Приватност", coachedButton: "Испробај вођени глас",
    coachedNotice: "Тренутни снимак се засебно шаље ElevenLabs-у како би се вратио преобликовани глас за вежбу. InterviewThread га не чува; примењују се правила ElevenLabs-а.",
    coachedReady: "Вођени глас је спреман", coachedUnavailable: "Вођени глас није доступан",
  },
  sl: {
    title: "Uporabim mikrofon?",
    cloudBody: "Po prijavi brskalnik sproti ustvari osnutek. Ko snemanje ustavite, se zvok, izbrani jezik in do 80 izrazov za delovno mesto najprej pošljejo družbi ElevenLabs, po potrebi pa storitvi Azure. InterviewThread zvoka ne shranjuje ali beleži; ponudniki ga lahko obdelajo ali hranijo skladno s svojimi pravilniki. Nič se ne pošlje, dokler vsebine ne pregledate in pritisnete »Pošlji«.",
    browserBody: "Brskalnik ustvari podnapise in lahko uporabi govorno storitev svojega ponudnika. InterviewThread zvoka ne naloži ali shrani. Nič se ne pošlje samodejno.",
    cloudButton: "Uporabi glas v oblaku", browserButton: "Uporabi podnapise", typeButton: "Vnesi besedilo", privacyLink: "Zasebnost", coachedButton: "Preizkusi vodeni glas",
    coachedNotice: "Trenutni posnetek se ločeno pošlje družbi ElevenLabs, da ustvari preoblikovan glas za vajo. InterviewThread ga ne shrani; velja pravilnik družbe ElevenLabs.",
    coachedReady: "Vodeni glas je pripravljen", coachedUnavailable: "Vodeni glas ni na voljo",
  },
  sw: {
    title: "Utumie maikrofoni?",
    cloudBody: "Ukiwa umeingia, kivinjari hutengeneza rasimu ya moja kwa moja. Ukisimamisha rekodi, sauti, lugha uliyochagua na hadi istilahi 80 za nafasi hutumwa kwanza ElevenLabs, huku Azure ikiwa chaguo la akiba. InterviewThread haihifadhi wala kurekodi sauti kwenye kumbukumbu; watoa huduma wanaweza kuichakata au kuihifadhi kulingana na sera zao. Hakuna kinachowasilishwa hadi ukague na ubonyeze “Tuma”.",
    browserBody: "Kivinjari hutengeneza manukuu na kinaweza kutumia huduma ya usemi ya mtoa huduma wake. InterviewThread haipakii wala kuhifadhi sauti. Hakuna kinachowasilishwa kiotomatiki.",
    cloudButton: "Tumia sauti ya wingu", browserButton: "Tumia manukuu", typeButton: "Andika badala yake", privacyLink: "Faragha", coachedButton: "Jaribu sauti ya mazoezi",
    coachedNotice: "Rekodi ya sasa hutumwa kando kwa ElevenLabs ili kurejesha sauti ya mazoezi iliyobadilishwa. InterviewThread haihifadhi; sera ya ElevenLabs inatumika.",
    coachedReady: "Sauti ya mazoezi iko tayari", coachedUnavailable: "Sauti ya mazoezi haipatikani",
  },
  fa: {
    title: "از میکروفون استفاده شود؟",
    cloudBody: "پس از ورود، مرورگر یک پیش‌نویس زنده می‌سازد. با توقف ضبط، صدا، زبان انتخاب‌شده و حداکثر ۸۰ اصطلاح شغلی ابتدا به ElevenLabs و در صورت نیاز به Azure فرستاده می‌شود. InterviewThread صدا را ذخیره یا ثبت نمی‌کند؛ ارائه‌دهندگان ممکن است طبق سیاست‌های خود آن را پردازش یا نگهداری کنند. تا زمانی که محتوا را بازبینی نکنید و «ارسال» را نزنید، چیزی ارسال نمی‌شود.",
    browserBody: "مرورگر زیرنویس می‌سازد و ممکن است از سرویس گفتار ارائه‌دهندهٔ خود استفاده کند. InterviewThread صدا را بارگذاری یا ذخیره نمی‌کند و چیزی خودکار ارسال نمی‌شود.",
    cloudButton: "استفاده از صدای ابری", browserButton: "استفاده از زیرنویس", typeButton: "پاسخ نوشتاری", privacyLink: "حریم خصوصی", coachedButton: "آزمایش صدای تمرینی",
    coachedNotice: "ضبط فعلی جداگانه به ElevenLabs فرستاده می‌شود تا صدای تمرینیِ تغییریافته برگردانده شود. InterviewThread آن را ذخیره نمی‌کند؛ سیاست ElevenLabs اعمال می‌شود.",
    coachedReady: "صدای تمرینی آماده است", coachedUnavailable: "صدای تمرینی در دسترس نیست",
  },
} satisfies Record<LocaleCode, MicrophoneConsentCopy>;

export function voiceConsentCopyFor(locale: LocaleCode) {
  const copy = MICROPHONE_CONSENT_COPY[locale];
  return {
    ...copy,
    // Preserve each locale's reviewed wording while keeping the production
    // provider names precise across all 40 consent dialogs.
    cloudBody: copy.cloudBody
      .replace(/ElevenLabs(?! Scribe)/, "ElevenLabs Scribe")
      .replace(/Azure(?! Speech)/g, "Microsoft Azure Speech"),
  };
}
